<?php

namespace Database\Seeders;

use App\Models\DataProtectionAuthority;
use App\Models\DataProtectionAuthorityPostalCodeRange;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

/**
 * Seed der 16 Landes-Datenschutzbehörden + BfDI mit ihren PLZ-Bereichen.
 *
 * Quellen: offizielle Webseiten der Behörden (Stand 2026), PLZ-Leitregionen
 * der Deutschen Post. Edge-Cases an Bundesland-Grenzen werden bewusst nicht
 * abgebildet — der Nutzer kann den Vorschlag stets manuell überschreiben.
 */
class DataProtectionAuthoritiesSeeder extends Seeder
{
    public function run(): void
    {
        DB::transaction(function (): void {
            foreach ($this->authorities() as $entry) {
                $authority = DataProtectionAuthority::updateOrCreate(
                    ['key' => $entry['key']],
                    collect($entry)->except(['ranges'])->toArray(),
                );

                $authority->postalCodeRanges()->delete();
                foreach ($entry['ranges'] as $range) {
                    DataProtectionAuthorityPostalCodeRange::create([
                        'data_protection_authority_id' => $authority->id,
                        'plz_from' => $range[0],
                        'plz_to' => $range[1],
                        'notes' => $range[2] ?? null,
                    ]);
                }
            }
        });
    }

    /**
     * @return list<array{
     *   key: string,
     *   name: string,
     *   short_name: string,
     *   state: ?string,
     *   street: string,
     *   postal_code: string,
     *   city: string,
     *   phone: string,
     *   email: string,
     *   website: string,
     *   breach_notification_url: ?string,
     *   notes: ?string,
     *   sort: int,
     *   ranges: list<array{0:string, 1:string, 2?:string}>
     * }>
     */
    private function authorities(): array
    {
        return [
            [
                'key' => 'lfdi-bw',
                'name' => 'LfDI Baden-Württemberg',
                'short_name' => 'LfDI BW',
                'state' => 'Baden-Württemberg',
                'street' => 'Lautenschlagerstraße 20',
                'postal_code' => '70173',
                'city' => 'Stuttgart',
                'phone' => '+49 711 615541-0',
                'email' => 'poststelle@lfdi.bwl.de',
                'website' => 'https://www.baden-wuerttemberg.datenschutz.de',
                'breach_notification_url' => 'https://www.baden-wuerttemberg.datenschutz.de/online-meldung-datenpannen/',
                'notes' => null,
                'sort' => 10,
                'ranges' => [
                    ['68001', '69513', 'Mannheim, Heidelberg'],
                    ['70001', '79874', 'Stuttgart, Karlsruhe, Freiburg'],
                    ['88001', '88099'],
                    ['88300', '88515', 'Oberschwaben'],
                    ['88701', '89079', 'Bodensee, Ulm'],
                ],
            ],
            [
                'key' => 'baylda',
                'name' => 'Bayerisches Landesamt für Datenschutzaufsicht (BayLDA)',
                'short_name' => 'BayLDA',
                'state' => 'Bayern',
                'street' => 'Promenade 18',
                'postal_code' => '91522',
                'city' => 'Ansbach',
                'phone' => '+49 981 180093-0',
                'email' => 'poststelle@lda.bayern.de',
                'website' => 'https://www.lda.bayern.de',
                'breach_notification_url' => 'https://www.lda.bayern.de/de/datenpanne.html',
                'notes' => 'Zuständig für nicht-öffentliche Stellen (Privatwirtschaft) in Bayern. Für öffentliche Stellen ist der BayLfD zuständig.',
                'sort' => 20,
                'ranges' => [
                    ['80001', '87779', 'München, Augsburg, Allgäu'],
                    ['89081', '89619'],
                    ['89671', '89690'],
                    ['90001', '96489', 'Nürnberg, Bayreuth, Bamberg'],
                    ['97001', '97896', 'Würzburg, Aschaffenburg'],
                ],
            ],
            [
                'key' => 'bayLfd',
                'name' => 'Bayerischer Landesbeauftragter für den Datenschutz (BayLfD)',
                'short_name' => 'BayLfD',
                'state' => 'Bayern',
                'street' => 'Wagmüllerstraße 18',
                'postal_code' => '80538',
                'city' => 'München',
                'phone' => '+49 89 212672-0',
                'email' => 'poststelle@datenschutz-bayern.de',
                'website' => 'https://www.datenschutz-bayern.de',
                'breach_notification_url' => 'https://www.datenschutz-bayern.de/datenpanne/',
                'notes' => 'Nur für ÖFFENTLICHE Stellen in Bayern (Behörden, Schulen, Hochschulen). Für die Privatwirtschaft ist das BayLDA zuständig — der Vorschlag bei privaten Mandanten ist daher das BayLDA.',
                'sort' => 25,
                'ranges' => [],
            ],
            [
                'key' => 'blnbdi',
                'name' => 'Berliner Beauftragte für Datenschutz und Informationsfreiheit',
                'short_name' => 'BlnBDI',
                'state' => 'Berlin',
                'street' => 'Alt-Moabit 59-61',
                'postal_code' => '10555',
                'city' => 'Berlin',
                'phone' => '+49 30 13889-0',
                'email' => 'mailbox@datenschutz-berlin.de',
                'website' => 'https://www.datenschutz-berlin.de',
                'breach_notification_url' => 'https://www.datenschutz-berlin.de/datenpannen-meldung',
                'notes' => null,
                'sort' => 30,
                'ranges' => [
                    ['10001', '14199', 'Berlin (14200+ liegt in Brandenburg)'],
                ],
            ],
            [
                'key' => 'lda-bb',
                'name' => 'Landesbeauftragte für den Datenschutz Brandenburg',
                'short_name' => 'LDA BB',
                'state' => 'Brandenburg',
                'street' => 'Stahnsdorfer Damm 77',
                'postal_code' => '14532',
                'city' => 'Kleinmachnow',
                'phone' => '+49 33203 356-0',
                'email' => 'poststelle@lda.brandenburg.de',
                'website' => 'https://www.lda.brandenburg.de',
                'breach_notification_url' => 'https://www.lda.brandenburg.de/lda/de/themen/datenschutz/datenpannen-meldung/',
                'notes' => null,
                'sort' => 40,
                'ranges' => [
                    ['03001', '03253', 'Cottbus, Spreewald'],
                    ['14401', '16928', 'Potsdam, Frankfurt (Oder)'],
                ],
            ],
            [
                'key' => 'lfdi-hb',
                'name' => 'Landesbeauftragte für Datenschutz und Informationsfreiheit der Freien Hansestadt Bremen',
                'short_name' => 'LfDI HB',
                'state' => 'Bremen',
                'street' => 'Arndtstraße 1',
                'postal_code' => '27570',
                'city' => 'Bremerhaven',
                'phone' => '+49 421 361-2010',
                'email' => 'office@datenschutz.bremen.de',
                'website' => 'https://www.datenschutz.bremen.de',
                'breach_notification_url' => 'https://www.datenschutz.bremen.de/datenschutz/datenpanne-melden-23519',
                'notes' => null,
                'sort' => 50,
                'ranges' => [
                    ['27499', '27580', 'Bremerhaven'],
                    ['28001', '28779', 'Bremen-Stadt'],
                ],
            ],
            [
                'key' => 'hmbbfdi',
                'name' => 'Der Hamburgische Beauftragte für Datenschutz und Informationsfreiheit',
                'short_name' => 'HmbBfDI',
                'state' => 'Hamburg',
                'street' => 'Ludwig-Erhard-Straße 22',
                'postal_code' => '20459',
                'city' => 'Hamburg',
                'phone' => '+49 40 428 54-4040',
                'email' => 'mailbox@datenschutz.hamburg.de',
                'website' => 'https://datenschutz-hamburg.de',
                'breach_notification_url' => 'https://datenschutz-hamburg.de/anmeldung-datenpanne',
                'notes' => null,
                'sort' => 60,
                'ranges' => [
                    ['20001', '21149', 'Hamburg (Alster, Hafen)'],
                    ['22001', '22769', 'Hamburg-Wandsbek, Altona'],
                ],
            ],
            [
                'key' => 'hbdi',
                'name' => 'Der Hessische Beauftragte für Datenschutz und Informationsfreiheit',
                'short_name' => 'HBDI',
                'state' => 'Hessen',
                'street' => 'Gustav-Stresemann-Ring 1',
                'postal_code' => '65189',
                'city' => 'Wiesbaden',
                'phone' => '+49 611 1408-0',
                'email' => 'poststelle@datenschutz.hessen.de',
                'website' => 'https://datenschutz.hessen.de',
                'breach_notification_url' => 'https://datenschutz.hessen.de/datenpanne-melden',
                'notes' => null,
                'sort' => 70,
                'ranges' => [
                    ['34001', '36399', 'Kassel, Marburg, Fulda'],
                    ['60001', '65929', 'Frankfurt, Wiesbaden, Darmstadt'],
                ],
            ],
            [
                'key' => 'lfd-mv',
                'name' => 'Der Landesbeauftragte für Datenschutz und Informationsfreiheit Mecklenburg-Vorpommern',
                'short_name' => 'LfDI MV',
                'state' => 'Mecklenburg-Vorpommern',
                'street' => 'Lennéstraße 1',
                'postal_code' => '19053',
                'city' => 'Schwerin',
                'phone' => '+49 385 59494-0',
                'email' => 'info@datenschutz-mv.de',
                'website' => 'https://www.datenschutz-mv.de',
                'breach_notification_url' => 'https://www.datenschutz-mv.de/datenschutz/datenpannen/',
                'notes' => null,
                'sort' => 80,
                'ranges' => [
                    ['17001', '17999', 'Neubrandenburg, Vorpommern'],
                    ['18001', '19412', 'Rostock, Schwerin, Wismar'],
                ],
            ],
            [
                'key' => 'lfd-ni',
                'name' => 'Die Landesbeauftragte für den Datenschutz Niedersachsen',
                'short_name' => 'LfD NI',
                'state' => 'Niedersachsen',
                'street' => 'Prinzenstraße 5',
                'postal_code' => '30159',
                'city' => 'Hannover',
                'phone' => '+49 511 120-4500',
                'email' => 'poststelle@lfd.niedersachsen.de',
                'website' => 'https://lfd.niedersachsen.de',
                'breach_notification_url' => 'https://lfd.niedersachsen.de/startseite/themen/data_breach_notification/data-breach-notification-fur-verantwortliche-204923.html',
                'notes' => null,
                'sort' => 90,
                'ranges' => [
                    ['26001', '27498', 'Oldenburg, Wilhelmshaven'],
                    ['27607', '27999', 'Cuxhaven, Stade'],
                    ['28782', '29999', 'Bremen-Umland, Lüneburg'],
                    ['30001', '31868', 'Hannover, Hildesheim'],
                    ['37001', '37671', 'Göttingen, Northeim'],
                    ['38000', '38479', 'Braunschweig, Wolfsburg'],
                    ['38528', '38729'],
                    ['49001', '49849', 'Osnabrück, Emsland'],
                ],
            ],
            [
                'key' => 'ldi-nrw',
                'name' => 'Landesbeauftragte für Datenschutz und Informationsfreiheit Nordrhein-Westfalen',
                'short_name' => 'LDI NRW',
                'state' => 'Nordrhein-Westfalen',
                'street' => 'Kavalleriestraße 2-4',
                'postal_code' => '40213',
                'city' => 'Düsseldorf',
                'phone' => '+49 211 38424-0',
                'email' => 'poststelle@ldi.nrw.de',
                'website' => 'https://www.ldi.nrw.de',
                'breach_notification_url' => 'https://www.ldi.nrw.de/themen/datenschutz/meldung-von-datenschutzverletzungen',
                'notes' => null,
                'sort' => 100,
                'ranges' => [
                    ['32001', '33829', 'Bielefeld, Paderborn'],
                    ['40001', '48739', 'Düsseldorf, Essen, Münster'],
                    ['50001', '51149', 'Köln'],
                    ['51201', '53359', 'Bergisches Land, Bonn-Region'],
                    ['57001', '57489', 'Siegen'],
                    ['58001', '59969', 'Hagen, Dortmund'],
                ],
            ],
            [
                'key' => 'lfdi-rp',
                'name' => 'Der Landesbeauftragte für den Datenschutz und die Informationsfreiheit Rheinland-Pfalz',
                'short_name' => 'LfDI RP',
                'state' => 'Rheinland-Pfalz',
                'street' => 'Hintere Bleiche 34',
                'postal_code' => '55116',
                'city' => 'Mainz',
                'phone' => '+49 6131 208-2449',
                'email' => 'poststelle@datenschutz.rlp.de',
                'website' => 'https://www.datenschutz.rlp.de',
                'breach_notification_url' => 'https://www.datenschutz.rlp.de/datenpanne-melden',
                'notes' => null,
                'sort' => 110,
                'ranges' => [
                    ['54001', '54669', 'Trier, Eifel'],
                    ['55001', '55776', 'Mainz, Hunsrück'],
                    ['56001', '56869', 'Koblenz, Westerwald'],
                    ['66839', '67829', 'Pfalz, Kaiserslautern'],
                    ['76711', '76891', 'Südpfalz'],
                ],
            ],
            [
                'key' => 'uld-sl',
                'name' => 'Unabhängiges Datenschutzzentrum Saarland',
                'short_name' => 'UDS',
                'state' => 'Saarland',
                'street' => 'Fritz-Dobisch-Straße 12',
                'postal_code' => '66111',
                'city' => 'Saarbrücken',
                'phone' => '+49 681 94781-0',
                'email' => 'poststelle@datenschutz.saarland.de',
                'website' => 'https://www.datenschutz.saarland.de',
                'breach_notification_url' => 'https://www.datenschutz.saarland.de/datenpannen-meldung',
                'notes' => null,
                'sort' => 120,
                'ranges' => [
                    ['66001', '66839', 'Saarbrücken, Saarlouis'],
                ],
            ],
            [
                'key' => 'sdb',
                'name' => 'Sächsische Datenschutz- und Transparenzbeauftragte',
                'short_name' => 'SDTB',
                'state' => 'Sachsen',
                'street' => 'Devrientstraße 5',
                'postal_code' => '01067',
                'city' => 'Dresden',
                'phone' => '+49 351 85471-101',
                'email' => 'saechsdsb@slt.sachsen.de',
                'website' => 'https://www.saechsdsb.de',
                'breach_notification_url' => 'https://www.saechsdsb.de/datenpannen',
                'notes' => null,
                'sort' => 130,
                'ranges' => [
                    ['01001', '02999', 'Dresden, Bautzen, Görlitz'],
                    ['04001', '04579', 'Leipzig'],
                    ['08001', '09669', 'Chemnitz, Zwickau, Vogtland'],
                ],
            ],
            [
                'key' => 'lfd-st',
                'name' => 'Landesbeauftragter für den Datenschutz Sachsen-Anhalt',
                'short_name' => 'LfD ST',
                'state' => 'Sachsen-Anhalt',
                'street' => 'Leiterstraße 9',
                'postal_code' => '39104',
                'city' => 'Magdeburg',
                'phone' => '+49 391 81803-0',
                'email' => 'poststelle@lfd.sachsen-anhalt.de',
                'website' => 'https://datenschutz.sachsen-anhalt.de',
                'breach_notification_url' => 'https://datenschutz.sachsen-anhalt.de/datenschutz/datenschutzverletzungen',
                'notes' => null,
                'sort' => 140,
                'ranges' => [
                    ['06001', '06928', 'Halle, Dessau, Wittenberg'],
                    ['38480', '38489', 'Klötze'],
                    ['39001', '39649', 'Magdeburg, Stendal'],
                ],
            ],
            [
                'key' => 'uld-sh',
                'name' => 'Unabhängiges Landeszentrum für Datenschutz Schleswig-Holstein',
                'short_name' => 'ULD SH',
                'state' => 'Schleswig-Holstein',
                'street' => 'Holstenstraße 98',
                'postal_code' => '24103',
                'city' => 'Kiel',
                'phone' => '+49 431 988-1200',
                'email' => 'mail@datenschutzzentrum.de',
                'website' => 'https://www.datenschutzzentrum.de',
                'breach_notification_url' => 'https://www.datenschutzzentrum.de/datenpanne/',
                'notes' => null,
                'sort' => 150,
                'ranges' => [
                    ['22850', '22999', 'Pinneberg, Norderstedt'],
                    ['23001', '25999', 'Lübeck, Kiel, Flensburg'],
                ],
            ],
            [
                'key' => 'tlfdi',
                'name' => 'Thüringer Landesbeauftragter für den Datenschutz und die Informationsfreiheit',
                'short_name' => 'TLfDI',
                'state' => 'Thüringen',
                'street' => 'Häßlerstraße 8',
                'postal_code' => '99096',
                'city' => 'Erfurt',
                'phone' => '+49 361 57-3112900',
                'email' => 'poststelle@datenschutz.thueringen.de',
                'website' => 'https://www.tlfdi.de',
                'breach_notification_url' => 'https://www.tlfdi.de/tlfdi/datenschutz/datenpanne/',
                'notes' => null,
                'sort' => 160,
                'ranges' => [
                    ['07001', '07999', 'Gera, Jena, Saalfeld'],
                    ['98001', '99998', 'Erfurt, Weimar, Suhl, Eisenach'],
                ],
            ],
            [
                'key' => 'bfdi',
                'name' => 'Der Bundesbeauftragte für den Datenschutz und die Informationsfreiheit',
                'short_name' => 'BfDI',
                'state' => 'Bund',
                'street' => 'Graurheindorfer Straße 153',
                'postal_code' => '53117',
                'city' => 'Bonn',
                'phone' => '+49 228 997799-0',
                'email' => 'poststelle@bfdi.bund.de',
                'website' => 'https://www.bfdi.bund.de',
                'breach_notification_url' => 'https://www.bfdi.bund.de/DE/Buerger/IhreRechte/Beschwerde/beschwerde-node.html',
                'notes' => 'Nur für Bundesbehörden, Telekommunikations- und Postdiensteanbieter sowie bundesweit tätige Sozialversicherungsträger zuständig — keine PLZ-basierte Zuordnung für die Privatwirtschaft.',
                'sort' => 999,
                'ranges' => [],
            ],
        ];
    }
}
