<?php

namespace Database\Seeders\IndustryTemplates;

use App\Enums\Industry;

class KrankenhausTemplate implements Contract
{
    public function name(): string
    {
        return 'Krankenhaus Grund-/Regelversorgung (unter KRITIS-Schwelle)';
    }

    public function industry(): Industry
    {
        return Industry::OeffentlicheEinrichtung;
    }

    public function description(): string
    {
        return 'Kommunales Krankenhaus der Grund- und Regelversorgung (kommunale Klinik gGmbH, ca. 450 Mitarbeiter, < 30.000 vollstationäre Fälle/Jahr) UNTERHALB der KRITIS-Schwelle nach BSI-KritisV. Trotz fehlender KRITIS-Pflicht gilt § 75c SGB V verbindlich: IT-Sicherheit nach Stand der Technik ist PFLICHT, die Orientierung am branchenspezifischen Sicherheitsstandard B3S Krankenhaus (DKG) ist unterhalb der Schwelle freiwillig. Schwerpunkte: Krankenhausinformationssystem (KIS), PACS/Radiologie, Labor (LIS), Intensiv-PDMS, Medikations- und Apothekensoftware, Notaufnahme-/Aufnahmesystem, Schwesternruf, Netzersatzanlage/USV für OP und Intensiv, Medizingeräte-Netz, Blutbank, Sterilgutversorgung (AEMP). Weitere Rechtsbezüge: NIS2 (Gesundheitssektor, Einrichtung important), MDR/MPBetreibV (STK/MTK), IfSG § 23 (Hygiene, RKI), KAEP-Pflicht nach Landeskrankenhausgesetz und Art. 9 DSGVO (Patientendaten besonderer Kategorie). Enthält: 1 Klinik + MVZ, 13 Mitarbeiter mit Pflichtrollen, 16 Systeme inkl. KIS/PACS/LIS/Notstrom, 6 Dienstleister, 4 Versicherungen, Kommunikationsvorlagen, Testplan und system_tasks.';
    }

    public function sort(): int
    {
        return 93;
    }

    public function payload(): array
    {
        // Stable IDs, damit FK-Verweise innerhalb des Payloads konsistent
        // bleiben. Beim Apply werden sie via regenerateIds neu gemappt.
        $loc = [
            'klinik' => Helpers::uuid(),
            'mvz' => Helpers::uuid(),
        ];

        $emp = [
            'gf' => Helpers::uuid(),
            'aerztl_dir' => Helpers::uuid(),
            'pflegedir' => Helpers::uuid(),
            'it_leitung' => Helpers::uuid(),
            'isb' => Helpers::uuid(),
            'it_stv' => Helpers::uuid(),
            'hygiene' => Helpers::uuid(),
            'medizintechnik' => Helpers::uuid(),
            'presse' => Helpers::uuid(),
            'dsb' => Helpers::uuid(),
            'kel' => Helpers::uuid(),
            'notaufnahme' => Helpers::uuid(),
            'apotheke' => Helpers::uuid(),
        ];

        $prov = [
            'kis' => Helpers::uuid(),
            'msp' => Helpers::uuid(),
            'medtech' => Helpers::uuid(),
            'lfdi' => Helpers::uuid(),
            'energie' => Helpers::uuid(),
            'internet' => Helpers::uuid(),
        ];

        $sys = [
            'kis' => Helpers::uuid(),
            'pacs' => Helpers::uuid(),
            'lis' => Helpers::uuid(),
            'pdms' => Helpers::uuid(),
            'apo' => Helpers::uuid(),
            'aufnahme' => Helpers::uuid(),
            'schwesternruf' => Helpers::uuid(),
            'notstrom' => Helpers::uuid(),
            'mednetz' => Helpers::uuid(),
            'blutbank' => Helpers::uuid(),
            'aemp' => Helpers::uuid(),
            'rz' => Helpers::uuid(),
            'internet' => Helpers::uuid(),
            'm365' => Helpers::uuid(),
            'kueche' => Helpers::uuid(),
            'glt' => Helpers::uuid(),
        ];

        $ts = Helpers::now();

        return Helpers::payload([
            'company' => [[
                'name' => 'Kreisklinik Musterstadt gGmbH',
                'industry' => 'oeffentliche_einrichtung',
                'employee_count' => 450,
                'review_cycle_months' => 12,
                'legal_form' => 'gmbh',
                'kritis_relevant' => 'no',
                'nis2_classification' => 'important',
                'cyber_insurance_deductible' => '25.000 €',
                'budget_it_lead' => 5000,
                'budget_emergency_officer' => 15000,
                'budget_management' => 150000,
                'data_protection_authority_name' => 'LfDI Baden-Württemberg',
                'data_protection_authority_phone' => '0711 615541-0',
                'data_protection_authority_website' => 'https://www.baden-wuerttemberg.datenschutz.de',
            ]],

            'locations' => [
                [
                    'id' => $loc['klinik'], 'name' => 'Kreisklinik Musterstadt (Hauptgebäude)', 'street' => 'Klinikstraße 1',
                    'postal_code' => '74072', 'city' => 'Musterstadt', 'country' => 'DE',
                    'is_headquarters' => 1, 'phone' => '07131 600-0',
                    'notes' => 'Akutkrankenhaus Grund-/Regelversorgung, ca. 250 Betten, < 30.000 vollstationäre Fälle/Jahr (unter KRITIS-Schwelle). Notaufnahme 24/7, OP, Intensivstation, Radiologie, Labor, Apotheke. Rechenzentrum im Untergeschoss, redundante Netzersatzanlage.',
                    'sort' => 0, 'created_at' => $ts, 'updated_at' => $ts,
                ],
                [
                    'id' => $loc['mvz'], 'name' => 'MVZ am Klinikum (Außenstelle)', 'street' => 'Bahnhofstraße 22',
                    'postal_code' => '74072', 'city' => 'Musterstadt', 'country' => 'DE',
                    'is_headquarters' => 0, 'phone' => '07131 600-900',
                    'notes' => 'Medizinisches Versorgungszentrum, ambulante Praxen (Chirurgie, Innere). KIS-Anbindung per VPN an das Hauptgebäude.',
                    'sort' => 1, 'created_at' => $ts, 'updated_at' => $ts,
                ],
            ],

            'employees' => [
                ['id' => $emp['gf'], 'first_name' => 'Dr.', 'last_name' => 'Berger', 'position' => 'Geschäftsführung', 'department' => 'Geschäftsführung', 'work_phone' => '07131 600-100', 'mobile_phone' => '0172 6660001', 'private_phone' => null, 'email' => 'gf@kreisklinik-musterstadt.de', 'emergency_contact' => null, 'manager_id' => null, 'is_key_personnel' => 1, 'crisis_role' => 'management', 'is_crisis_deputy' => 0, 'notes' => 'Gesamtverantwortung Klinik gGmbH, Vorsitz Krankenhauseinsatzleitung (KEL). Letztentscheid bei Notaufnahme-Abmeldung und externer Kommunikation.', 'location_id' => $loc['klinik'], 'created_at' => $ts, 'updated_at' => $ts],
                ['id' => $emp['aerztl_dir'], 'first_name' => 'Prof. Dr.', 'last_name' => 'Hartmann', 'position' => 'Ärztlicher Direktor', 'department' => 'Ärztliche Direktion', 'work_phone' => '07131 600-110', 'mobile_phone' => '0172 6660002', 'private_phone' => null, 'email' => 'aerztl.direktor@kreisklinik-musterstadt.de', 'emergency_contact' => null, 'manager_id' => $emp['gf'], 'is_key_personnel' => 1, 'crisis_role' => 'management', 'is_crisis_deputy' => 1, 'notes' => 'Medizinische Gesamtverantwortung, Mitglied KEL. Entscheidet über Verlegungen, OP-Stopp und Priorisierung bei IT-Ausfall.', 'location_id' => $loc['klinik'], 'created_at' => $ts, 'updated_at' => $ts],
                ['id' => $emp['pflegedir'], 'first_name' => 'Andrea', 'last_name' => 'Sommer', 'position' => 'Pflegedirektion', 'department' => 'Pflegedirektion', 'work_phone' => '07131 600-120', 'mobile_phone' => '0172 6660003', 'private_phone' => null, 'email' => 'pflegedirektion@kreisklinik-musterstadt.de', 'emergency_contact' => null, 'manager_id' => $emp['gf'], 'is_key_personnel' => 1, 'crisis_role' => 'emergency_officer', 'is_crisis_deputy' => 0, 'notes' => 'Notfallbeauftragte (Pflege). Steuert Personaleinsatz bei KIS-Ausfall, koordiniert Umstellung auf Papier-Doku auf Station.', 'location_id' => $loc['klinik'], 'created_at' => $ts, 'updated_at' => $ts],
                ['id' => $emp['it_leitung'], 'first_name' => 'Markus', 'last_name' => 'Reuter', 'position' => 'IT-Leitung', 'department' => 'IT', 'work_phone' => '07131 600-130', 'mobile_phone' => '0172 6660004', 'private_phone' => null, 'email' => 'it-leitung@kreisklinik-musterstadt.de', 'emergency_contact' => null, 'manager_id' => $emp['gf'], 'is_key_personnel' => 1, 'crisis_role' => 'it_lead', 'is_crisis_deputy' => 0, 'notes' => 'Leitung Klinik-IT, Verantwortung für KIS/PACS/RZ. Erste Eskalationsstufe bei IT-Sicherheitsvorfällen.', 'location_id' => $loc['klinik'], 'created_at' => $ts, 'updated_at' => $ts],
                ['id' => $emp['isb'], 'first_name' => 'Julia', 'last_name' => 'Vogt', 'position' => 'IT-Sicherheitsbeauftragte (ISB) nach § 75c SGB V', 'department' => 'IT', 'work_phone' => '07131 600-131', 'mobile_phone' => '0172 6660005', 'private_phone' => null, 'email' => 'isb@kreisklinik-musterstadt.de', 'emergency_contact' => null, 'manager_id' => $emp['it_leitung'], 'is_key_personnel' => 1, 'crisis_role' => 'it_lead', 'is_crisis_deputy' => 1, 'notes' => 'IT-Sicherheitsbeauftragte nach § 75c SGB V (Stand der Technik PFLICHT). Orientierung an B3S Krankenhaus (DKG, freiwillig unter Schwelle), Schwachstellenmanagement, Meldewesen.', 'location_id' => $loc['klinik'], 'created_at' => $ts, 'updated_at' => $ts],
                ['id' => $emp['it_stv'], 'first_name' => 'Tobias', 'last_name' => 'Krämer', 'position' => 'Stv. IT-Leitung / Systemadministration', 'department' => 'IT', 'work_phone' => '07131 600-132', 'mobile_phone' => '0172 6660006', 'private_phone' => null, 'email' => 'it-admin@kreisklinik-musterstadt.de', 'emergency_contact' => null, 'manager_id' => $emp['it_leitung'], 'is_key_personnel' => 1, 'crisis_role' => 'it_lead', 'is_crisis_deputy' => 1, 'notes' => 'Vertretung IT-Leitung, Backup-/Restore-Verantwortung, Rufbereitschaft RZ.', 'location_id' => $loc['klinik'], 'created_at' => $ts, 'updated_at' => $ts],
                ['id' => $emp['hygiene'], 'first_name' => 'Dr.', 'last_name' => 'Lindner', 'position' => 'Krankenhaushygieniker', 'department' => 'Hygiene', 'work_phone' => '07131 600-140', 'mobile_phone' => '0172 6660007', 'private_phone' => null, 'email' => 'hygiene@kreisklinik-musterstadt.de', 'emergency_contact' => null, 'manager_id' => $emp['aerztl_dir'], 'is_key_personnel' => 1, 'crisis_role' => null, 'is_crisis_deputy' => 0, 'notes' => 'Krankenhaushygiene nach IfSG § 23 (RKI-Empfehlungen). Relevant bei Ausbruchsgeschehen parallel zum IT-Vorfall.', 'location_id' => $loc['klinik'], 'created_at' => $ts, 'updated_at' => $ts],
                ['id' => $emp['medizintechnik'], 'first_name' => 'Frank', 'last_name' => 'Weiß', 'position' => 'Leitung Medizintechnik / MPG-Beauftragter', 'department' => 'Medizintechnik', 'work_phone' => '07131 600-150', 'mobile_phone' => '0172 6660008', 'private_phone' => null, 'email' => 'medizintechnik@kreisklinik-musterstadt.de', 'emergency_contact' => null, 'manager_id' => $emp['it_leitung'], 'is_key_personnel' => 1, 'crisis_role' => null, 'is_crisis_deputy' => 0, 'notes' => 'Verantwortlich Medizinprodukte nach MPBetreibV (STK/MTK), Medizingeräte-Netz, Schnittstelle zur IT-Sicherheit (MDR/Cybersecurity).', 'location_id' => $loc['klinik'], 'created_at' => $ts, 'updated_at' => $ts],
                ['id' => $emp['presse'], 'first_name' => 'Sabine', 'last_name' => 'Kuhn', 'position' => 'Leitung Unternehmenskommunikation / Pressestelle', 'department' => 'Kommunikation', 'work_phone' => '07131 600-160', 'mobile_phone' => '0172 6660009', 'private_phone' => null, 'email' => 'presse@kreisklinik-musterstadt.de', 'emergency_contact' => null, 'manager_id' => $emp['gf'], 'is_key_personnel' => 1, 'crisis_role' => 'communications_lead', 'is_crisis_deputy' => 0, 'notes' => 'Presse- und Krisenkommunikation, Abstimmung mit Gesundheitsamt und Träger. Einzige freigabeberechtigte Stelle für externe Statements.', 'location_id' => $loc['klinik'], 'created_at' => $ts, 'updated_at' => $ts],
                ['id' => $emp['dsb'], 'first_name' => 'Dr.', 'last_name' => 'Engelhardt', 'position' => 'Datenschutzbeauftragter (extern)', 'department' => 'Compliance', 'work_phone' => null, 'mobile_phone' => '0172 6660010', 'private_phone' => null, 'email' => 'dsb@datenschutz-klinik.example', 'emergency_contact' => null, 'manager_id' => null, 'is_key_personnel' => 1, 'crisis_role' => 'dpo', 'is_crisis_deputy' => 0, 'notes' => 'Externer DSB. Bei Datenpanne sofort Kontakt — Patientendaten = besondere Kategorien Art. 9 DSGVO, Art. 33-Meldung binnen 72 h.', 'location_id' => null, 'created_at' => $ts, 'updated_at' => $ts],
                ['id' => $emp['kel'], 'first_name' => 'Dr.', 'last_name' => 'Wagner', 'position' => 'Krankenhauseinsatzleitung (KEL) / Koordinator KAEP', 'department' => 'Ärztliche Direktion', 'work_phone' => '07131 600-170', 'mobile_phone' => '0172 6660011', 'private_phone' => null, 'email' => 'kel@kreisklinik-musterstadt.de', 'emergency_contact' => null, 'manager_id' => $emp['aerztl_dir'], 'is_key_personnel' => 1, 'crisis_role' => 'emergency_officer', 'is_crisis_deputy' => 1, 'notes' => 'Operative Leitung Krankenhausalarm- und Einsatzplan (KAEP, Pflicht nach Landeskrankenhausgesetz/Katastrophenschutz). Aktivierung Krisenstab, MANV-Koordination.', 'location_id' => $loc['klinik'], 'created_at' => $ts, 'updated_at' => $ts],
                ['id' => $emp['notaufnahme'], 'first_name' => 'Dr.', 'last_name' => 'Fischer', 'position' => 'Leitung Zentrale Notaufnahme (ZNA)', 'department' => 'Notaufnahme', 'work_phone' => '07131 600-180', 'mobile_phone' => '0172 6660012', 'private_phone' => null, 'email' => 'zna-leitung@kreisklinik-musterstadt.de', 'emergency_contact' => null, 'manager_id' => $emp['aerztl_dir'], 'is_key_personnel' => 1, 'crisis_role' => null, 'is_crisis_deputy' => 0, 'notes' => 'Leitung ZNA. Entscheidet über Notaufnahme-Abmeldung in IVENA/Leitstelle bei System- oder Kapazitätsausfall.', 'location_id' => $loc['klinik'], 'created_at' => $ts, 'updated_at' => $ts],
                ['id' => $emp['apotheke'], 'first_name' => 'Dr.', 'last_name' => 'Albrecht', 'position' => 'Leitung Krankenhausapotheke', 'department' => 'Apotheke', 'work_phone' => '07131 600-190', 'mobile_phone' => '0172 6660013', 'private_phone' => null, 'email' => 'apotheke@kreisklinik-musterstadt.de', 'emergency_contact' => null, 'manager_id' => $emp['aerztl_dir'], 'is_key_personnel' => 1, 'crisis_role' => null, 'is_crisis_deputy' => 0, 'notes' => 'Arzneimittelversorgung, Betäubungsmittel-Doku, Medikationssoftware. Notfallvorrat kritischer Medikamente.', 'location_id' => $loc['klinik'], 'created_at' => $ts, 'updated_at' => $ts],
            ],

            'service_providers' => [
                ['id' => $prov['kis'], 'name' => 'Dedalus HealthCare GmbH (KIS ORBIS)', 'type' => 'other', 'contact_name' => 'Klinik-Support / Account-Manager', 'hotline' => '0228 2668-000', 'email' => 'support@dedalus.example', 'contract_number' => 'KIS-KMS-2026-001', 'sla' => '24/7 für P1 (KIS-Totalausfall), Reaktionszeit 1 h', 'notes' => 'KIS-Hersteller (ORBIS). KRITISCH: bei Ausfall steht die gesamte Patientendokumentation, Leistungserfassung und Abrechnung. P1-Hotline 24/7 vertraglich zugesichert.', 'direct_order_limit' => 10000, 'created_at' => $ts, 'updated_at' => $ts],
                ['id' => $prov['msp'], 'name' => 'MediNet IT-Services GmbH (Medizin-IT MSP)', 'type' => 'it_msp', 'contact_name' => 'NOC / Hr. Brunner', 'hotline' => '0711 4455-900', 'email' => 'noc@medinet-it.example', 'contract_number' => 'MSP-KMS-2026', 'sla' => '24/7 Rufbereitschaft, P1 Reaktion 30 Min', 'notes' => 'Managed Service Provider für Server, Netzwerk, Firewall, Backup. Spezialisiert auf Klinik-IT (B3S-Orientierung, DSGVO Art. 9).', 'direct_order_limit' => 8000, 'created_at' => $ts, 'updated_at' => $ts],
                ['id' => $prov['medtech'], 'name' => 'MedTechCare Wartungsservice GmbH', 'type' => 'other', 'contact_name' => 'Disposition Service', 'hotline' => '0800 6383224', 'email' => 'service@medtechcare.example', 'contract_number' => 'STK-KMS-2025-044', 'sla' => 'Mo-Fr 7-19, Notdienst 24/7 für lebenserhaltende Geräte', 'notes' => 'Wartung Medizintechnik, sicherheits- und messtechnische Kontrollen (STK/MTK nach MPBetreibV). Beatmung, Monitoring, OP-Technik.', 'direct_order_limit' => 5000, 'created_at' => $ts, 'updated_at' => $ts],
                ['id' => $prov['lfdi'], 'name' => 'LfDI Baden-Württemberg', 'type' => 'data_protection_authority', 'contact_name' => 'Meldestelle Datenpannen', 'hotline' => '0711 615541-0', 'email' => 'poststelle@lfdi.bwl.de', 'contract_number' => null, 'sla' => 'Mo-Fr 8-16', 'notes' => 'Aufsichtsbehörde für Meldungen nach Art. 33 DSGVO. Patientendaten = besondere Kategorien Art. 9, Meldung binnen 72 h.', 'direct_order_limit' => null, 'created_at' => $ts, 'updated_at' => $ts],
                ['id' => $prov['energie'], 'name' => 'Stadtwerke Musterstadt (Energieversorger)', 'type' => 'utility', 'contact_name' => 'Netzleitstelle / Störungsdienst', 'hotline' => '07131 700-112', 'email' => 'stoerung@stadtwerke-musterstadt.example', 'contract_number' => 'SLP-KMS-2024', 'sla' => 'Störungsdienst 24/7', 'notes' => 'Strom- und Wärmeversorgung. Bei Netzausfall übernimmt die klinikeigene Netzersatzanlage (NEA) OP, Intensiv und Notaufnahme.', 'direct_order_limit' => null, 'created_at' => $ts, 'updated_at' => $ts],
                ['id' => $prov['internet'], 'name' => 'Deutsche Telekom Business (Standortanbindung)', 'type' => 'internet_provider', 'contact_name' => 'Geschäftskunden-Service', 'hotline' => '0800 3301000', 'email' => 'business-support@telekom.example', 'contract_number' => 'GK-KMS-2025-777', 'sla' => 'Premium-SLA, Entstörung 4 h', 'notes' => 'Redundante Standortanbindung Hauptgebäude + VPN-Anbindung MVZ. Backup-Leitung über zweiten Carrier.', 'direct_order_limit' => null, 'created_at' => $ts, 'updated_at' => $ts],
            ],

            'systems' => [
                ['id' => $sys['kis'], 'name' => 'Krankenhausinformationssystem (KIS, ORBIS)', 'description' => 'Zentrales KIS für Patientenstammdaten, ärztliche und pflegerische Dokumentation, Anforderungen, Befunde, Leistungserfassung und DRG-Abrechnung. Herzstück des klinischen Betriebs.', 'category' => 'geschaeftsbetrieb', 'rto_minutes' => 60, 'rpo_minutes' => 15, 'downtime_cost_per_hour' => 8000, 'fallback_process' => 'Sofort-Umstellung auf KIS-Notfallbetrieb: Papier-Aufnahmebogen, Papier-Kurve und Anforderungsscheine aus dem Notfall-Schrank jeder Station. KIS-Hersteller-P1-Hotline (24/7). Read-Only-Notfall-Client mit letztem Datenstand falls verfügbar. Lückenlose Nacherfassung nach Wiederanlauf (haftungs- und abrechnungsrelevant).', 'runbook_reference' => 'Runbook „KIS-Ausfall / Notfallbetrieb" v2.1', 'system_priority_id' => null, 'emergency_level_id' => null, 'created_at' => $ts, 'updated_at' => $ts],
                ['id' => $sys['pacs'], 'name' => 'PACS / Radiologie (RIS)', 'description' => 'Bildarchivierungs- und Kommunikationssystem für CT, Röntgen, Ultraschall inkl. Radiologie-Informationssystem. Befundung und Bildverteilung in OP, ZNA, Stationen.', 'category' => 'geschaeftsbetrieb', 'rto_minutes' => 120, 'rpo_minutes' => 30, 'downtime_cost_per_hour' => 3000, 'fallback_process' => 'Modalitäten lokal weiterbetreiben (Bilder zwischenspeichern am Gerät). Befundung am Modalitäts-Arbeitsplatz, Bilder per CD/USB an OP/Station. Manuelle Befundzettel. Nachträglicher Import ins PACS nach Wiederanlauf.', 'runbook_reference' => 'Runbook „PACS-Ausfall" v1.3', 'system_priority_id' => null, 'emergency_level_id' => null, 'created_at' => $ts, 'updated_at' => $ts],
                ['id' => $sys['lis'], 'name' => 'Laborinformationssystem (LIS)', 'description' => 'Labor-IT für Analytik, Befundübermittlung und Anbindung der Laborautomaten. Klinische Chemie, Hämatologie, Mikrobiologie, Notfalllabor.', 'category' => 'geschaeftsbetrieb', 'rto_minutes' => 120, 'rpo_minutes' => 30, 'downtime_cost_per_hour' => 2500, 'fallback_process' => 'Notfalllabor manuell betreiben: Anforderung per Papierschein, Geräte im Standalone-Modus, Befund telefonisch + handschriftlich an Station/ZNA. Point-of-Care-Geräte (BGA, Troponin) priorisieren.', 'runbook_reference' => 'Runbook „Labor-Ausfall" v1.1', 'system_priority_id' => null, 'emergency_level_id' => null, 'created_at' => $ts, 'updated_at' => $ts],
                ['id' => $sys['pdms'], 'name' => 'Intensiv-PDMS (Patientendaten-Managementsystem)', 'description' => 'Patientendaten-Managementsystem auf der Intensivstation: kontinuierliche Vitaldaten, Beatmung, Medikation, Bilanzierung. Direkt patientengefährdend bei Ausfall.', 'category' => 'basisbetrieb', 'rto_minutes' => 30, 'rpo_minutes' => 5, 'downtime_cost_per_hour' => 6000, 'fallback_process' => 'Sofort Umstellung auf Papier-Intensivkurve (Notfall-Vordruck am Bettplatz). Monitore und Beatmungsgeräte laufen autonom weiter — Werte manuell ablesen und dokumentieren. Engmaschige pflegerische Überwachung. Medizintechnik informieren.', 'runbook_reference' => 'Runbook „PDMS-Ausfall Intensiv" v2.0', 'system_priority_id' => null, 'emergency_level_id' => null, 'created_at' => $ts, 'updated_at' => $ts],
                ['id' => $sys['apo'], 'name' => 'Apotheken- / Medikationssoftware', 'description' => 'Krankenhausapotheken-System für Arzneimittelversorgung, Stationsbestellung, Betäubungsmittel-Doku und Unit-Dose-Versorgung.', 'category' => 'geschaeftsbetrieb', 'rto_minutes' => 240, 'rpo_minutes' => 60, 'downtime_cost_per_hour' => 1200, 'fallback_process' => 'Stationsbedarf per Papier-Anforderung an Apotheke. Notfalldepot kritischer Medikamente auf Station nutzen. BTM-Buch in Papierform weiterführen. Manuelle Ausgabe-Dokumentation.', 'runbook_reference' => 'Runbook „Apotheken-IT-Ausfall" v1.0', 'system_priority_id' => null, 'emergency_level_id' => null, 'created_at' => $ts, 'updated_at' => $ts],
                ['id' => $sys['aufnahme'], 'name' => 'Patientenaufnahme / ZNA-System', 'description' => 'Aufnahme- und Notaufnahmesystem (Ersteinschätzung/Triage nach Manchester, Behandlungsdoku ZNA, Anbindung Leitstelle/IVENA).', 'category' => 'geschaeftsbetrieb', 'rto_minutes' => 60, 'rpo_minutes' => 15, 'downtime_cost_per_hour' => 3000, 'fallback_process' => 'Manuelle Triage per Papier-Ersteinschätzungsbogen. Aufnahme handschriftlich, Vergabe von Notfall-Fallnummern aus reserviertem Nummernkreis. Bei Kapazitäts-/Systemausfall: Abmeldung in IVENA/bei Leitstelle durch ZNA-Leitung.', 'runbook_reference' => 'Runbook „ZNA-/Aufnahme-Ausfall" v1.2', 'system_priority_id' => null, 'emergency_level_id' => null, 'created_at' => $ts, 'updated_at' => $ts],
                ['id' => $sys['schwesternruf'], 'name' => 'Schwesternruf / Patientenrufanlage', 'description' => 'Patientenrufanlage auf allen Stationen inkl. Notruf-Taster, Personalruf und Telefonie-Integration. Sicherheitskritisch für Patientenüberwachung.', 'category' => 'basisbetrieb', 'rto_minutes' => 30, 'rpo_minutes' => null, 'downtime_cost_per_hour' => 2000, 'fallback_process' => 'Erhöhte pflegerische Präsenz und engmaschige Rundgänge auf betroffenen Stationen. Mobiltelefone/DECT als Ersatz-Kommunikation. Kritische Patienten in Sichtweite des Stützpunkts verlegen. Haustechnik + Medizintechnik sofort alarmieren.', 'runbook_reference' => 'Runbook „Schwesternruf-Ausfall" v1.0', 'system_priority_id' => null, 'emergency_level_id' => null, 'created_at' => $ts, 'updated_at' => $ts],
                ['id' => $sys['notstrom'], 'name' => 'Netzersatzanlage (NEA) + USV', 'description' => 'Klinikeigene Netzersatzanlage (Diesel) und zentrale USV für die Sicherstellung der Stromversorgung von OP, Intensivstation, Notaufnahme, RZ und lebenserhaltenden Geräten bei Netzausfall.', 'category' => 'basisbetrieb', 'rto_minutes' => 1, 'rpo_minutes' => null, 'downtime_cost_per_hour' => 20000, 'fallback_process' => 'USV überbrückt unterbrechungsfrei bis NEA anläuft (< 15 Sek). Bei NEA-Versagen: Lastabwurf nach Prioritätenplan (OP/Intensiv/ZNA zuerst), Verlegung/OP-Stopp einleiten, Energieversorger und Servicepartner NEA sofort. Treibstoffvorrat für 24-72 h vorhalten.', 'runbook_reference' => 'Runbook „Stromausfall / NEA" v2.2', 'system_priority_id' => null, 'emergency_level_id' => null, 'created_at' => $ts, 'updated_at' => $ts],
                ['id' => $sys['mednetz'], 'name' => 'Medizingeräte-Netz (Medical Device Network)', 'description' => 'Separiertes Netzsegment für vernetzte Medizinprodukte (Monitore, Infusionspumpen, Beatmung, OP-Technik). MDR-/MPBetreibV-relevant, von der Office-IT getrennt.', 'category' => 'basisbetrieb', 'rto_minutes' => 60, 'rpo_minutes' => null, 'downtime_cost_per_hour' => 4000, 'fallback_process' => 'Geräte im Standalone-Betrieb weiterführen (lokale Anzeige/Alarmierung bleibt funktionsfähig). Manuelle Vitalwert-Dokumentation. Medizintechnik isoliert das betroffene Segment, MSP prüft auf Kompromittierung. Keine Geräte-Updates während Vorfall.', 'runbook_reference' => 'Runbook „Medizingeräte-Netz-Störung" v1.1', 'system_priority_id' => null, 'emergency_level_id' => null, 'created_at' => $ts, 'updated_at' => $ts],
                ['id' => $sys['blutbank'], 'name' => 'Blutbank / Transfusionssystem', 'description' => 'Blutdepot-Verwaltung, Kreuzprobe-Doku, Konservenbestand und Rückverfolgbarkeit (Transfusionsgesetz). Anbindung an Labor und Kühlüberwachung.', 'category' => 'basisbetrieb', 'rto_minutes' => 120, 'rpo_minutes' => 30, 'downtime_cost_per_hour' => 2500, 'fallback_process' => 'Notfall-0-negativ-Konserven nach SOP freigeben. Kreuzprobe und Konserven-Ausgabe manuell mit Papier-Begleitschein dokumentieren (Rückverfolgbarkeit zwingend!). Kühlschrank-Temperaturen manuell protokollieren. Transfusionsverantwortlichen informieren.', 'runbook_reference' => 'Runbook „Blutbank-Ausfall" v1.0', 'system_priority_id' => null, 'emergency_level_id' => null, 'created_at' => $ts, 'updated_at' => $ts],
                ['id' => $sys['aemp'], 'name' => 'Sterilgutversorgung (AEMP/ZSVA)', 'description' => 'Aufbereitungseinheit für Medizinprodukte (Zentrale Sterilgutversorgung): Dokumentation der Aufbereitungs-Chargen, Freigabe und Rückverfolgbarkeit von Sterilgut für OP.', 'category' => 'geschaeftsbetrieb', 'rto_minutes' => 240, 'rpo_minutes' => 60, 'downtime_cost_per_hour' => 1500, 'fallback_process' => 'Chargen-Dokumentation auf Papier-Freigabeprotokoll. Sterilgut-Bestand im OP nutzen, elektive Eingriffe ggf. verschieben. Manuelle Freigabe durch Sachkundige nach Prozess-Validierung. Nacherfassung nach Wiederanlauf.', 'runbook_reference' => 'Runbook „AEMP-IT-Ausfall" v1.0', 'system_priority_id' => null, 'emergency_level_id' => null, 'created_at' => $ts, 'updated_at' => $ts],
                ['id' => $sys['rz'], 'name' => 'Rechenzentrum / Serverinfrastruktur', 'description' => 'Klinik-Rechenzentrum (virtualisierte Server, Storage, Backup, Active Directory, Datenbanken). Trägt KIS, PACS, LIS und nahezu alle klinischen Anwendungen.', 'category' => 'basisbetrieb', 'rto_minutes' => 60, 'rpo_minutes' => 15, 'downtime_cost_per_hour' => 10000, 'fallback_process' => 'Redundante Hardware/Cluster-Failover. MSP-Rufbereitschaft (P1, 30 Min). Restore aus Backup (3-2-1, Offline-Kopie gegen Ransomware). Bis Wiederanlauf: alle abhängigen Systeme im Notfallbetrieb (Papier). Isolation bei Verdacht auf Kompromittierung.', 'runbook_reference' => 'Runbook „RZ-Ausfall / Restore" v2.0', 'system_priority_id' => null, 'emergency_level_id' => null, 'created_at' => $ts, 'updated_at' => $ts],
                ['id' => $sys['internet'], 'name' => 'Internet- / Standortnetz', 'description' => 'Redundante Internet-Anbindung Hauptgebäude, internes LAN/WLAN und VPN-Standortkopplung zum MVZ. Firewall und Segmentierung (Office / Medizin / Verwaltung).', 'category' => 'basisbetrieb', 'rto_minutes' => 60, 'rpo_minutes' => null, 'downtime_cost_per_hour' => 2000, 'fallback_process' => 'Automatischer Failover auf Backup-Carrier. Interne Systeme laufen im LAN weiter (KIS/PACS lokal gehostet). TI/eAU und externe Dienste pausieren. Provider-Premium-SLA (4 h) eskalieren. MVZ ggf. autark per Notfall-Workflow.', 'runbook_reference' => 'Runbook „Netz-/Internet-Ausfall" v1.2', 'system_priority_id' => null, 'emergency_level_id' => null, 'created_at' => $ts, 'updated_at' => $ts],
                ['id' => $sys['m365'], 'name' => 'E-Mail / M365 (Verwaltung)', 'description' => 'Microsoft 365 für Verwaltung, Geschäftsführung und administrative Kommunikation. Nicht direkt patientenversorgungsrelevant.', 'category' => 'geschaeftsbetrieb', 'rto_minutes' => 480, 'rpo_minutes' => 60, 'downtime_cost_per_hour' => 400, 'fallback_process' => 'Telefon und Fax als Übergangs-Kommunikation. Mobile Webmail-Zugriff. Behörden-/Kassenkommunikation priorisiert per Telefon. Kein Versand sensibler Patientendaten über alternative private Kanäle.', 'runbook_reference' => null, 'system_priority_id' => null, 'emergency_level_id' => null, 'created_at' => $ts, 'updated_at' => $ts],
                ['id' => $sys['kueche'], 'name' => 'Speiseversorgung / Küchen-IT', 'description' => 'Menü- und Kostform-Management, Diät-/Allergen-Steuerung und Bestellung der Patientenverpflegung (inkl. Sonderkostformen).', 'category' => 'unterstuetzend', 'rto_minutes' => 720, 'rpo_minutes' => 240, 'downtime_cost_per_hour' => 300, 'fallback_process' => 'Standard-Menüplan und Kostformen aus Papier-Liste je Station. Diät- und Allergen-Anforderungen telefonisch an die Küche. Manuelle Erfassung, Nachpflege nach Wiederanlauf.', 'runbook_reference' => null, 'system_priority_id' => null, 'emergency_level_id' => null, 'created_at' => $ts, 'updated_at' => $ts],
                ['id' => $sys['glt'], 'name' => 'Gebäudeleittechnik (GLT)', 'description' => 'Gebäudeleittechnik für Heizung, Lüftung (OP-RLT), medizinische Gase, Wasser/Legionellen-Überwachung und Kälte. Sicherheitsrelevant für OP und Intensiv.', 'category' => 'basisbetrieb', 'rto_minutes' => 120, 'rpo_minutes' => null, 'downtime_cost_per_hour' => 3000, 'fallback_process' => 'Haustechnik schaltet betroffene Anlagen auf manuelle/lokale Steuerung. OP-RLT und medizinische Gase priorisiert überwachen. Bei RLT-Ausfall im OP: elektive Eingriffe stoppen. Servicepartner GLT sofort, Energieversorger einbinden.', 'runbook_reference' => 'Runbook „GLT-/Haustechnik-Ausfall" v1.1', 'system_priority_id' => null, 'emergency_level_id' => null, 'created_at' => $ts, 'updated_at' => $ts],
            ],

            'system_dependencies' => [
                ['system_id' => $sys['rz'], 'depends_on_system_id' => $sys['notstrom'], 'sort' => 0, 'note' => 'RZ hängt an NEA/USV.', 'created_at' => $ts, 'updated_at' => $ts],
                ['system_id' => $sys['mednetz'], 'depends_on_system_id' => $sys['notstrom'], 'sort' => 0, 'note' => 'Medizingeräte-Netz strompflichtig (lebenserhaltend).', 'created_at' => $ts, 'updated_at' => $ts],
                ['system_id' => $sys['schwesternruf'], 'depends_on_system_id' => $sys['notstrom'], 'sort' => 0, 'note' => null, 'created_at' => $ts, 'updated_at' => $ts],
                ['system_id' => $sys['glt'], 'depends_on_system_id' => $sys['notstrom'], 'sort' => 0, 'note' => 'OP-RLT und Gase strompflichtig.', 'created_at' => $ts, 'updated_at' => $ts],
                ['system_id' => $sys['internet'], 'depends_on_system_id' => $sys['notstrom'], 'sort' => 0, 'note' => null, 'created_at' => $ts, 'updated_at' => $ts],
                ['system_id' => $sys['kis'], 'depends_on_system_id' => $sys['rz'], 'sort' => 0, 'note' => 'KIS im RZ gehostet.', 'created_at' => $ts, 'updated_at' => $ts],
                ['system_id' => $sys['pacs'], 'depends_on_system_id' => $sys['rz'], 'sort' => 0, 'note' => null, 'created_at' => $ts, 'updated_at' => $ts],
                ['system_id' => $sys['pacs'], 'depends_on_system_id' => $sys['kis'], 'sort' => 1, 'note' => 'Auftrags-/Befundkommunikation über KIS.', 'created_at' => $ts, 'updated_at' => $ts],
                ['system_id' => $sys['lis'], 'depends_on_system_id' => $sys['rz'], 'sort' => 0, 'note' => null, 'created_at' => $ts, 'updated_at' => $ts],
                ['system_id' => $sys['lis'], 'depends_on_system_id' => $sys['kis'], 'sort' => 1, 'note' => 'Anforderung/Befundrückgabe über KIS.', 'created_at' => $ts, 'updated_at' => $ts],
                ['system_id' => $sys['pdms'], 'depends_on_system_id' => $sys['rz'], 'sort' => 0, 'note' => null, 'created_at' => $ts, 'updated_at' => $ts],
                ['system_id' => $sys['pdms'], 'depends_on_system_id' => $sys['mednetz'], 'sort' => 1, 'note' => 'Vitaldaten aus Medizingeräte-Netz.', 'created_at' => $ts, 'updated_at' => $ts],
                ['system_id' => $sys['apo'], 'depends_on_system_id' => $sys['kis'], 'sort' => 0, 'note' => 'Medikation/Bestellung aus KIS.', 'created_at' => $ts, 'updated_at' => $ts],
                ['system_id' => $sys['aufnahme'], 'depends_on_system_id' => $sys['kis'], 'sort' => 0, 'note' => 'ZNA-Doku in KIS.', 'created_at' => $ts, 'updated_at' => $ts],
                ['system_id' => $sys['blutbank'], 'depends_on_system_id' => $sys['lis'], 'sort' => 0, 'note' => 'Anbindung an Labor.', 'created_at' => $ts, 'updated_at' => $ts],
                ['system_id' => $sys['aemp'], 'depends_on_system_id' => $sys['rz'], 'sort' => 0, 'note' => null, 'created_at' => $ts, 'updated_at' => $ts],
                ['system_id' => $sys['kis'], 'depends_on_system_id' => $sys['internet'], 'sort' => 1, 'note' => 'MVZ-Anbindung per VPN.', 'created_at' => $ts, 'updated_at' => $ts],
                ['system_id' => $sys['m365'], 'depends_on_system_id' => $sys['internet'], 'sort' => 0, 'note' => null, 'created_at' => $ts, 'updated_at' => $ts],
            ],

            'insurance_policies' => [
                ['id' => Helpers::uuid(), 'type' => 'cyber', 'insurer' => 'Allianz Cyber (Healthcare)', 'policy_number' => 'CY-KMS-2026-010', 'hotline' => '0800 1009000', 'email' => 'cyber-healthcare@allianz.example', 'reporting_window' => 'unverzüglich, spätestens 24 Stunden', 'contact_name' => 'Incident-Hotline', 'notes' => 'Cyber-Deckung 5 Mio €, Healthcare-Tarif. Forensik, Krisendienstleister und Betriebsunterbrechung eingeschlossen. Patientendaten Art. 9 DSGVO.', 'deductible' => '25.000 €', 'created_at' => $ts, 'updated_at' => $ts],
                ['id' => Helpers::uuid(), 'type' => 'liability', 'insurer' => 'Ecclesia / Heilwesen-Haftpflicht', 'policy_number' => 'HW-KMS-2025-002', 'hotline' => '05231 603-0', 'email' => 'heilwesen-schaden@ecclesia.example', 'reporting_window' => 'binnen 7 Tagen', 'contact_name' => 'Schadenabteilung Heilwesen', 'notes' => 'Krankenhaus-/Heilwesen-Haftpflicht (Betriebs- und Berufshaftpflicht), Behandlungsfehler und Personenschäden.', 'deductible' => '10.000 €', 'created_at' => $ts, 'updated_at' => $ts],
                ['id' => Helpers::uuid(), 'type' => 'property', 'insurer' => 'VKB Sach (Gebäude/Technik)', 'policy_number' => 'PR-KMS-2024-033', 'hotline' => '089 2160-0', 'email' => 'sach-schaden@vkb.example', 'reporting_window' => 'binnen 7 Tagen', 'contact_name' => 'Fr. Mayer', 'notes' => 'Gebäude-, Inventar- und Elektronikversicherung inkl. Medizintechnik und Rechenzentrum.', 'deductible' => '5.000 €', 'created_at' => $ts, 'updated_at' => $ts],
                ['id' => Helpers::uuid(), 'type' => 'business_interruption', 'insurer' => 'Gothaer Gewerbe (BU)', 'policy_number' => 'BI-KMS-2025-021', 'hotline' => '0221 308-00', 'email' => 'bu-schaden@gothaer.example', 'reporting_window' => 'binnen 7 Tagen', 'contact_name' => 'Hr. Naumann', 'notes' => 'Betriebsunterbrechung bis 60 Tage, gekoppelt an Sach- und Cyber-Ereignisse (Ertragsausfall bei Notaufnahme-Abmeldung / OP-Stopp).', 'deductible' => '10.000 €', 'created_at' => $ts, 'updated_at' => $ts],
            ],

            'communication_templates' => [
                ['id' => Helpers::uuid(), 'name' => 'KIS-Ausfall – Anweisung an Stationen (Intranet/Aushang)', 'audience' => 'employees', 'channel' => 'intranet', 'subject' => 'KIS-Ausfall – Sofortmaßnahmen Notfallbetrieb', 'body' => "INTERNE ANWEISUNG — KIS-NOTFALLBETRIEB\n\nDas KIS (ORBIS) ist aktuell gestört. Ab sofort gilt der Notfallbetrieb:\n\n1. Dokumentation auf Papier: Notfall-Aufnahmebogen, Papier-Kurve und Anforderungsscheine aus dem Notfall-Schrank der Station verwenden.\n2. Patientenidentifikation über Armband / Aufnahmeunterlagen sicherstellen.\n3. Anforderungen an Labor und Radiologie per Papierschein + Telefon.\n4. KEINE Patientendaten über private Geräte oder Messenger versenden (Art. 9 DSGVO).\n5. Nach Wiederanlauf: lückenlose Nacherfassung aller Papierdaten ins KIS (haftungs- und abrechnungsrelevant).\n\nRückfragen: IT-Leitung Durchwahl 600-130. Stand: {{ zeitpunkt }}.", 'fallback' => 'Zusätzlich Aushang am Stationsstützpunkt; Stationsleitungen per DECT informieren.', 'sort' => 0, 'scenario_id' => null, 'created_at' => $ts, 'updated_at' => $ts],
                ['id' => Helpers::uuid(), 'name' => 'Patienten-/Angehörigen-Information (Telefon)', 'audience' => 'customers', 'channel' => 'phone', 'subject' => null, 'body' => "Anrufskript Patienten/Angehörige:\n\nGuten Tag, hier {{ ansprechpartner }} von der Kreisklinik Musterstadt.\n\nAufgrund einer technischen Störung kann es heute zu Wartezeiten bei {{ bereich }} kommen. Die medizinische Versorgung Ihres Angehörigen / Ihre Versorgung ist sichergestellt; wir arbeiten im geregelten Notfallbetrieb.\n\nGeplante Termine: {{ hinweis_termine }}\nBitte bringen Sie zur Aufnahme {{ benoetigte_unterlagen }} mit.\n\nBei Fragen erreichen Sie uns unter 07131 600-0. Vielen Dank für Ihr Verständnis.", 'fallback' => 'Bei Nichterreichen: Hinweis auf Website/Aushang am Haupteingang.', 'sort' => 1, 'scenario_id' => null, 'created_at' => $ts, 'updated_at' => $ts],
                ['id' => Helpers::uuid(), 'name' => 'Meldung an Gesundheitsamt / Behörde (E-Mail)', 'audience' => 'authorities', 'channel' => 'email', 'subject' => 'Meldung Betriebsstörung – Kreisklinik Musterstadt gGmbH', 'body' => "Sehr geehrte Damen und Herren,\n\nwir informieren Sie als zuständige Behörde über eine erhebliche Betriebsstörung an der Kreisklinik Musterstadt gGmbH.\n\nStörungsbeginn: {{ zeitpunkt }}\nBetroffene Bereiche/Systeme: {{ systeme }}\nAuswirkung auf die Versorgung: {{ auswirkung }}\nEingeleitete Maßnahmen: {{ massnahmen }} (Notfallbetrieb aktiv, KEL einberufen)\nVoraussichtliche Behebung: {{ prognose }}\n\nDie Patientenversorgung wird im Notfallbetrieb aufrechterhalten. Eine etwaige Notaufnahme-Abmeldung ist über IVENA/Leitstelle erfolgt.\n\nMit freundlichen Grüßen\nGeschäftsführung / KEL\nKreisklinik Musterstadt gGmbH", 'fallback' => 'Parallel telefonische Vorabinformation an das Gesundheitsamt.', 'sort' => 2, 'scenario_id' => null, 'created_at' => $ts, 'updated_at' => $ts],
                ['id' => Helpers::uuid(), 'name' => 'DSGVO-Meldung Aufsichtsbehörde (Art. 33, Patientendaten)', 'audience' => 'authorities', 'channel' => 'email', 'subject' => 'Meldung gemäß Art. 33 DSGVO – Kreisklinik Musterstadt gGmbH (besondere Kategorien)', 'body' => "Sehr geehrte Damen und Herren,\n\nhiermit melden wir gemäß Art. 33 DSGVO einen Sicherheitsvorfall mit Bezug zu personenbezogenen Daten besonderer Kategorien (Gesundheitsdaten, Art. 9 DSGVO).\n\nVerantwortlicher: Kreisklinik Musterstadt gGmbH\nBranche: Krankenhaus der Grund-/Regelversorgung\nZeitpunkt der Kenntnis: {{ zeitpunkt }}\nVorfall: {{ vorfall }}\nKategorien betroffener Daten: Patientenstamm-, Diagnose- und Behandlungsdaten\nBetroffene Personen (geschätzt): {{ anzahl }}\nEingeleitete Maßnahmen: {{ massnahmen }}\nExterner DSB: Dr. Engelhardt\n\nDie Meldung erfolgt unverzüglich, spätestens binnen 72 Stunden nach Kenntnis.\n\nMit freundlichen Grüßen\nGeschäftsführung\nKreisklinik Musterstadt gGmbH", 'fallback' => null, 'sort' => 3, 'scenario_id' => null, 'created_at' => $ts, 'updated_at' => $ts],
                ['id' => Helpers::uuid(), 'name' => 'Presse-Statement Betriebsstörung', 'audience' => 'press', 'channel' => 'email', 'subject' => 'Pressemitteilung: Technische Störung an der Kreisklinik Musterstadt', 'body' => "PRESSEMITTEILUNG\n\nKreisklinik Musterstadt: Technische Störung – Patientenversorgung gesichert\n\nMusterstadt, {{ datum }}. An der Kreisklinik Musterstadt kam es seit {{ zeitpunkt }} zu einer technischen Störung in {{ bereich }}. Die Klinik arbeitet im geregelten Notfallbetrieb; die Versorgung der Patientinnen und Patienten ist sichergestellt.\n\n{{ optional_notaufnahme }} Über die zentrale Leitstelle wurde eine vorübergehende Abmeldung der Notaufnahme veranlasst, um die Versorgung auf umliegende Häuser zu verteilen.\n\nDie Klinik steht in engem Austausch mit den zuständigen Behörden. Über den weiteren Verlauf informieren wir, sobald belastbare Erkenntnisse vorliegen.\n\nKontakt für Medienanfragen: Pressestelle, presse@kreisklinik-musterstadt.de, 07131 600-160.\n\n— Freigabe ausschließlich durch die Pressestelle in Abstimmung mit der Geschäftsführung. —", 'fallback' => 'Statement zusätzlich auf Klinik-Website und Social-Media nur nach Freigabe Pressestelle.', 'sort' => 4, 'scenario_id' => null, 'created_at' => $ts, 'updated_at' => $ts],
                ['id' => Helpers::uuid(), 'name' => 'Notaufnahme-Abmeldung Leitstelle/IVENA (Telefon)', 'audience' => 'authorities', 'channel' => 'phone', 'subject' => null, 'body' => "Anrufskript ZNA-Leitung → Integrierte Leitstelle / IVENA:\n\nHier {{ name }}, Leitung Zentrale Notaufnahme der Kreisklinik Musterstadt.\n\nWir müssen die Notaufnahme aufgrund {{ grund (System-/Stromausfall, Kapazität) }} ab sofort {{ teilweise/vollständig }} abmelden.\n\n- Betroffene Versorgungsbereiche: {{ bereiche }}\n- Weiterhin aufnahmefähig: {{ ausnahmen / vital bedrohte Fälle }}\n- Voraussichtliche Dauer: {{ prognose }}\n\nBitte Status in IVENA entsprechend setzen und Rettungsdienst-Disposition informieren. Rückmeldung erbeten an 07131 600-180.", 'fallback' => 'Parallel Eintrag in IVENA durch ZNA-Leitung; schriftliche Bestätigung per Mail nachreichen.', 'sort' => 5, 'scenario_id' => null, 'created_at' => $ts, 'updated_at' => $ts],
            ],

            'emergency_resources' => [
                ['id' => Helpers::uuid(), 'type' => 'offline_docs', 'name' => 'Krankenhausalarm- und Einsatzplan (KAEP)', 'description' => 'Vollständiger KAEP inkl. Alarmierungsstufen, KEL-Aufbau, MANV-Konzept, IT-Ausfall-Szenario und internem/externem Schadensfall. Pflicht nach Landeskrankenhausgesetz/Katastrophenschutz.', 'location' => 'KEL-Raum, Geschäftsführung, ZNA-Leitstand, Pforte (je 1 Papierexemplar)', 'access_holders' => 'KEL, Geschäftsführung, Ärztlicher Direktor, ZNA-Leitung, Pflegedirektion', 'last_check_at' => Helpers::date(-90), 'next_check_at' => Helpers::date(90), 'notes' => 'Jährliche Aktualisierung, Abstimmung mit Katastrophenschutzbehörde und Rettungsdienst.', 'sort' => 0, 'created_at' => $ts, 'updated_at' => $ts, 'last_reminder_sent_at' => null],
                ['id' => Helpers::uuid(), 'type' => 'offline_docs', 'name' => 'Manuelle Aufnahme-/Doku-Formulare (KIS-Notfallbetrieb)', 'description' => 'Vordruck-Sätze für Notfall-Aufnahmebogen, Papier-Kurve, Intensivkurve, Anforderungsscheine Labor/Radiologie, Triage-Bogen. Für den Betrieb bei KIS-Ausfall.', 'location' => 'Notfall-Schrank jeder Station + ZNA + Intensiv; Zentrallager Pflege', 'access_holders' => 'Alle Stationen, ZNA, Intensiv, Funktionsbereiche', 'last_check_at' => Helpers::date(-30), 'next_check_at' => Helpers::date(60), 'notes' => 'Mindestbestand quartalsweise prüfen, reservierter Notfall-Fallnummernkreis dokumentieren.', 'sort' => 1, 'created_at' => $ts, 'updated_at' => $ts, 'last_reminder_sent_at' => null],
                ['id' => Helpers::uuid(), 'type' => 'generator_ups', 'name' => 'Netzersatzanlage (NEA) + zentrale USV', 'description' => 'Diesel-Netzersatzanlage und zentrale USV für OP, Intensiv, ZNA, RZ und lebenserhaltende Geräte. Treibstoffvorrat für 24–72 h.', 'location' => 'Technikzentrale / NEA-Raum Untergeschoss', 'access_holders' => 'Haustechnik, Medizintechnik, IT-Leitung', 'last_check_at' => Helpers::date(-30), 'next_check_at' => Helpers::date(0), 'notes' => 'Monatlicher Probelauf unter Last (Prüfprotokoll). Treibstofffüllstand und Nachlieferungsvertrag prüfen.', 'sort' => 2, 'created_at' => $ts, 'updated_at' => $ts, 'last_reminder_sent_at' => null],
                ['id' => Helpers::uuid(), 'type' => 'replacement_hardware', 'name' => 'Notfall-Telefonliste + Krisen-Mobiltelefone', 'description' => 'Gedruckte Notfall-Telefonliste (KEL, Krisenrollen, Dienstleister, Behörden) + Pool von DECT-/Mobiltelefonen (anderer Provider) für Kommunikation bei IT-/Telefonausfall.', 'location' => 'KEL-Raum, Pforte, ZNA-Leitstand, IT-Leitung', 'access_holders' => 'KEL, Pforte, Stationsleitungen, IT-Leitung', 'last_check_at' => Helpers::date(-45), 'next_check_at' => Helpers::date(45), 'notes' => 'Liste bei Personalwechsel sofort aktualisieren; Akkus/Prepaid der Mobiltelefone halbjährlich prüfen.', 'sort' => 3, 'created_at' => $ts, 'updated_at' => $ts, 'last_reminder_sent_at' => null],
                ['id' => Helpers::uuid(), 'type' => 'offline_backup', 'name' => 'Offline-Backup (3-2-1, Ransomware-resistent)', 'description' => 'Tägliches Backup der klinischen Systeme nach 3-2-1-Regel mit einer physisch getrennten, offline gehaltenen Kopie (Air-Gap) als Schutz gegen Ransomware-Verschlüsselung.', 'location' => 'RZ + ausgelagerter Tresor/Brandschutzschrank (zweiter Brandabschnitt)', 'access_holders' => 'IT-Leitung, Stv. IT-Leitung, MSP (Restore)', 'last_check_at' => Helpers::date(-14), 'next_check_at' => Helpers::date(75), 'notes' => 'Restore-Tests planmäßig (siehe Testplan). Offline-Medium nach Sicherung physisch trennen.', 'sort' => 4, 'created_at' => $ts, 'updated_at' => $ts, 'last_reminder_sent_at' => null],
                ['id' => Helpers::uuid(), 'type' => 'password_safe', 'name' => 'Passwort-Safe Notfallzugänge', 'description' => 'Verschlüsselter Passwort-Safe mit Notfall-Administratorzugängen (KIS, RZ, Firewall, NEA-Steuerung) und versiegelter Papier-Notfallumschlag (Break-Glass).', 'location' => 'Tresor IT-Leitung (digital) + versiegelter Umschlag im Tresor Geschäftsführung', 'access_holders' => 'IT-Leitung, Stv. IT-Leitung, ISB; Break-Glass: Geschäftsführung', 'last_check_at' => Helpers::date(-60), 'next_check_at' => Helpers::date(120), 'notes' => 'Zugriff protokollieren. Nach Nutzung des Break-Glass-Umschlags Zugangsdaten rotieren.', 'sort' => 5, 'created_at' => $ts, 'updated_at' => $ts, 'last_reminder_sent_at' => null],
            ],

            'handbook_tests' => [
                ['id' => Helpers::uuid(), 'type' => 'tabletop', 'name' => 'Tabletop KIS-Totalausfall (24 h)', 'description' => 'Schreibtischübung: KIS/RZ 24 h nicht verfügbar (z. B. Ransomware). Notfallbetrieb mit Papier, Priorisierung Notaufnahme/OP, KEL-Aktivierung, Hersteller-/MSP-Eskalation, Nacherfassungs-Konzept, Meldewege (Art. 33 DSGVO, Behörden).', 'interval' => 'yearly', 'last_executed_at' => Helpers::date(-180), 'next_due_at' => Helpers::date(185), 'responsible_employee_id' => $emp['isb'], 'result_notes' => null, 'sort' => 0, 'created_at' => $ts, 'updated_at' => $ts, 'last_reminder_sent_at' => null],
                ['id' => Helpers::uuid(), 'type' => 'recovery', 'name' => 'Netzersatzanlagen-/USV-Test (Lastprobe)', 'description' => 'Geplanter Probelauf der NEA unter realer Last inkl. USV-Übergabe. Anlaufzeit, Lastübernahme OP/Intensiv/RZ und Treibstoffsystem prüfen. Prüfprotokoll führen.', 'interval' => 'monthly', 'last_executed_at' => Helpers::date(-25), 'next_due_at' => Helpers::date(5), 'responsible_employee_id' => $emp['medizintechnik'], 'result_notes' => null, 'sort' => 1, 'created_at' => $ts, 'updated_at' => $ts, 'last_reminder_sent_at' => null],
                ['id' => Helpers::uuid(), 'type' => 'backup_restore', 'name' => 'Restore-Test KIS-Backup', 'description' => 'Wiederherstellung des KIS aus dem Backup in eine isolierte Testumgebung. Datenkonsistenz, RPO-Einhaltung (15 Min) und Wiederanlaufzeit validieren. Offline-Kopie (Air-Gap) einbeziehen.', 'interval' => 'biannually', 'last_executed_at' => Helpers::date(-120), 'next_due_at' => Helpers::date(60), 'responsible_employee_id' => $emp['it_stv'], 'result_notes' => null, 'sort' => 2, 'created_at' => $ts, 'updated_at' => $ts, 'last_reminder_sent_at' => null],
                ['id' => Helpers::uuid(), 'type' => 'contact_check', 'name' => 'Krisenstab-Erreichbarkeit (KEL/Krisenrollen)', 'description' => 'Erreichbarkeitstest aller Krisenrollen und Mitglieder der Krankenhauseinsatzleitung sowie der P1-Dienstleister (KIS-Hersteller, MSP, Medizintechnik, Energieversorger) über die hinterlegten Notfallnummern.', 'interval' => 'quarterly', 'last_executed_at' => Helpers::date(-60), 'next_due_at' => Helpers::date(30), 'responsible_employee_id' => $emp['kel'], 'result_notes' => null, 'sort' => 3, 'created_at' => $ts, 'updated_at' => $ts, 'last_reminder_sent_at' => null],
                ['id' => Helpers::uuid(), 'type' => 'communication', 'name' => 'MANV-/Alarmierungsübung (KAEP)', 'description' => 'Übung zur internen Alarmierung und Krisenkommunikation nach KAEP (z. B. MANV-Szenario). Alarmierungskette, KEL-Aufbau, Kommunikation zu Leitstelle/IVENA und Gesundheitsamt sowie Pressestelle testen.', 'interval' => 'yearly', 'last_executed_at' => Helpers::date(-220), 'next_due_at' => Helpers::date(145), 'responsible_employee_id' => $emp['kel'], 'result_notes' => null, 'sort' => 4, 'created_at' => $ts, 'updated_at' => $ts, 'last_reminder_sent_at' => null],
            ],

            'system_tasks' => [
                ['id' => Helpers::uuid(), 'system_id' => $sys['notstrom'], 'title' => 'NEA-Probelauf unter Last', 'description' => 'Monatlicher Probelauf der Netzersatzanlage unter realer Last, Anlaufzeit und Lastübernahme dokumentieren, Treibstofffüllstand prüfen.', 'due_date' => Helpers::date(5), 'completed_at' => null, 'sort' => 0, 'created_at' => $ts, 'updated_at' => $ts],
                ['id' => Helpers::uuid(), 'system_id' => $sys['notstrom'], 'title' => 'Zentrale USV testen', 'description' => 'USV-Akku-/Lasttest, Überbrückungszeit messen, Batteriezustand und Übergabe an NEA prüfen.', 'due_date' => Helpers::date(20), 'completed_at' => null, 'sort' => 1, 'created_at' => $ts, 'updated_at' => $ts],
                ['id' => Helpers::uuid(), 'system_id' => $sys['kis'], 'title' => 'KIS-Patch-Management abstimmen', 'description' => 'Sicherheits-Updates und Patch-Stand mit KIS-Hersteller koordinieren, Wartungsfenster planen, Testsystem nutzen (§ 75c SGB V, Stand der Technik).', 'due_date' => Helpers::date(30), 'completed_at' => null, 'sort' => 0, 'created_at' => $ts, 'updated_at' => $ts],
                ['id' => Helpers::uuid(), 'system_id' => $sys['rz'], 'title' => 'Backup-Restore-Test (Offline-Kopie)', 'description' => 'Stichproben-Restore aus dem Offline-Backup in Testumgebung, Integrität und Wiederanlaufzeit dokumentieren.', 'due_date' => Helpers::date(45), 'completed_at' => null, 'sort' => 0, 'created_at' => $ts, 'updated_at' => $ts],
                ['id' => Helpers::uuid(), 'system_id' => $sys['mednetz'], 'title' => 'Medizintechnik STK/MTK-Prüfung', 'description' => 'Sicherheits- und messtechnische Kontrollen nach MPBetreibV planen/durchführen, Prüffristen vernetzter Medizinprodukte überwachen.', 'due_date' => Helpers::date(60), 'completed_at' => null, 'sort' => 0, 'created_at' => $ts, 'updated_at' => $ts],
                ['id' => Helpers::uuid(), 'system_id' => $sys['m365'], 'title' => 'Phishing-Awareness Personal', 'description' => 'Awareness-Schulung und simulierte Phishing-Kampagne für klinisches und administratives Personal (Fokus Patientendaten, Ransomware).', 'due_date' => Helpers::date(90), 'completed_at' => null, 'sort' => 0, 'created_at' => $ts, 'updated_at' => $ts],
            ],
        ]);
    }
}
