<?php

namespace Database\Seeders\IndustryTemplates;

use App\Enums\Industry;

class KrankenhausKritisTemplate implements Contract
{
    public function name(): string
    {
        return 'Krankenhaus (KRITIS, ≥ 30.000 Fälle/Jahr)';
    }

    public function industry(): Industry
    {
        return Industry::OeffentlicheEinrichtung;
    }

    public function description(): string
    {
        return 'Kommunaler Schwerpunkt-/Maximalversorger als Anstalt öffentlichen Rechts mit über 30.000 vollstationären Fällen/Jahr und damit KRITIS-pflichtige Anlage nach BSI-KritisV (Schwellenwert 30.000 Fälle) sowie wesentliche Einrichtung nach NIS2. Pflichten voll ausgebaut: Nachweis der IT-Sicherheit nach § 8a BSIG alle zwei Jahre, Meldepflicht erheblicher Störungen ans BSI nach § 8b BSIG, verpflichtende Anwendung des B3S Sicherheit für die Gesundheitsversorgung im Krankenhaus (DKG) als branchenspezifischer Sicherheitsstandard, IT-Sicherheitsverpflichtung nach § 75c SGB V, ISMS nach ISO 27001. Klinischer Schwerpunkt: OP-Zentrum, Intensivmedizin (PDMS), Zentrale Notaufnahme mit IVENA-Anbindung, Radiologie (PACS/RIS), Labor (LIS), Apotheke/Unit-Dose, Blutbank. Enthält rund 2.200 Mitarbeiter, 3 Standorte, 17 Systeme mit RTO/RPO (zentrales KIS, NEA/USV, SIEM/SOC, Air-Gap-Backup), 8 Dienstleister inkl. BSI-Meldestelle, Versicherungen, BSI-/MANV-/DSGVO-Kommunikationsvorlagen, KAEP-Notfallressourcen, KRITIS-Testplan (§ 8a-Audit, Meldeketten, Ransomware-Wiederanlauf) und system_tasks.';
    }

    public function sort(): int
    {
        return 94;
    }

    public function payload(): array
    {
        // Stable IDs, damit FK-Verweise innerhalb des Payloads konsistent
        // bleiben. Beim Apply werden sie via regenerateIds neu gemappt.
        $loc = [
            'klinikum' => Helpers::uuid(),
            'bettenhaus' => Helpers::uuid(),
            'rz_backup' => Helpers::uuid(),
        ];

        $emp = [
            'vorstand' => Helpers::uuid(),
            'aerztl_direktor' => Helpers::uuid(),
            'pflegedirektion' => Helpers::uuid(),
            'cio' => Helpers::uuid(),
            'cio_stv' => Helpers::uuid(),
            'ciso' => Helpers::uuid(),
            'hygieniker' => Helpers::uuid(),
            'medizintechnik' => Helpers::uuid(),
            'pressestelle' => Helpers::uuid(),
            'dsb' => Helpers::uuid(),
            'kel' => Helpers::uuid(),
            'notaufnahme' => Helpers::uuid(),
            'bcm' => Helpers::uuid(),
            'soc_lead' => Helpers::uuid(),
            'op_leitung' => Helpers::uuid(),
        ];

        $prov = [
            'bsi' => Helpers::uuid(),
            'soc' => Helpers::uuid(),
            'kis' => Helpers::uuid(),
            'medtech' => Helpers::uuid(),
            'lfdi' => Helpers::uuid(),
            'stadtwerke' => Helpers::uuid(),
            'carrier' => Helpers::uuid(),
            'cyber' => Helpers::uuid(),
        ];

        $sys = [
            'kis' => Helpers::uuid(),
            'pacs' => Helpers::uuid(),
            'lis' => Helpers::uuid(),
            'pdms' => Helpers::uuid(),
            'ris' => Helpers::uuid(),
            'op_system' => Helpers::uuid(),
            'medikation' => Helpers::uuid(),
            'blutbank' => Helpers::uuid(),
            'notaufnahme' => Helpers::uuid(),
            'schwesternruf' => Helpers::uuid(),
            'nea' => Helpers::uuid(),
            'biomed_netz' => Helpers::uuid(),
            'siem' => Helpers::uuid(),
            'backup' => Helpers::uuid(),
            'netzwerk' => Helpers::uuid(),
            'ti' => Helpers::uuid(),
            'glt' => Helpers::uuid(),
        ];

        $ts = Helpers::now();

        return Helpers::payload([
            'company' => [[
                'name' => 'Klinikum Musterstadt AöR',
                'industry' => 'oeffentliche_einrichtung',
                'employee_count' => 2200,
                'review_cycle_months' => 6,
                'legal_form' => 'aoer',
                'kritis_relevant' => 'yes',
                'nis2_classification' => 'essential',
                'cyber_insurance_deductible' => '100.000 €',
                'budget_it_lead' => 50000,
                'budget_emergency_officer' => 150000,
                'budget_management' => 2000000,
                'data_protection_authority_name' => 'LfDI Baden-Württemberg',
                'data_protection_authority_phone' => '0711 615541-0',
                'data_protection_authority_website' => 'https://www.baden-wuerttemberg.datenschutz.de',
            ]],

            'locations' => [
                [
                    'id' => $loc['klinikum'], 'name' => 'Hauptklinikum (Maximalversorger)', 'street' => 'Klinikstraße 1',
                    'postal_code' => '70173', 'city' => 'Musterstadt', 'country' => 'DE',
                    'is_headquarters' => 1, 'phone' => '0711 5000 0',
                    'notes' => 'Zentralgebäude mit OP-Zentrum (14 Säle), Intensivstationen (60 Betten), Zentraler Notaufnahme, Radiologie, Zentrallabor, Apotheke und primärem Rechenzentrum (redundante RZ-Räume, NEA + USV). Rund 1.000 Planbetten, > 30.000 vollstationäre Fälle/Jahr — KRITIS-Anlage nach BSI-KritisV.',
                    'sort' => 0, 'created_at' => $ts, 'updated_at' => $ts,
                ],
                [
                    'id' => $loc['bettenhaus'], 'name' => 'Bettenhaus Süd / 2. Standort', 'street' => 'Parkallee 24',
                    'postal_code' => '70597', 'city' => 'Musterstadt', 'country' => 'DE',
                    'is_headquarters' => 0, 'phone' => '0711 5000 4000',
                    'notes' => 'Zweiter Standort mit Normalstationen, Geriatrie, Reha und Verwaltung. Über Standortverbund (Dark-Fiber) an das Haupt-RZ angebunden. Eigene USV-Absicherung für Verteiler und Patientendaten-Zugriff.',
                    'sort' => 1, 'created_at' => $ts, 'updated_at' => $ts,
                ],
                [
                    'id' => $loc['rz_backup'], 'name' => 'Externes Backup-Rechenzentrum (Georedundanz)', 'street' => 'Rechenzentrumsweg 8',
                    'postal_code' => '76131', 'city' => 'Nachbarstadt', 'country' => 'DE',
                    'is_headquarters' => 0, 'phone' => '0721 9999 0',
                    'notes' => 'Georedundanter zweiter RZ-Standort (> 5 km, getrennte Brandabschnitte/Energieversorgung) für Cluster-Failover und Air-Gap-Backup. Anforderung aus B3S Krankenhaus / § 8a BSIG (Georedundanz kritischer Komponenten).',
                    'sort' => 2, 'created_at' => $ts, 'updated_at' => $ts,
                ],
            ],

            'employees' => [
                ['id' => $emp['vorstand'], 'first_name' => 'Dr.', 'last_name' => 'Vorstand Berger', 'position' => 'Vorstandsvorsitzender / Geschäftsführung', 'department' => 'Vorstand', 'work_phone' => '0711 5000 100', 'mobile_phone' => '0172 5000001', 'private_phone' => null, 'email' => 'vorstand@klinikum-musterstadt.example', 'emergency_contact' => null, 'manager_id' => null, 'is_key_personnel' => 1, 'crisis_role' => 'management', 'is_crisis_deputy' => 0, 'notes' => 'Gesamtverantwortung AöR, Rechenschaftspflicht nach § 8a BSIG und NIS2 (Geschäftsleitung haftet für ISMS). Vorsitz Krisenstab.', 'location_id' => $loc['klinikum'], 'created_at' => $ts, 'updated_at' => $ts],
                ['id' => $emp['aerztl_direktor'], 'first_name' => 'Prof. Dr.', 'last_name' => 'Ärztl. Direktor Sommer', 'position' => 'Ärztlicher Direktor', 'department' => 'Ärztliche Leitung', 'work_phone' => '0711 5000 110', 'mobile_phone' => '0172 5000002', 'private_phone' => null, 'email' => 'aerztl.direktor@klinikum-musterstadt.example', 'emergency_contact' => null, 'manager_id' => $emp['vorstand'], 'is_key_personnel' => 1, 'crisis_role' => 'management', 'is_crisis_deputy' => 1, 'notes' => 'Medizinische Gesamtverantwortung, Priorisierung Patientenversorgung bei IT-Ausfall, Schnittstelle zu Chefärzten.', 'location_id' => $loc['klinikum'], 'created_at' => $ts, 'updated_at' => $ts],
                ['id' => $emp['pflegedirektion'], 'first_name' => 'Andrea', 'last_name' => 'Pflegedirektion Wolf', 'position' => 'Pflegedirektorin / Notfallbeauftragte', 'department' => 'Pflegedirektion', 'work_phone' => '0711 5000 120', 'mobile_phone' => '0172 5000003', 'private_phone' => null, 'email' => 'pflegedirektion@klinikum-musterstadt.example', 'emergency_contact' => null, 'manager_id' => $emp['vorstand'], 'is_key_personnel' => 1, 'crisis_role' => 'emergency_officer', 'is_crisis_deputy' => 0, 'notes' => 'Notfallbeauftragte Pflege, verantwortlich für Umstellung auf manuelle Doku/Aufnahme bei KIS-Ausfall, Personalsteuerung MANV.', 'location_id' => $loc['klinikum'], 'created_at' => $ts, 'updated_at' => $ts],
                ['id' => $emp['cio'], 'first_name' => 'Markus', 'last_name' => 'CIO Hartmann', 'position' => 'CIO / IT-Leitung', 'department' => 'IT', 'work_phone' => '0711 5000 200', 'mobile_phone' => '0172 5000010', 'private_phone' => null, 'email' => 'cio@klinikum-musterstadt.example', 'emergency_contact' => null, 'manager_id' => $emp['vorstand'], 'is_key_personnel' => 1, 'crisis_role' => 'it_lead', 'is_crisis_deputy' => 0, 'notes' => 'Verantwortlich für Rechenzentrum, KIS, Netz, Wiederanlaufkoordination. Technischer Leiter Krisenstab.', 'location_id' => $loc['klinikum'], 'created_at' => $ts, 'updated_at' => $ts],
                ['id' => $emp['cio_stv'], 'first_name' => 'Sabine', 'last_name' => 'IT-Stv. Vogel', 'position' => 'Stv. IT-Leitung / Leitung RZ-Betrieb', 'department' => 'IT', 'work_phone' => '0711 5000 201', 'mobile_phone' => '0172 5000011', 'private_phone' => null, 'email' => 'it-stv@klinikum-musterstadt.example', 'emergency_contact' => null, 'manager_id' => $emp['cio'], 'is_key_personnel' => 1, 'crisis_role' => 'it_lead', 'is_crisis_deputy' => 1, 'notes' => 'Vertretung CIO, operativer RZ-Betrieb, Backup/Restore-Verantwortung, NEA-Koordination mit Technik.', 'location_id' => $loc['klinikum'], 'created_at' => $ts, 'updated_at' => $ts],
                ['id' => $emp['ciso'], 'first_name' => 'Thomas', 'last_name' => 'CISO Klein', 'position' => 'Informationssicherheitsbeauftragter (ISB/CISO) nach § 75c SGB V', 'department' => 'Informationssicherheit', 'work_phone' => '0711 5000 210', 'mobile_phone' => '0172 5000012', 'private_phone' => null, 'email' => 'ciso@klinikum-musterstadt.example', 'emergency_contact' => null, 'manager_id' => $emp['vorstand'], 'is_key_personnel' => 1, 'crisis_role' => 'it_lead', 'is_crisis_deputy' => 0, 'notes' => 'ISMS nach ISO 27001 / B3S Krankenhaus, § 8a-Nachweis, Meldekoordination ans BSI nach § 8b BSIG, direkt an Vorstand berichtend. Unabhängig von IT-Betrieb.', 'location_id' => $loc['klinikum'], 'created_at' => $ts, 'updated_at' => $ts],
                ['id' => $emp['hygieniker'], 'first_name' => 'Dr.', 'last_name' => 'Hygiene Fischer', 'position' => 'Krankenhaushygieniker', 'department' => 'Krankenhaushygiene', 'work_phone' => '0711 5000 130', 'mobile_phone' => '0172 5000013', 'private_phone' => null, 'email' => 'hygiene@klinikum-musterstadt.example', 'emergency_contact' => null, 'manager_id' => $emp['aerztl_direktor'], 'is_key_personnel' => 1, 'crisis_role' => null, 'is_crisis_deputy' => 0, 'notes' => 'Infektionsschutz nach IfSG, RKI-Meldungen, Schnittstelle Krisenstab bei Ausbruchsgeschehen (Doppelszenario Cyber + Hygiene).', 'location_id' => $loc['klinikum'], 'created_at' => $ts, 'updated_at' => $ts],
                ['id' => $emp['medizintechnik'], 'first_name' => 'Jürgen', 'last_name' => 'Medizintechnik Braun', 'position' => 'Leitung Medizintechnik (MPG/MPBetreibV)', 'department' => 'Medizintechnik', 'work_phone' => '0711 5000 220', 'mobile_phone' => '0172 5000014', 'private_phone' => null, 'email' => 'medizintechnik@klinikum-musterstadt.example', 'emergency_contact' => null, 'manager_id' => $emp['cio'], 'is_key_personnel' => 1, 'crisis_role' => null, 'is_crisis_deputy' => 0, 'notes' => 'Verantwortlich Medizingeräte-Bestand, STK/MTK nach MPBetreibV, Segmentierung Biomed-Netz, MDR-Konformität vernetzter Geräte.', 'location_id' => $loc['klinikum'], 'created_at' => $ts, 'updated_at' => $ts],
                ['id' => $emp['pressestelle'], 'first_name' => 'Claudia', 'last_name' => 'Presse Schäfer', 'position' => 'Leitung Unternehmenskommunikation / Pressestelle', 'department' => 'Kommunikation', 'work_phone' => '0711 5000 140', 'mobile_phone' => '0172 5000015', 'private_phone' => null, 'email' => 'presse@klinikum-musterstadt.example', 'emergency_contact' => null, 'manager_id' => $emp['vorstand'], 'is_key_personnel' => 1, 'crisis_role' => 'communications_lead', 'is_crisis_deputy' => 0, 'notes' => 'Krisenkommunikation Cyberangriff, Presse, Abstimmung mit BSI/Aufsicht vor Veröffentlichung, Angehörigen-/Patienteninformation.', 'location_id' => $loc['klinikum'], 'created_at' => $ts, 'updated_at' => $ts],
                ['id' => $emp['dsb'], 'first_name' => 'Petra', 'last_name' => 'Datenschutz Lang', 'position' => 'Datenschutzbeauftragte (intern)', 'department' => 'Datenschutz', 'work_phone' => '0711 5000 150', 'mobile_phone' => '0172 5000016', 'private_phone' => null, 'email' => 'datenschutz@klinikum-musterstadt.example', 'emergency_contact' => null, 'manager_id' => $emp['vorstand'], 'is_key_personnel' => 1, 'crisis_role' => 'dpo', 'is_crisis_deputy' => 0, 'notes' => 'Interne DSB. Art. 33/34 DSGVO bei Vorfällen mit Patientendaten (Gesundheitsdaten Art. 9), Meldung an LfDI binnen 72 h.', 'location_id' => $loc['klinikum'], 'created_at' => $ts, 'updated_at' => $ts],
                ['id' => $emp['kel'], 'first_name' => 'Dr.', 'last_name' => 'KEL Neumann', 'position' => 'Leiter Krankenhauseinsatzleitung (KEL)', 'department' => 'Krisenmanagement', 'work_phone' => '0711 5000 160', 'mobile_phone' => '0172 5000017', 'private_phone' => null, 'email' => 'kel@klinikum-musterstadt.example', 'emergency_contact' => null, 'manager_id' => $emp['vorstand'], 'is_key_personnel' => 1, 'crisis_role' => 'emergency_officer', 'is_crisis_deputy' => 1, 'notes' => 'Leitet die Krankenhauseinsatzleitung nach KAEP (Krankenhausalarm- und -einsatzplanung), Aktivierung bei MANV und IT-Großschadenslage.', 'location_id' => $loc['klinikum'], 'created_at' => $ts, 'updated_at' => $ts],
                ['id' => $emp['notaufnahme'], 'first_name' => 'Michael', 'last_name' => 'ZNA Wagner', 'position' => 'Pflegerische Leitung Zentrale Notaufnahme / Leitstelle', 'department' => 'Notaufnahme', 'work_phone' => '0711 5000 170', 'mobile_phone' => '0172 5000018', 'private_phone' => null, 'email' => 'zna-leitung@klinikum-musterstadt.example', 'emergency_contact' => null, 'manager_id' => $emp['pflegedirektion'], 'is_key_personnel' => 1, 'crisis_role' => null, 'is_crisis_deputy' => 0, 'notes' => 'IVENA-Anmeldung/Abmeldung von der Versorgung, Schnittstelle Rettungsleitstelle, Triage bei Systemausfall.', 'location_id' => $loc['klinikum'], 'created_at' => $ts, 'updated_at' => $ts],
                ['id' => $emp['bcm'], 'first_name' => 'Stefan', 'last_name' => 'BCM Krüger', 'position' => 'Notfall-/BCM-Beauftragter', 'department' => 'Informationssicherheit', 'work_phone' => '0711 5000 211', 'mobile_phone' => '0172 5000019', 'private_phone' => null, 'email' => 'bcm@klinikum-musterstadt.example', 'emergency_contact' => null, 'manager_id' => $emp['ciso'], 'is_key_personnel' => 1, 'crisis_role' => 'emergency_officer', 'is_crisis_deputy' => 0, 'notes' => 'Business Continuity Management nach B3S/ISO 22301, Pflege Notfallhandbuch, Wiederanlaufpläne, Koordination der Notfalltests.', 'location_id' => $loc['klinikum'], 'created_at' => $ts, 'updated_at' => $ts],
                ['id' => $emp['soc_lead'], 'first_name' => 'Daniel', 'last_name' => 'SOC Richter', 'position' => 'SOC-Koordinator / Security-Operations', 'department' => 'Informationssicherheit', 'work_phone' => '0711 5000 212', 'mobile_phone' => '0172 5000020', 'private_phone' => null, 'email' => 'soc@klinikum-musterstadt.example', 'emergency_contact' => null, 'manager_id' => $emp['ciso'], 'is_key_personnel' => 1, 'crisis_role' => 'it_lead', 'is_crisis_deputy' => 1, 'notes' => 'Schnittstelle zum externen SOC/MDR-Dienstleister, Triage SIEM-Alarme, Erstbewertung Meldepflicht § 8b BSIG.', 'location_id' => $loc['klinikum'], 'created_at' => $ts, 'updated_at' => $ts],
                ['id' => $emp['op_leitung'], 'first_name' => 'Birgit', 'last_name' => 'OP Hofmann', 'position' => 'Leitung OP-Management / Anästhesie-Pflege', 'department' => 'OP / Anästhesie', 'work_phone' => '0711 5000 180', 'mobile_phone' => '0172 5000021', 'private_phone' => null, 'email' => 'op-management@klinikum-musterstadt.example', 'emergency_contact' => null, 'manager_id' => $emp['pflegedirektion'], 'is_key_personnel' => 1, 'crisis_role' => null, 'is_crisis_deputy' => 0, 'notes' => 'OP-Programmsteuerung, Priorisierung/Absage elektiver Eingriffe bei IT- oder Stromausfall, Sicherstellung Notfall-OP-Kapazität.', 'location_id' => $loc['klinikum'], 'created_at' => $ts, 'updated_at' => $ts],
            ],

            'service_providers' => [
                ['id' => $prov['bsi'], 'name' => 'BSI – Meldestelle KRITIS (Nationales IT-Lagezentrum)', 'type' => 'bsi_reporting_office', 'contact_name' => 'Meldestelle / Single Point of Contact', 'hotline' => '0228 99 9582 222', 'email' => 'kritis@bsi.bund.de', 'contract_number' => 'KRITIS-Kontaktstelle reg. (BSIG § 8b Abs. 3)', 'sla' => '24/7 Lagezentrum', 'notes' => 'Pflicht-Meldestelle für erhebliche Störungen nach § 8b BSIG. Erstmeldung unverzüglich über das BSI-Meldeportal (registrierte Kontaktstelle). Auch Empfänger für NIS2-Meldekette. KEIN technischer Dienstleister.', 'direct_order_limit' => null, 'created_at' => $ts, 'updated_at' => $ts],
                ['id' => $prov['soc'], 'name' => 'CyberDefense SOC/MDR GmbH (24/7 Managed Detection & Response)', 'type' => 'it_msp', 'contact_name' => 'SOC-Schichtleitung', 'hotline' => '0800 7626100', 'email' => 'soc@cyberdefense.example', 'contract_number' => 'MDR-KH-2026-001', 'sla' => '24/7, P1-Reaktion < 15 Min', 'notes' => 'Externes SOC/MDR: SIEM-Auswertung, EDR-Alarmierung, Incident Response Retainer für Ransomware. Liefert forensische Unterstützung und IOC für BSI-Meldung.', 'direct_order_limit' => 50000, 'created_at' => $ts, 'updated_at' => $ts],
                ['id' => $prov['kis'], 'name' => 'KIS-Hersteller Healthcare Systems AG', 'type' => 'other', 'contact_name' => 'Critical-Support Krankenhaus', 'hotline' => '0800 5470000', 'email' => 'critical-support@kis-hersteller.example', 'contract_number' => 'KIS-WV-2025-KH', 'sla' => '24/7 P1 für KIS-Kernbetrieb, Reaktion < 30 Min', 'notes' => 'Hersteller des zentralen KIS. KRITISCH: bei Ausfall steht die gesamte klinische Dokumentation/Anordnung. Wartungsvertrag mit Notfall-Wiederanlauf und Georedundanz-Support.', 'direct_order_limit' => 50000, 'created_at' => $ts, 'updated_at' => $ts],
                ['id' => $prov['medtech'], 'name' => 'Medizintechnik-Service MedEngineering GmbH', 'type' => 'other', 'contact_name' => 'Technischer Außendienst', 'hotline' => '0711 6677 800', 'email' => 'service@medengineering.example', 'contract_number' => 'MT-WV-2025-44', 'sla' => 'Mo-Fr 7-19, Rufbereitschaft Intensiv/OP 24/7', 'notes' => 'Wartung/Instandhaltung vernetzter Medizingeräte (Beatmung, Monitoring, PACS-Modalitäten) nach MPBetreibV. STK/MTK-Durchführung, Patch-Freigabe für MDR-Geräte.', 'direct_order_limit' => 25000, 'created_at' => $ts, 'updated_at' => $ts],
                ['id' => $prov['lfdi'], 'name' => 'LfDI Baden-Württemberg (Aufsichtsbehörde)', 'type' => 'data_protection_authority', 'contact_name' => 'Meldestelle Datenpannen', 'hotline' => '0711 615541-0', 'email' => 'poststelle@lfdi.bwl.de', 'contract_number' => null, 'sla' => 'Mo-Fr 8-16', 'notes' => 'Aufsichtsbehörde für DSGVO Art. 33-Meldungen (binnen 72 h). Patientendaten = besondere Kategorien Art. 9 DSGVO. Getrennt von der BSI-Meldung nach § 8b BSIG.', 'direct_order_limit' => null, 'created_at' => $ts, 'updated_at' => $ts],
                ['id' => $prov['stadtwerke'], 'name' => 'Stadtwerke Musterstadt (Energieversorger)', 'type' => 'utility', 'contact_name' => 'Netzleitstelle / Großkunden', 'hotline' => '0711 289 0', 'email' => 'netzleitstelle@stadtwerke-musterstadt.example', 'contract_number' => 'EVU-KH-2024', 'sla' => 'Entstörung 24/7', 'notes' => 'Mittelspannungs-Anschluss Klinikum (zwei getrennte Einspeisungen). Bei Netzausfall übernimmt die hauseigene NEA. Priorisierte Wiederversorgung als KRITIS-Einrichtung.', 'direct_order_limit' => null, 'created_at' => $ts, 'updated_at' => $ts],
                ['id' => $prov['carrier'], 'name' => 'TelekomNetz Carrier (Standortverbund/Internet)', 'type' => 'internet_provider', 'contact_name' => 'Business Service Desk', 'hotline' => '0800 3301000', 'email' => 'business-noc@carrier.example', 'contract_number' => 'WAN-KH-2025-redundant', 'sla' => '99,95 %, Entstörung 4 h', 'notes' => 'Redundante Internet-/WAN-Anbindung (zwei Carrier-Wege, getrennte Trassen) für Standortverbund, TI, Georedundanz-Replikation.', 'direct_order_limit' => 10000, 'created_at' => $ts, 'updated_at' => $ts],
                ['id' => $prov['cyber'], 'name' => 'Heilwesen-Assekuranz (Cyber-Versicherer, Schadenstelle)', 'type' => 'other', 'contact_name' => 'Cyber-Notfall-Hotline', 'hotline' => '0800 4434464', 'email' => 'cyber-claims@heilwesen-assekuranz.example', 'contract_number' => 'CY-KH-2026-0007', 'sla' => '24/7 Incident-Hotline', 'notes' => 'Cyber-Versicherer mit Incident-Response-Netzwerk; im Schadenfall sofort einzubinden (Forensik, Verhandlungsführung Ransomware).', 'direct_order_limit' => null, 'created_at' => $ts, 'updated_at' => $ts],
            ],

            'systems' => [
                ['id' => $sys['kis'], 'name' => 'Krankenhausinformationssystem (KIS) – zentral', 'description' => 'Zentrales klinisches Informationssystem: Patientenakte, ärztliche/pflegerische Doku, Anordnungen, Stationsmanagement, Aufnahme/Verlegung/Entlassung (ADT). Herzstück der gesamten Versorgung, im Haupt-RZ als Cluster mit Georedundanz.', 'category' => 'basisbetrieb', 'rto_minutes' => 60, 'rpo_minutes' => 5, 'downtime_cost_per_hour' => 25000, 'fallback_process' => 'Sofort-Aktivierung KIS-Ausfall-Konzept (B3S): manuelle Aufnahme-/Verlegungsformulare, Papier-Kurve, Notfall-Patientenliste je Station. KEL/Krisenstab informieren. Hersteller-Critical-Support (24/7) + Georedundanz-Failover prüfen. Lückenlose Nacherfassung nach Wiederanlauf.', 'runbook_reference' => 'Runbook „KIS-Totalausfall / Ransomware" v2.3 (B3S Anlage)', 'system_priority_id' => null, 'emergency_level_id' => null, 'created_at' => $ts, 'updated_at' => $ts],
                ['id' => $sys['pacs'], 'name' => 'PACS – Bildarchiv Radiologie', 'description' => 'Picture Archiving and Communication System: Speicherung/Befundung radiologischer Bilddaten (CT, MRT, Röntgen), Anbindung an Modalitäten und KIS/RIS.', 'category' => 'basisbetrieb', 'rto_minutes' => 120, 'rpo_minutes' => 15, 'downtime_cost_per_hour' => 8000, 'fallback_process' => 'Befundung direkt an Modalitäts-Konsole, lokale Zwischenspeicherung, Notfall-Befund mündlich + Papier. Voraufnahmen über Georedundanz-Kopie abrufen.', 'runbook_reference' => 'Runbook „PACS-Ausfall" v1.4', 'system_priority_id' => null, 'emergency_level_id' => null, 'created_at' => $ts, 'updated_at' => $ts],
                ['id' => $sys['lis'], 'name' => 'Laborinformationssystem (LIS) – Zentrallabor', 'description' => 'Auftrags- und Befundsteuerung Zentrallabor inkl. Anbindung Analysenautomaten, Notfall-/Point-of-Care-Diagnostik.', 'category' => 'basisbetrieb', 'rto_minutes' => 120, 'rpo_minutes' => 15, 'downtime_cost_per_hour' => 7000, 'fallback_process' => 'Notfall-Parameter (Blutbild, Gerinnung, BGA) über Geräte-Direktausdruck/POCT. Papier-Anforderungsscheine, manuelle Befundübermittlung an Intensiv/OP/Notaufnahme.', 'runbook_reference' => 'Runbook „LIS-Ausfall" v1.3', 'system_priority_id' => null, 'emergency_level_id' => null, 'created_at' => $ts, 'updated_at' => $ts],
                ['id' => $sys['pdms'], 'name' => 'PDMS – Patientendatenmanagement Intensiv', 'description' => 'Patient Data Management System auf Intensiv- und Anästhesiestationen: Vitaldaten-Monitoring, Beatmung, Medikation, Bilanzierung. Direkt patientennah/lebenskritisch.', 'category' => 'basisbetrieb', 'rto_minutes' => 30, 'rpo_minutes' => 5, 'downtime_cost_per_hour' => 15000, 'fallback_process' => 'Umstellung auf Papier-Intensivkurve (vorgehalten je Bettplatz), Monitoring lokal am Gerät weiterführen, Medikation nach Papier-Anordnung. Höchste Priorität für Wiederanlauf nach KIS.', 'runbook_reference' => 'Runbook „PDMS/Intensiv-Ausfall" v1.5', 'system_priority_id' => null, 'emergency_level_id' => null, 'created_at' => $ts, 'updated_at' => $ts],
                ['id' => $sys['ris'], 'name' => 'RIS – Radiologie-Informationssystem', 'description' => 'Terminierung, Auftragssteuerung und Befundschreibung Radiologie; Bindeglied zwischen KIS und PACS.', 'category' => 'geschaeftsbetrieb', 'rto_minutes' => 240, 'rpo_minutes' => 15, 'downtime_cost_per_hour' => 3000, 'fallback_process' => 'Manuelle Terminsteuerung am Modalitäts-Arbeitsplatz, Papier-Auftrag, Befunddiktat offline mit späterer Nacherfassung.', 'runbook_reference' => null, 'system_priority_id' => null, 'emergency_level_id' => null, 'created_at' => $ts, 'updated_at' => $ts],
                ['id' => $sys['op_system'], 'name' => 'OP-/Anästhesie-Managementsystem', 'description' => 'OP-Planung, Saalbelegung, Anästhesie-Dokumentation, Materialdokumentation. Steuert das gesamte OP-Zentrum (14 Säle).', 'category' => 'basisbetrieb', 'rto_minutes' => 60, 'rpo_minutes' => 15, 'downtime_cost_per_hour' => 12000, 'fallback_process' => 'OP-Programm aus täglichem Papierausdruck weiterführen, Anästhesieprotokoll auf Papier, elektive Eingriffe priorisieren/verschieben. OP-Management + ärztl. Direktor entscheiden Saalbetrieb.', 'runbook_reference' => 'Runbook „OP-System-Ausfall" v1.2', 'system_priority_id' => null, 'emergency_level_id' => null, 'created_at' => $ts, 'updated_at' => $ts],
                ['id' => $sys['medikation'], 'name' => 'Medikation / Apotheke / Unit-Dose', 'description' => 'Geschlossener Medikationsprozess: elektronische Verordnung (CPOE), Apothekensystem, Unit-Dose-Verblisterung, Betäubungsmittel-Doku.', 'category' => 'basisbetrieb', 'rto_minutes' => 120, 'rpo_minutes' => 15, 'downtime_cost_per_hour' => 6000, 'fallback_process' => 'Papier-Verordnung und manuelle Stationsbevorratung aus Notfalldepot, BtM-Dokumentation handschriftlich, Apotheke beliefert nach Telefon-/Faxanforderung. Doppelte Kontrolle Hochrisiko-Medikation.', 'runbook_reference' => 'Runbook „Medikation/Unit-Dose-Ausfall" v1.1', 'system_priority_id' => null, 'emergency_level_id' => null, 'created_at' => $ts, 'updated_at' => $ts],
                ['id' => $sys['blutbank'], 'name' => 'Blutbank / Transfusionsmanagement', 'description' => 'Verwaltung Blutkonserven, Kreuzprobe, Transfusionsdokumentation (Transfusionsgesetz/Hämotherapie-Richtlinie), Anbindung Labor.', 'category' => 'basisbetrieb', 'rto_minutes' => 60, 'rpo_minutes' => 5, 'downtime_cost_per_hour' => 9000, 'fallback_process' => 'Notfall-Konservenausgabe nach manueller Kreuzprobe und Papier-Begleitschein, lückenlose handschriftliche Chargen-/Transfusionsdoku (rückverfolgbar nach TFG). Notfalldepot 0-negativ vorgehalten.', 'runbook_reference' => 'Runbook „Blutbank-Ausfall" v1.1', 'system_priority_id' => null, 'emergency_level_id' => null, 'created_at' => $ts, 'updated_at' => $ts],
                ['id' => $sys['notaufnahme'], 'name' => 'Notaufnahme-System + IVENA-Anbindung', 'description' => 'Ersteinschätzung/Triage (z. B. MTS), Verlaufsdoku Zentrale Notaufnahme und Anbindung an IVENA (Interdisziplinärer Versorgungsnachweis) zur An-/Abmeldung gegenüber der Rettungsleitstelle.', 'category' => 'basisbetrieb', 'rto_minutes' => 60, 'rpo_minutes' => 15, 'downtime_cost_per_hour' => 7000, 'fallback_process' => 'Triage auf Papier-Ersteinschätzungsbogen, Patientenliste manuell. IVENA-Status telefonisch an die Rettungsleitstelle melden; ggf. Abmeldung von der Versorgung einzelner Fachgebiete.', 'runbook_reference' => 'Runbook „ZNA/IVENA-Ausfall" v1.2', 'system_priority_id' => null, 'emergency_level_id' => null, 'created_at' => $ts, 'updated_at' => $ts],
                ['id' => $sys['schwesternruf'], 'name' => 'Patientenruf / Schwesternrufanlage', 'description' => 'Lichtruf-/Schwesternrufanlage aller Stationen inkl. Notruf Intensiv/OP; sicherheitsrelevant für die unmittelbare Patientenüberwachung.', 'category' => 'basisbetrieb', 'rto_minutes' => 30, 'rpo_minutes' => null, 'downtime_cost_per_hour' => 5000, 'fallback_process' => 'Erhöhte Präsenz-/Sichtkontrolle durch Pflegepersonal, mobile DECT-Telefone als Rückfallebene, Techniker-Rufbereitschaft sofort. Auf Intensiv lückenlose Sitzwache.', 'runbook_reference' => 'Runbook „Schwesternruf-Ausfall" v1.0', 'system_priority_id' => null, 'emergency_level_id' => null, 'created_at' => $ts, 'updated_at' => $ts],
                ['id' => $sys['nea'], 'name' => 'Netzersatzanlage (NEA) + USV', 'description' => 'Netzersatzanlage (Diesel-Notstrom) mit Dieselbevorratung und zentrale USV-Anlagen. Sichert OP, Intensiv, NotStromV-relevante Verbraucher und das Rechenzentrum. Lebenskritische Infrastruktur.', 'category' => 'basisbetrieb', 'rto_minutes' => 1, 'rpo_minutes' => null, 'downtime_cost_per_hour' => 40000, 'fallback_process' => 'USV überbrückt bis NEA-Anlauf (< 15 s) für Sicherheitsstromversorgung. Bei NEA-Störung: zweite NEA / mobiles Notstromaggregat (Vertrag), OP-/Intensiv-Priorisierung, Diesel-Nachschub über EVU/THW. Technik-Rufbereitschaft 24/7.', 'runbook_reference' => 'Runbook „Stromausfall / NEA-Betrieb" v2.0 (NotStromV/DIN VDE 0100-710)', 'system_priority_id' => null, 'emergency_level_id' => null, 'created_at' => $ts, 'updated_at' => $ts],
                ['id' => $sys['biomed_netz'], 'name' => 'Medizingeräte-/Biomed-Netz (segmentiert)', 'description' => 'Eigenes, vom Office-Netz getrenntes (segmentiertes) Netz für vernetzte Medizingeräte: Monitoring, Beatmung, Infusionspumpen, Modalitäten. Anforderung B3S/MPBetreibV.', 'category' => 'basisbetrieb', 'rto_minutes' => 60, 'rpo_minutes' => null, 'downtime_cost_per_hour' => 9000, 'fallback_process' => 'Geräte im autarken Stand-alone-Betrieb weiterführen (lokale Anzeige), manuelle Vitaldatenübernahme. Medizintechnik + IT prüfen Segment-Isolierung, ggf. gezielte Trennung bei Schadsoftware-Verdacht.', 'runbook_reference' => 'Runbook „Biomed-Netz-Ausfall/Isolierung" v1.1', 'system_priority_id' => null, 'emergency_level_id' => null, 'created_at' => $ts, 'updated_at' => $ts],
                ['id' => $sys['siem'], 'name' => 'SIEM / SOC / EDR (KRITIS-Detektion)', 'description' => 'Security Information and Event Management mit angebundenem 24/7-SOC und EDR auf Endpoints/Servern. Pflicht-Angriffserkennung für KRITIS (§ 8a Abs. 1a BSIG: Systeme zur Angriffserkennung).', 'category' => 'unterstuetzend', 'rto_minutes' => 60, 'rpo_minutes' => 15, 'downtime_cost_per_hour' => 4000, 'fallback_process' => 'Bei SIEM-Ausfall: SOC-Dienstleister informieren, erhöhte manuelle Log-Sichtung kritischer Systeme, EDR-Konsole direkt prüfen. Detektionslücke dokumentieren (nachweisrelevant § 8a).', 'runbook_reference' => 'Runbook „SIEM/SOC-Ausfall" v1.2', 'system_priority_id' => null, 'emergency_level_id' => null, 'created_at' => $ts, 'updated_at' => $ts],
                ['id' => $sys['backup'], 'name' => 'Backup 3-2-1 + Air-Gap (offline/immutable)', 'description' => 'Backup-Infrastruktur nach 3-2-1-Regel mit immutablem, physisch getrenntem Air-Gap-Backup im georedundanten RZ. Zentrale Wiederanlauf-Grundlage nach Ransomware.', 'category' => 'unterstuetzend', 'rto_minutes' => 240, 'rpo_minutes' => 60, 'downtime_cost_per_hour' => 5000, 'fallback_process' => 'Air-Gap-/Offline-Backup ist bewusst vom Netz getrennt — bei Ransomware Restore aus immutabler Kopie nach Forensik-Freigabe. Restore-Reihenfolge: KIS → PDMS → Labor/Blutbank → OP. Regelmäßige Restore-Tests sind § 8a-Nachweis.', 'runbook_reference' => 'Runbook „Restore Air-Gap-Backup" v2.1', 'system_priority_id' => null, 'emergency_level_id' => null, 'created_at' => $ts, 'updated_at' => $ts],
                ['id' => $sys['netzwerk'], 'name' => 'Standort-/Campusnetz + VPN', 'description' => 'Campus-LAN/WLAN, Standortverbund (Dark-Fiber) zwischen Haupt- und Nebenstandort, VPN für Fernwartung und Heimarbeitsplätze.', 'category' => 'basisbetrieb', 'rto_minutes' => 120, 'rpo_minutes' => null, 'downtime_cost_per_hour' => 6000, 'fallback_process' => 'Redundante Core-Switche/zweite Faser-Trasse automatisch aktiv. Bei VPN-Kompromittierung sofort Fernzugänge sperren (Eindämmung). Standort Süd kann lokal eingeschränkt weiterarbeiten.', 'runbook_reference' => 'Runbook „Netz-/VPN-Ausfall" v1.3', 'system_priority_id' => null, 'emergency_level_id' => null, 'created_at' => $ts, 'updated_at' => $ts],
                ['id' => $sys['ti'], 'name' => 'Telematik-Infrastruktur (TI) / Konnektor', 'description' => 'Anbindung an die Telematik-Infrastruktur (Konnektor, eGK/HBA, eAU/eRezept, KIM/ePA-Komponenten).', 'category' => 'geschaeftsbetrieb', 'rto_minutes' => 480, 'rpo_minutes' => 60, 'downtime_cost_per_hour' => 1500, 'fallback_process' => 'Ersatzverfahren nach gematik-Vorgaben (Papier/PDF), Aufnahme über Ersatzverfahren eGK. Kein unmittelbarer Versorgungsstopp.', 'runbook_reference' => null, 'system_priority_id' => null, 'emergency_level_id' => null, 'created_at' => $ts, 'updated_at' => $ts],
                ['id' => $sys['glt'], 'name' => 'Gebäudeleittechnik (medizinische Gase, Heizung, Wasser, Kälte)', 'description' => 'GLT/Technisches Gebäudemanagement: medizinische Gase (Sauerstoff/Druckluft/Vakuum), Heizung, Trinkwasser, Kälte/Klima (OP/Intensiv/Serverraum), Sterilgutversorgung (AEMP).', 'category' => 'basisbetrieb', 'rto_minutes' => 30, 'rpo_minutes' => null, 'downtime_cost_per_hour' => 11000, 'fallback_process' => 'Medizinische Gase: Notfall-Flaschenbatterien und manuelle Umschaltung. Kälte OP/Serverraum: mobile Kühlung. Technik-Rufbereitschaft 24/7, AEMP-Ersatzsterilisation extern. Trinkwasser-Hygiene nach IfSG sicherstellen.', 'runbook_reference' => 'Runbook „GLT/Medizinische Gase/Kälte" v1.2', 'system_priority_id' => null, 'emergency_level_id' => null, 'created_at' => $ts, 'updated_at' => $ts],
            ],

            'system_dependencies' => [
                ['system_id' => $sys['kis'], 'depends_on_system_id' => $sys['nea'], 'sort' => 0, 'note' => 'RZ hängt an Sicherheitsstromversorgung (NEA/USV).', 'created_at' => $ts, 'updated_at' => $ts],
                ['system_id' => $sys['kis'], 'depends_on_system_id' => $sys['netzwerk'], 'sort' => 1, 'note' => 'Campusnetz für Stationszugriff.', 'created_at' => $ts, 'updated_at' => $ts],
                ['system_id' => $sys['pacs'], 'depends_on_system_id' => $sys['kis'], 'sort' => 0, 'note' => 'Patientenkontext/Aufträge aus KIS.', 'created_at' => $ts, 'updated_at' => $ts],
                ['system_id' => $sys['pacs'], 'depends_on_system_id' => $sys['nea'], 'sort' => 1, 'note' => 'Bildarchiv im RZ.', 'created_at' => $ts, 'updated_at' => $ts],
                ['system_id' => $sys['lis'], 'depends_on_system_id' => $sys['kis'], 'sort' => 0, 'note' => 'Auftragsanbindung KIS.', 'created_at' => $ts, 'updated_at' => $ts],
                ['system_id' => $sys['pdms'], 'depends_on_system_id' => $sys['kis'], 'sort' => 0, 'note' => 'Stamm-/Falldaten aus KIS.', 'created_at' => $ts, 'updated_at' => $ts],
                ['system_id' => $sys['pdms'], 'depends_on_system_id' => $sys['biomed_netz'], 'sort' => 1, 'note' => 'Vitaldaten über Medizingeräte-Netz.', 'created_at' => $ts, 'updated_at' => $ts],
                ['system_id' => $sys['pdms'], 'depends_on_system_id' => $sys['nea'], 'sort' => 2, 'note' => 'Intensiv an Sicherheitsstrom.', 'created_at' => $ts, 'updated_at' => $ts],
                ['system_id' => $sys['ris'], 'depends_on_system_id' => $sys['kis'], 'sort' => 0, 'note' => null, 'created_at' => $ts, 'updated_at' => $ts],
                ['system_id' => $sys['ris'], 'depends_on_system_id' => $sys['pacs'], 'sort' => 1, 'note' => 'RIS-PACS-Kopplung.', 'created_at' => $ts, 'updated_at' => $ts],
                ['system_id' => $sys['op_system'], 'depends_on_system_id' => $sys['kis'], 'sort' => 0, 'note' => 'Falldaten/Anordnungen.', 'created_at' => $ts, 'updated_at' => $ts],
                ['system_id' => $sys['op_system'], 'depends_on_system_id' => $sys['nea'], 'sort' => 1, 'note' => 'OP an Sicherheitsstrom.', 'created_at' => $ts, 'updated_at' => $ts],
                ['system_id' => $sys['medikation'], 'depends_on_system_id' => $sys['kis'], 'sort' => 0, 'note' => 'CPOE-Verordnung aus KIS.', 'created_at' => $ts, 'updated_at' => $ts],
                ['system_id' => $sys['blutbank'], 'depends_on_system_id' => $sys['lis'], 'sort' => 0, 'note' => 'Kreuzprobe/Labor-Kopplung.', 'created_at' => $ts, 'updated_at' => $ts],
                ['system_id' => $sys['notaufnahme'], 'depends_on_system_id' => $sys['kis'], 'sort' => 0, 'note' => 'Patientenanlage über KIS.', 'created_at' => $ts, 'updated_at' => $ts],
                ['system_id' => $sys['notaufnahme'], 'depends_on_system_id' => $sys['netzwerk'], 'sort' => 1, 'note' => 'IVENA über Internet/WAN.', 'created_at' => $ts, 'updated_at' => $ts],
                ['system_id' => $sys['schwesternruf'], 'depends_on_system_id' => $sys['nea'], 'sort' => 0, 'note' => 'Rufanlage an Sicherheitsstrom.', 'created_at' => $ts, 'updated_at' => $ts],
                ['system_id' => $sys['biomed_netz'], 'depends_on_system_id' => $sys['nea'], 'sort' => 0, 'note' => null, 'created_at' => $ts, 'updated_at' => $ts],
                ['system_id' => $sys['siem'], 'depends_on_system_id' => $sys['netzwerk'], 'sort' => 0, 'note' => 'Log-/EDR-Sammlung über Netz.', 'created_at' => $ts, 'updated_at' => $ts],
                ['system_id' => $sys['netzwerk'], 'depends_on_system_id' => $sys['nea'], 'sort' => 0, 'note' => 'Core-Switche im RZ.', 'created_at' => $ts, 'updated_at' => $ts],
                ['system_id' => $sys['ti'], 'depends_on_system_id' => $sys['netzwerk'], 'sort' => 0, 'note' => 'Konnektor über WAN.', 'created_at' => $ts, 'updated_at' => $ts],
                ['system_id' => $sys['glt'], 'depends_on_system_id' => $sys['nea'], 'sort' => 0, 'note' => 'GLT-Steuerung an Sicherheitsstrom.', 'created_at' => $ts, 'updated_at' => $ts],
                ['system_id' => $sys['backup'], 'depends_on_system_id' => $sys['nea'], 'sort' => 0, 'note' => 'Air-Gap-Backup bewusst NICHT vom Produktivnetz abhängig (Offline-Schutz), aber Strom im RZ erforderlich.', 'created_at' => $ts, 'updated_at' => $ts],
            ],

            'insurance_policies' => [
                ['id' => Helpers::uuid(), 'type' => 'cyber', 'insurer' => 'Heilwesen-Assekuranz Cyber (KRITIS)', 'policy_number' => 'CY-KH-2026-0007', 'hotline' => '0800 4434464', 'email' => 'cyber-claims@heilwesen-assekuranz.example', 'reporting_window' => 'unverzüglich, spätestens 24 Stunden', 'contact_name' => 'Cyber-Notfall-Hotline', 'notes' => 'Deckung 25 Mio €, KRITIS-/Krankenhaus-Spezialtarif inkl. Betriebsunterbrechung, Forensik, Lösegeld-Verhandlung, Krisenkommunikation. Abstimmung mit BSI-Meldung erforderlich.', 'deductible' => '100.000 €', 'created_at' => $ts, 'updated_at' => $ts],
                ['id' => Helpers::uuid(), 'type' => 'liability', 'insurer' => 'Versicherungskammer (Heilwesen-Haftpflicht)', 'policy_number' => 'BHV-KH-2025-12', 'hotline' => '089 2160-0', 'email' => 'heilwesen-schaden@vkb.example', 'reporting_window' => 'unverzüglich nach Bekanntwerden', 'contact_name' => 'Schadenstelle Heilwesen', 'notes' => 'Betriebs-/Heilwesenhaftpflicht Maximalversorger, Deckung 50 Mio €, inkl. Patientenschäden infolge IT-Ausfall.', 'deductible' => '50.000 €', 'created_at' => $ts, 'updated_at' => $ts],
                ['id' => Helpers::uuid(), 'type' => 'property', 'insurer' => 'Allianz Sach AG (Gebäude/Technik)', 'policy_number' => 'PROP-KH-2025-08', 'hotline' => '0800 1112020', 'email' => 'sach-schaden@allianz.example', 'reporting_window' => 'binnen 3 Tagen', 'contact_name' => 'Industrie-Schaden', 'notes' => 'Gebäude-, Inhalts- und Technikversicherung (inkl. Medizintechnik, RZ-Hardware, NEA). Elektronik-/Maschinenbruch eingeschlossen.', 'deductible' => '25.000 €', 'created_at' => $ts, 'updated_at' => $ts],
                ['id' => Helpers::uuid(), 'type' => 'business_interruption', 'insurer' => 'Allianz Sach AG (Betriebsunterbrechung)', 'policy_number' => 'BI-KH-2025-09', 'hotline' => '0800 1112020', 'email' => 'bu-schaden@allianz.example', 'reporting_window' => 'binnen 3 Tagen', 'contact_name' => 'Industrie-Schaden BU', 'notes' => 'Betriebsunterbrechung bis 90 Tage Haftzeit; deckt Erlösausfall durch Versorgungs-/Aufnahmestopp (auch infolge Cybervorfall).', 'deductible' => '50.000 €', 'created_at' => $ts, 'updated_at' => $ts],
            ],

            'communication_templates' => [
                ['id' => Helpers::uuid(), 'name' => 'BSI-Erstmeldung § 8b BSIG / NIS2 (24 h)', 'audience' => 'authorities', 'channel' => 'email', 'subject' => 'Meldung erheblicher Störung gem. § 8b BSIG – Klinikum Musterstadt AöR (KRITIS Gesundheit)', 'body' => "Über das BSI-Meldeportal (registrierte Kontaktstelle) – ersatzweise per E-Mail/Telefon:\n\nMeldende Einrichtung: Klinikum Musterstadt AöR (KRITIS-Anlage Sektor Gesundheit, BSI-KritisV)\nKontaktstelle: {{ kontaktstelle }} / {{ telefon }}\n\nArt der Störung: {{ stoerungsart }} (z. B. Ransomware/Ausfall KIS)\nZeitpunkt Eintritt/Kenntnis: {{ zeitpunkt }}\nBetroffene Anlagenteile/Dienste: {{ betroffene_systeme }}\nAuswirkung auf die kritische Dienstleistung (stationäre Versorgung): {{ auswirkung }}\nGgf. Abmeldung von der Versorgung (IVENA): {{ ivena_status }}\nBisherige Maßnahmen: {{ massnahmen }}\nVoraussichtliche Dauer: {{ prognose }}\n\nErstmeldung unverzüglich; Folgemeldungen und Abschlussmeldung folgen. Parallel informiert: Cyber-Versicherer, SOC/MDR-Dienstleister.\n\n{{ ciso_name }}, Informationssicherheitsbeauftragter", 'fallback' => 'Wenn Meldeportal nicht erreichbar: telefonische Erstmeldung BSI-Lagezentrum 0228 99 9582 222, schriftliche Nachreichung.', 'sort' => 0, 'scenario_id' => null, 'created_at' => $ts, 'updated_at' => $ts],
                ['id' => Helpers::uuid(), 'name' => 'MANV / Großschadenslage – Meldung Rettungsleitstelle', 'audience' => 'authorities', 'channel' => 'phone', 'subject' => null, 'body' => "Anrufskript Integrierte Rettungsleitstelle:\n\nHier Klinikum Musterstadt, Krankenhauseinsatzleitung (KEL), {{ name }}.\n\nWir aktivieren den Krankenhausalarmplan (KAEP) wegen {{ anlass }} (z. B. MANV / IT-Großschadenslage).\nAufnahmekapazität aktuell: {{ kapazitaet }} (Schockraum/Intensiv/OP).\nIVENA-Status wird gesetzt auf: {{ ivena }} (teilweise/komplette Abmeldung Fachgebiete: {{ fachgebiete }}).\nKontakt KEL: 0711 5000 160 / 0172 5000017.\n\nBitte um Rückmeldung zur Patientenverteilung im Versorgungsgebiet.", 'fallback' => 'Parallel Funkkontakt; bei Telefonausfall Satellitentelefon der KEL nutzen.', 'sort' => 1, 'scenario_id' => null, 'created_at' => $ts, 'updated_at' => $ts],
                ['id' => Helpers::uuid(), 'name' => 'KIS-Ausfall – klinikweite Anweisung', 'audience' => 'employees', 'channel' => 'intranet', 'subject' => 'SOFORTMASSNAHME: KIS-Ausfall – Umstellung auf manuelles Verfahren', 'body' => "KLINIKWEITE ANWEISUNG (KIS-Ausfall-Konzept B3S)\n\nDas zentrale KIS ist gestört (Stand {{ zeitpunkt }}). Krisenstab/KEL aktiviert.\n\n1. SOFORT Umstellung auf Papierverfahren: Aufnahme-/Verlegungsbögen, Papier-Kurve, Notfall-Medikationsbogen (Notfallordner je Station).\n2. Intensiv/OP: Papier-Intensivkurve und Anästhesieprotokoll, lückenlose Doku.\n3. Labor/Radiologie nur Notfallanforderungen (Papierschein, telefonische Befundübermittlung).\n4. KEINE eigenmächtigen Systemneustarts; bei Verdacht auf Schadsoftware Geräte NICHT herunterfahren, sondern IT/SOC informieren.\n5. Alle Maßnahmen dokumentieren für spätere Nacherfassung.\n\nRückfragen: IT-Leitstand 0711 5000 200, Pflegedirektion 0711 5000 120.", 'fallback' => 'Bei Intranet-Ausfall: Aushang Stationen + Telefonkette über Bereichsleitungen, Lautsprecherdurchsage.', 'sort' => 2, 'scenario_id' => null, 'created_at' => $ts, 'updated_at' => $ts],
                ['id' => Helpers::uuid(), 'name' => 'Patienten-/Angehörigen-Information (Hotline)', 'audience' => 'customers', 'channel' => 'phone', 'subject' => null, 'body' => "Sprechzettel Info-Hotline für Patienten/Angehörige:\n\nGuten Tag, Klinikum Musterstadt, {{ name }}.\n\nAufgrund einer technischen Störung kann es derzeit zu Wartezeiten und Verschiebungen planbarer Termine/Eingriffe kommen. Die Notfallversorgung ist sichergestellt.\n• Planbare Termine: {{ regelung }} (ggf. Verschiebung, wir melden uns).\n• Notfälle: jederzeit über die Zentrale Notaufnahme.\n• Angehörige auf Station: bitte telefonisch unter {{ stationsnummer }}.\n\nWir bitten um Verständnis. Aktuelle Infos auch auf {{ website }}.", 'fallback' => 'Zusätzliche Info auf Website/Aushang Haupteingang; Bürgertelefon mit erhöhter Besetzung.', 'sort' => 3, 'scenario_id' => null, 'created_at' => $ts, 'updated_at' => $ts],
                ['id' => Helpers::uuid(), 'name' => 'DSGVO Art. 33 – Patientendaten (Aufsichtsbehörde)', 'audience' => 'authorities', 'channel' => 'email', 'subject' => 'Meldung gem. Art. 33 DSGVO – Klinikum Musterstadt AöR (besondere Kategorien, Art. 9)', 'body' => "Sehr geehrte Damen und Herren,\n\nhiermit melden wir gemäß Art. 33 DSGVO (binnen 72 h) einen Sicherheitsvorfall mit personenbezogenen Daten besonderer Kategorien (Gesundheitsdaten, Art. 9).\n\nVerantwortlicher: Klinikum Musterstadt AöR\nZeitpunkt der Kenntnis: {{ zeitpunkt }}\nArt des Vorfalls: {{ vorfall }}\nBetroffene Datenkategorien: {{ datenkategorien }}\nGeschätzte Zahl Betroffener / Datensätze: {{ anzahl }}\nWahrscheinliche Folgen: {{ folgen }}\nGetroffene/geplante Maßnahmen: {{ massnahmen }}\nDSB: Petra Lang (intern), datenschutz@klinikum-musterstadt.example\n\nDiese Meldung erfolgt zusätzlich zur Meldung nach § 8b BSIG ans BSI.\n\nMit freundlichen Grüßen\n{{ dsb_name }}, Datenschutzbeauftragte", 'fallback' => 'Bei drohendem hohen Risiko zusätzlich Benachrichtigung Betroffener nach Art. 34 DSGVO vorbereiten.', 'sort' => 4, 'scenario_id' => null, 'created_at' => $ts, 'updated_at' => $ts],
                ['id' => Helpers::uuid(), 'name' => 'Presse-/Krisenkommunikation Cyberangriff', 'audience' => 'press', 'channel' => 'email', 'subject' => 'Pressemitteilung – IT-Sicherheitsvorfall am Klinikum Musterstadt', 'body' => "PRESSEMITTEILUNG (Freigabe nur durch Vorstand + Pressestelle, Abstimmung mit BSI)\n\nDas Klinikum Musterstadt ist von einem IT-Sicherheitsvorfall betroffen. Wir haben unmittelbar unsere Notfallpläne aktiviert und die zuständigen Behörden (BSI, Datenschutzaufsicht) informiert.\n\n• Die Notfall- und Akutversorgung ist sichergestellt.\n• Planbare Eingriffe/Termine können {{ einschraenkung }}.\n• Ein Krisenstab steuert den Wiederanlauf gemeinsam mit externen IT-Sicherheitsexperten.\n• Für die Sicherheit von Patientendaten gilt höchste Priorität; Untersuchungen dauern an.\n\nKontakt Pressestelle: presse@klinikum-musterstadt.example, 0711 5000 140.\nStand: {{ zeitpunkt }}", 'fallback' => 'Einheitliche Sprachregelung; keine Detail-/Spekulationsauskünfte vor BSI-Abstimmung. Social-Media-Kanäle mit identischer Kernbotschaft.', 'sort' => 5, 'scenario_id' => null, 'created_at' => $ts, 'updated_at' => $ts],
            ],

            'emergency_resources' => [
                ['id' => Helpers::uuid(), 'type' => 'offline_docs', 'name' => 'KAEP + B3S-Notfallkonzept (Papier)', 'description' => 'Krankenhausalarm- und -einsatzplanung (KAEP) inkl. IT-Notfallkonzept nach B3S Krankenhaus: Alarmierungswege, KEL-Struktur, KIS-Ausfall-Verfahren, Wiederanlaufpläne, BSI-/DSGVO-Meldeketten.', 'location' => 'KEL-Raum, IT-Leitstand, Pflegedirektion, Vorstand (je Papierexemplar)', 'access_holders' => 'Vorstand, KEL, CISO/BCM, CIO, Pflegedirektion', 'last_check_at' => Helpers::date(-30), 'next_check_at' => Helpers::date(150), 'notes' => 'Mindestens halbjährliche Aktualisierung (review_cycle 6 Monate). Bewusst auch offline vorgehalten – muss bei Totalausfall ohne IT nutzbar sein.', 'sort' => 0, 'created_at' => $ts, 'updated_at' => $ts, 'last_reminder_sent_at' => null],
                ['id' => Helpers::uuid(), 'type' => 'offline_docs', 'name' => 'Notfall-Formularsätze (Aufnahme/Doku/Medikation)', 'description' => 'Vorgedruckte Papier-Formulare für den KIS-Ausfall: Aufnahme/ADT, Papier-Kurve, Anordnungs-/Medikationsbogen, Intensivkurve, Labor-/Transfusionsbegleitschein. In jedem Stations-Notfallordner.', 'location' => 'Notfallordner je Station/Funktionsbereich + Zentrallager Materialwirtschaft', 'access_holders' => 'Gesamtes Pflege- und ärztliches Personal', 'last_check_at' => Helpers::date(-60), 'next_check_at' => Helpers::date(120), 'notes' => 'Quartalsweise Bestands- und Aktualitätsprüfung (Formularversionen). Voraussetzung für ununterbrochene Versorgung bei KIS-Ausfall.', 'sort' => 1, 'created_at' => $ts, 'updated_at' => $ts, 'last_reminder_sent_at' => null],
                ['id' => Helpers::uuid(), 'type' => 'offline_backup', 'name' => 'Air-Gap-/Offline-Backup (immutable)', 'description' => 'Physisch vom Netz getrenntes, unveränderliches (immutable) Backup im georedundanten RZ. Wiederanlauf-Grundlage nach Ransomware, vor Verschlüsselung geschützt.', 'location' => 'Externes Backup-Rechenzentrum Nachbarstadt (Air-Gap-Tresor/Tape-Library)', 'access_holders' => 'CIO, Stv. IT-Leitung (Vier-Augen-Prinzip)', 'last_check_at' => Helpers::date(-21), 'next_check_at' => Helpers::date(70), 'notes' => 'Regelmäßige Restore-Tests sind Nachweisbestandteil § 8a BSIG. Zugriff streng protokolliert.', 'sort' => 2, 'created_at' => $ts, 'updated_at' => $ts, 'last_reminder_sent_at' => null],
                ['id' => Helpers::uuid(), 'type' => 'generator_ups', 'name' => 'Netzersatzanlage (NEA) + Diesel-Bevorratung', 'description' => 'Diesel-Netzersatzanlage mit USV-Pufferung für Sicherheitsstromversorgung (OP, Intensiv, RZ, med. Gase). Dieselvorrat für ≥ 72 h Volllast, Nachschubvertrag.', 'location' => 'Energiezentrale Hauptklinikum (NEA-Raum), Dieseltanks UG', 'access_holders' => 'Technische Leitung, NEA-Rufbereitschaft, IT (RZ-Last)', 'last_check_at' => Helpers::date(-14), 'next_check_at' => Helpers::date(16), 'notes' => 'Monatlicher Probelauf, jährlicher Schwarzstart-/Lasttest. Dieselqualität und Füllstand prüfen. NotStromV/DIN VDE 0100-710.', 'sort' => 3, 'created_at' => $ts, 'updated_at' => $ts, 'last_reminder_sent_at' => null],
                ['id' => Helpers::uuid(), 'type' => 'emergency_sim', 'name' => 'Notfall-Kommunikation (Satelliten-/Mobiltelefone)', 'description' => 'Satellitentelefone für KEL/Vorstand und Pool von Mobiltelefonen mit SIM eines zweiten Netzbetreibers für die Krisenkommunikation bei Ausfall der Haustelefonie/Internet.', 'location' => 'KEL-Raum (Tresor), IT-Leitstand', 'access_holders' => 'KEL, Vorstand, CIO, Pressestelle', 'last_check_at' => Helpers::date(-45), 'next_check_at' => Helpers::date(45), 'notes' => 'Halbjährliche Funktions-/Aktivierungsprüfung (SIM-Gültigkeit, Akku, Satellitenempfang).', 'sort' => 4, 'created_at' => $ts, 'updated_at' => $ts, 'last_reminder_sent_at' => null],
                ['id' => Helpers::uuid(), 'type' => 'password_safe', 'name' => 'Passwort-Safe / Notfall-Adminzugänge (Break-Glass)', 'description' => 'Offline gesicherter Passwort-Safe mit Notfall-Administratorzugängen (Domäne, KIS, RZ, NEA-Steuerung) für den Wiederanlauf, wenn zentrale Identitätsdienste kompromittiert/ausgefallen sind.', 'location' => 'Tresor IT-Leitstand (versiegelter Umschlag) + Backup-Tresor Vorstand', 'access_holders' => 'CIO, Stv. IT-Leitung, CISO (Vier-Augen-Prinzip, Zugriff protokolliert)', 'last_check_at' => Helpers::date(-30), 'next_check_at' => Helpers::date(60), 'notes' => 'Break-Glass-Verfahren; nach jeder Nutzung Zugänge rotieren. Bestandteil ISMS/§ 8a-Nachweis.', 'sort' => 5, 'created_at' => $ts, 'updated_at' => $ts, 'last_reminder_sent_at' => null],
            ],

            'handbook_tests' => [
                ['id' => Helpers::uuid(), 'type' => 'tabletop', 'name' => '§ 8a BSIG KRITIS-Nachweis / Audit-Vorbereitung', 'description' => 'Tabletop und Dokumentenprüfung zur Vorbereitung des Nachweises nach § 8a BSIG (alle 2 Jahre): ISMS-Reife (ISO 27001/B3S), Maßnahmenumsetzung, Mängelliste, Nachweisdokumente für die prüfende Stelle/BSI.', 'interval' => 'biannually', 'last_executed_at' => Helpers::date(-300), 'next_due_at' => Helpers::date(60), 'responsible_employee_id' => $emp['ciso'], 'result_notes' => null, 'sort' => 0, 'created_at' => $ts, 'updated_at' => $ts, 'last_reminder_sent_at' => null],
                ['id' => Helpers::uuid(), 'type' => 'communication', 'name' => 'BSI-Meldeketten-Test (§ 8b BSIG)', 'description' => 'Übung der Meldekette für erhebliche Störungen: Erstbewertung Meldepflicht durch SOC/CISO, Befüllung BSI-Meldeportal (Testfall), Erreichbarkeit Kontaktstelle, Parallel-Information Cyber-Versicherer und LfDI.', 'interval' => 'biannually', 'last_executed_at' => Helpers::date(-120), 'next_due_at' => Helpers::date(60), 'responsible_employee_id' => $emp['soc_lead'], 'result_notes' => null, 'sort' => 1, 'created_at' => $ts, 'updated_at' => $ts, 'last_reminder_sent_at' => null],
                ['id' => Helpers::uuid(), 'type' => 'recovery', 'name' => 'KIS-Wiederanlauf nach Ransomware', 'description' => 'Recovery-Übung KIS-Totalausfall: Umstellung auf Papierverfahren, forensische Freigabe, Wiederanlauf aus Air-Gap-Backup, Reihenfolge KIS → PDMS → Labor/Blutbank → OP, Nacherfassung. RTO/RPO messen.', 'interval' => 'yearly', 'last_executed_at' => Helpers::date(-200), 'next_due_at' => Helpers::date(165), 'responsible_employee_id' => $emp['cio'], 'result_notes' => null, 'sort' => 2, 'created_at' => $ts, 'updated_at' => $ts, 'last_reminder_sent_at' => null],
                ['id' => Helpers::uuid(), 'type' => 'recovery', 'name' => 'NEA-/Notstrom-Lasttest (Schwarzstart)', 'description' => 'Jährlicher Last-/Schwarzstarttest der Netzersatzanlage unter realer Last (OP/Intensiv/RZ-Schiene), USV-Pufferung und Umschaltzeiten messen, Dieselversorgung prüfen.', 'interval' => 'yearly', 'last_executed_at' => Helpers::date(-180), 'next_due_at' => Helpers::date(185), 'responsible_employee_id' => $emp['cio_stv'], 'result_notes' => null, 'sort' => 3, 'created_at' => $ts, 'updated_at' => $ts, 'last_reminder_sent_at' => null],
                ['id' => Helpers::uuid(), 'type' => 'backup_restore', 'name' => 'Restore-Test Air-Gap-Backup', 'description' => 'Wiederherstellungstest aus immutablem Air-Gap-Backup auf isolierte Recovery-Umgebung; Integrität/Konsistenz klinischer Daten validieren, Restore-Dauer dokumentieren (§ 8a-Nachweis).', 'interval' => 'quarterly', 'last_executed_at' => Helpers::date(-60), 'next_due_at' => Helpers::date(30), 'responsible_employee_id' => $emp['cio_stv'], 'result_notes' => null, 'sort' => 4, 'created_at' => $ts, 'updated_at' => $ts, 'last_reminder_sent_at' => null],
                ['id' => Helpers::uuid(), 'type' => 'contact_check', 'name' => 'Krisenstab-/KEL-Erreichbarkeit', 'description' => 'Quartalsweiser Alarmierungs-/Erreichbarkeitstest aller Krisenrollen (Vorstand, CISO, CIO, KEL, Pflegedirektion, Pressestelle) inkl. Stellvertretungen und Notfall-Kommunikationsmittel (Satellitentelefon).', 'interval' => 'quarterly', 'last_executed_at' => Helpers::date(-70), 'next_due_at' => Helpers::date(20), 'responsible_employee_id' => $emp['bcm'], 'result_notes' => null, 'sort' => 5, 'created_at' => $ts, 'updated_at' => $ts, 'last_reminder_sent_at' => null],
            ],

            'system_tasks' => [
                ['id' => Helpers::uuid(), 'system_id' => $sys['siem'], 'title' => '§ 8a-Nachweis vorbereiten', 'description' => 'Nachweisdokumente nach § 8a BSIG zusammenstellen (ISMS-Stand, Maßnahmenumsetzung, Mängelbeseitigung), prüfende Stelle terminieren.', 'due_date' => Helpers::date(40), 'completed_at' => null, 'sort' => 0, 'created_at' => $ts, 'updated_at' => $ts],
                ['id' => Helpers::uuid(), 'system_id' => $sys['netzwerk'], 'title' => 'Penetrationstest / Schwachstellenscan', 'description' => 'Externen Pentest und regelmäßigen authentifizierten Schwachstellenscan der KRITIS-Systeme beauftragen, Findings nachverfolgen.', 'due_date' => Helpers::date(75), 'completed_at' => null, 'sort' => 0, 'created_at' => $ts, 'updated_at' => $ts],
                ['id' => Helpers::uuid(), 'system_id' => $sys['nea'], 'title' => 'NEA-Lasttest / Probelauf', 'description' => 'Monatlichen Probelauf und Vorbereitung des jährlichen Schwarzstart-/Lasttests koordinieren, Dieselfüllstand/-qualität prüfen.', 'due_date' => Helpers::date(16), 'completed_at' => null, 'sort' => 0, 'created_at' => $ts, 'updated_at' => $ts],
                ['id' => Helpers::uuid(), 'system_id' => $sys['backup'], 'title' => 'Air-Gap-Backup-Restore durchführen', 'description' => 'Quartalsweisen Restore-Test aus immutablem Backup ausführen und für § 8a-Nachweis protokollieren.', 'due_date' => Helpers::date(30), 'completed_at' => null, 'sort' => 0, 'created_at' => $ts, 'updated_at' => $ts],
                ['id' => Helpers::uuid(), 'system_id' => $sys['siem'], 'title' => 'SIEM-Use-Cases / SOC-Alarmierung prüfen', 'description' => 'Detektions-Use-Cases (Angriffserkennung § 8a Abs. 1a) und Eskalations-/Alarmierungsketten mit dem SOC/MDR-Dienstleister überprüfen.', 'due_date' => Helpers::date(50), 'completed_at' => null, 'sort' => 1, 'created_at' => $ts, 'updated_at' => $ts],
                ['id' => Helpers::uuid(), 'system_id' => $sys['biomed_netz'], 'title' => 'Medizintechnik STK/MTK durchführen', 'description' => 'Sicherheits-/messtechnische Kontrollen nach MPBetreibV planen, Patch-/Firmware-Freigaben MDR-konform dokumentieren.', 'due_date' => Helpers::date(60), 'completed_at' => null, 'sort' => 0, 'created_at' => $ts, 'updated_at' => $ts],
                ['id' => Helpers::uuid(), 'system_id' => $sys['kis'], 'title' => 'Berechtigungs-Review KIS', 'description' => 'Rezertifizierung der Zugriffsrechte im KIS (Rollenkonzept, verwaiste Konten, privilegierte Zugänge) nach ISMS-Vorgabe.', 'due_date' => Helpers::date(45), 'completed_at' => null, 'sort' => 0, 'created_at' => $ts, 'updated_at' => $ts],
                ['id' => Helpers::uuid(), 'system_id' => $sys['kis'], 'title' => 'Notfall-Awareness Personal', 'description' => 'Schulung Stations-/OP-/Intensivpersonal zum KIS-Ausfall-Verfahren und Phishing-Awareness (Patientendaten), Teilnahme dokumentieren.', 'due_date' => Helpers::date(90), 'completed_at' => null, 'sort' => 1, 'created_at' => $ts, 'updated_at' => $ts],
            ],
        ]);
    }
}
