<?php

namespace Database\Seeders\IndustryTemplates;

use App\Enums\Industry;

class SeniorenzentrumTemplate implements Contract
{
    public function name(): string
    {
        return 'Seniorenzentrum / Pflegeheim (80–120 Plätze, stationär)';
    }

    public function industry(): Industry
    {
        return Industry::Dienstleistung;
    }

    public function description(): string
    {
        return 'Stationäres Seniorenzentrum mit rund 100 Pflegeplätzen, vier Wohnbereichen und 24/7-Versorgung pflegebedürftiger Bewohner. Schwerpunkte: Schwesternruf-/Lichtrufanlage (lebenskritisch), elektronische Pflegedokumentation, Medikamenten-Stellsoftware mit Kühlkette, Heimrecht/WTG-Landesheimgesetz, IfSG-Hygiene (§ 23/§ 36, Ausbruchsmeldung Gesundheitsamt), MD-Qualitätsprüfung, Art. 9 DSGVO (Gesundheitsdaten), Brandschutz- und Evakuierungskonzept. Enthält: 13 Mitarbeiter, 1 Standort, 14 Systeme inkl. sehr niedrige RTO für Schwesternruf, Notstrom und Heizung/Warmwasser, 8 Dienstleister, 4 Versicherungen, 6 Kommunikationsvorlagen, 6 Notfall-Ressourcen, 5 Testpläne, system_tasks.';
    }

    public function sort(): int
    {
        return 91;
    }

    public function payload(): array
    {
        // Stable IDs, damit FK-Verweise innerhalb des Payloads konsistent
        // bleiben. Beim Apply werden sie via regenerateIds neu gemappt.
        $haus = Helpers::uuid();

        $emp = [
            'heimleitung' => Helpers::uuid(),
            'pdl' => Helpers::uuid(),
            'pdl_stv' => Helpers::uuid(),
            'qmb' => Helpers::uuid(),
            'hygiene' => Helpers::uuid(),
            'haustechnik' => Helpers::uuid(),
            'verwaltung' => Helpers::uuid(),
            'wbl_1' => Helpers::uuid(),
            'wbl_2' => Helpers::uuid(),
            'pflege_1' => Helpers::uuid(),
            'pflege_2' => Helpers::uuid(),
            'kueche' => Helpers::uuid(),
            'dsb' => Helpers::uuid(),
        ];

        $prov = [
            'software' => Helpers::uuid(),
            'schwesternruf' => Helpers::uuid(),
            'notstrom' => Helpers::uuid(),
            'brandmelde' => Helpers::uuid(),
            'aufzug' => Helpers::uuid(),
            'it' => Helpers::uuid(),
            'gesundheitsamt' => Helpers::uuid(),
            'lfdi' => Helpers::uuid(),
        ];

        $sys = [
            'schwesternruf' => Helpers::uuid(),
            'pflegedoku' => Helpers::uuid(),
            'medikamente' => Helpers::uuid(),
            'kuehlkette' => Helpers::uuid(),
            'dienstplan' => Helpers::uuid(),
            'heimverwaltung' => Helpers::uuid(),
            'telefon' => Helpers::uuid(),
            'notstrom' => Helpers::uuid(),
            'heizung' => Helpers::uuid(),
            'brandmelde' => Helpers::uuid(),
            'aufzug' => Helpers::uuid(),
            'medizingeraete' => Helpers::uuid(),
            'internet' => Helpers::uuid(),
            'mail' => Helpers::uuid(),
            'kueche' => Helpers::uuid(),
            'waescherei' => Helpers::uuid(),
            'strom' => Helpers::uuid(),
        ];

        $ts = Helpers::now();

        return Helpers::payload([
            'company' => [[
                'name' => 'Seniorenzentrum Sonnenhof gGmbH',
                'industry' => 'dienstleistung',
                'employee_count' => 95,
                'review_cycle_months' => 12,
                'legal_form' => 'gmbh',
                'kritis_relevant' => 'no',
                'nis2_classification' => 'not_affected',
                'cyber_insurance_deductible' => '5.000 €',
                'budget_it_lead' => 1000,
                'budget_emergency_officer' => 5000,
                'budget_management' => 40000,
                'data_protection_authority_name' => 'LfDI Baden-Württemberg',
                'data_protection_authority_phone' => '0711 615541-0',
                'data_protection_authority_website' => 'https://www.baden-wuerttemberg.datenschutz.de',
            ]],

            'locations' => [
                [
                    'id' => $haus, 'name' => 'Seniorenzentrum Sonnenhof (Haupthaus)', 'street' => 'Lindenallee 24',
                    'postal_code' => '74072', 'city' => 'Heilbronn', 'country' => 'DE',
                    'is_headquarters' => 1, 'phone' => '07131 666 0',
                    'notes' => 'Pflegeheim-Gebäude mit ca. 100 vollstationären Plätzen, 4 Wohnbereiche/Pflegestationen über 3 Etagen, beschützender Demenzbereich im EG. 24/7-Versorgung. Großküche, Wäscherei und Haustechnik im UG. Einrichtung nach Landesheimgesetz/WTG zugelassen, MD-geprüft.',
                    'sort' => 0, 'created_at' => $ts, 'updated_at' => $ts,
                ],
            ],

            'employees' => [
                ['id' => $emp['heimleitung'], 'first_name' => 'Andrea', 'last_name' => 'Sonnberg', 'position' => 'Heimleitung / Einrichtungsleitung', 'department' => 'Leitung', 'work_phone' => '07131 666 100', 'mobile_phone' => '0172 6660001', 'private_phone' => '07131 887700', 'email' => 'a.sonnberg@sonnenhof-pflege.de', 'emergency_contact' => null, 'manager_id' => null, 'is_key_personnel' => 1, 'crisis_role' => 'management', 'is_crisis_deputy' => 0, 'notes' => 'Verantwortliche Einrichtungsleitung nach Landesheimgesetz/WTG. Gesamtverantwortung, Ansprechpartnerin Heimaufsicht.', 'location_id' => $haus, 'created_at' => $ts, 'updated_at' => $ts],
                ['id' => $emp['pdl'], 'first_name' => 'Thomas', 'last_name' => 'Reinhardt', 'position' => 'Pflegedienstleitung (PDL)', 'department' => 'Pflege', 'work_phone' => '07131 666 110', 'mobile_phone' => '0172 6660002', 'private_phone' => null, 'email' => 't.reinhardt@sonnenhof-pflege.de', 'emergency_contact' => null, 'manager_id' => $emp['heimleitung'], 'is_key_personnel' => 1, 'crisis_role' => 'emergency_officer', 'is_crisis_deputy' => 0, 'notes' => 'PDL nach SGB XI § 71. Notfallbeauftragter, Rufbereitschaft. Verantwortlich für Pflegequalität und MD-Prüfung.', 'location_id' => $haus, 'created_at' => $ts, 'updated_at' => $ts],
                ['id' => $emp['pdl_stv'], 'first_name' => 'Sabine', 'last_name' => 'Vogt', 'position' => 'Stellv. Pflegedienstleitung', 'department' => 'Pflege', 'work_phone' => '07131 666 111', 'mobile_phone' => '0172 6660003', 'private_phone' => null, 'email' => 's.vogt@sonnenhof-pflege.de', 'emergency_contact' => null, 'manager_id' => $emp['pdl'], 'is_key_personnel' => 1, 'crisis_role' => 'emergency_officer', 'is_crisis_deputy' => 1, 'notes' => 'Vertretung PDL/Notfallbeauftragte bei Urlaub/Krankheit, Mit-Rufbereitschaft.', 'location_id' => $haus, 'created_at' => $ts, 'updated_at' => $ts],
                ['id' => $emp['qmb'], 'first_name' => 'Petra', 'last_name' => 'Dietrich', 'position' => 'Qualitätsmanagementbeauftragte (QMB)', 'department' => 'Qualität', 'work_phone' => '07131 666 120', 'mobile_phone' => '0172 6660010', 'private_phone' => null, 'email' => 'p.dietrich@sonnenhof-pflege.de', 'emergency_contact' => null, 'manager_id' => $emp['heimleitung'], 'is_key_personnel' => 1, 'crisis_role' => null, 'is_crisis_deputy' => 0, 'notes' => 'QM nach MD-Qualitätsprüfung (QPR), Dokumentationsqualität, Beschwerdemanagement, Brandschutzordnung.', 'location_id' => $haus, 'created_at' => $ts, 'updated_at' => $ts],
                ['id' => $emp['hygiene'], 'first_name' => 'Markus', 'last_name' => 'Brenner', 'position' => 'Hygienebeauftragter (Pflegefachkraft)', 'department' => 'Pflege', 'work_phone' => '07131 666 121', 'mobile_phone' => '0172 6660011', 'private_phone' => null, 'email' => 'm.brenner@sonnenhof-pflege.de', 'emergency_contact' => null, 'manager_id' => $emp['pdl'], 'is_key_personnel' => 1, 'crisis_role' => null, 'is_crisis_deputy' => 0, 'notes' => 'Hygienebeauftragter nach IfSG § 23, Hygieneplan, Ausbruchsmanagement (Noro/Influenza), Meldung Gesundheitsamt nach § 36 IfSG.', 'location_id' => $haus, 'created_at' => $ts, 'updated_at' => $ts],
                ['id' => $emp['haustechnik'], 'first_name' => 'Jürgen', 'last_name' => 'Stahl', 'position' => 'Leiter Haustechnik / IT-Koordination', 'department' => 'Haustechnik', 'work_phone' => '07131 666 130', 'mobile_phone' => '0172 6660020', 'private_phone' => null, 'email' => 'j.stahl@sonnenhof-pflege.de', 'emergency_contact' => null, 'manager_id' => $emp['heimleitung'], 'is_key_personnel' => 1, 'crisis_role' => 'it_lead', 'is_crisis_deputy' => 0, 'notes' => 'Haustechnik (Notstrom, Heizung, Aufzüge, Brandmeldeanlage) und IT-Schnittstelle zum MSP. Verantwortlich für Schwesternruf-Wartung.', 'location_id' => $haus, 'created_at' => $ts, 'updated_at' => $ts],
                ['id' => $emp['verwaltung'], 'first_name' => 'Claudia', 'last_name' => 'Hartmann', 'position' => 'Verwaltungsleitung / Kommunikation', 'department' => 'Verwaltung', 'work_phone' => '07131 666 140', 'mobile_phone' => '0172 6660030', 'private_phone' => null, 'email' => 'c.hartmann@sonnenhof-pflege.de', 'emergency_contact' => null, 'manager_id' => $emp['heimleitung'], 'is_key_personnel' => 1, 'crisis_role' => 'communications_lead', 'is_crisis_deputy' => 0, 'notes' => 'Heimverwaltung, Bewohnerabrechnung, Angehörigen- und Behördenkommunikation (Heimaufsicht, Pflegekassen).', 'location_id' => $haus, 'created_at' => $ts, 'updated_at' => $ts],
                ['id' => $emp['wbl_1'], 'first_name' => 'Birgit', 'last_name' => 'Lang', 'position' => 'Wohnbereichsleitung WB 1+2', 'department' => 'Pflege', 'work_phone' => '07131 666 150', 'mobile_phone' => '0172 6660040', 'private_phone' => null, 'email' => 'b.lang@sonnenhof-pflege.de', 'emergency_contact' => null, 'manager_id' => $emp['pdl'], 'is_key_personnel' => 1, 'crisis_role' => null, 'is_crisis_deputy' => 1, 'notes' => 'Leitung Wohnbereiche 1+2 (EG/1.OG), Schichtkoordination, Vertretung im Krisenstab.', 'location_id' => $haus, 'created_at' => $ts, 'updated_at' => $ts],
                ['id' => $emp['wbl_2'], 'first_name' => 'Frank', 'last_name' => 'Berger', 'position' => 'Wohnbereichsleitung WB 3+4', 'department' => 'Pflege', 'work_phone' => '07131 666 151', 'mobile_phone' => '0172 6660041', 'private_phone' => null, 'email' => 'f.berger@sonnenhof-pflege.de', 'emergency_contact' => null, 'manager_id' => $emp['pdl'], 'is_key_personnel' => 1, 'crisis_role' => null, 'is_crisis_deputy' => 0, 'notes' => 'Leitung Wohnbereiche 3+4 inkl. beschützender Demenzbereich, Evakuierungs-/Räumungskoordination.', 'location_id' => $haus, 'created_at' => $ts, 'updated_at' => $ts],
                ['id' => $emp['pflege_1'], 'first_name' => 'Nadine', 'last_name' => 'Wolf', 'position' => 'Pflegefachkraft / Schichtleitung Nachtdienst', 'department' => 'Pflege', 'work_phone' => null, 'mobile_phone' => '0172 6660050', 'private_phone' => null, 'email' => 'n.wolf@sonnenhof-pflege.de', 'emergency_contact' => null, 'manager_id' => $emp['wbl_1'], 'is_key_personnel' => 1, 'crisis_role' => null, 'is_crisis_deputy' => 0, 'notes' => 'Verantwortliche Pflegefachkraft Nachtdienst (24/7-Besetzung), erste Reaktion bei Schwesternruf-Ausfall.', 'location_id' => $haus, 'created_at' => $ts, 'updated_at' => $ts],
                ['id' => $emp['pflege_2'], 'first_name' => 'Ayse', 'last_name' => 'Yilmaz', 'position' => 'Pflegefachkraft', 'department' => 'Pflege', 'work_phone' => null, 'mobile_phone' => '0172 6660051', 'private_phone' => null, 'email' => 'a.yilmaz@sonnenhof-pflege.de', 'emergency_contact' => null, 'manager_id' => $emp['wbl_2'], 'is_key_personnel' => 0, 'crisis_role' => null, 'is_crisis_deputy' => 0, 'notes' => 'Medikamentenmanagement, Stellkontrolle, Kühlketten-Überwachung Wohnbereich.', 'location_id' => $haus, 'created_at' => $ts, 'updated_at' => $ts],
                ['id' => $emp['kueche'], 'first_name' => 'Rainer', 'last_name' => 'Fuchs', 'position' => 'Küchenleitung (Großküche/HACCP)', 'department' => 'Hauswirtschaft', 'work_phone' => '07131 666 160', 'mobile_phone' => '0172 6660060', 'private_phone' => null, 'email' => 'r.fuchs@sonnenhof-pflege.de', 'emergency_contact' => null, 'manager_id' => $emp['heimleitung'], 'is_key_personnel' => 0, 'crisis_role' => null, 'is_crisis_deputy' => 0, 'notes' => 'Großküche mit HACCP-Konzept, Verpflegung ca. 100 Bewohner + Diätkost, Kühlketten-Doku Lebensmittel.', 'location_id' => $haus, 'created_at' => $ts, 'updated_at' => $ts],
                ['id' => $emp['dsb'], 'first_name' => 'Klaus', 'last_name' => 'Engel', 'position' => 'Datenschutzbeauftragter (extern)', 'department' => 'Compliance', 'work_phone' => null, 'mobile_phone' => '0172 6660070', 'private_phone' => null, 'email' => 'engel@datenschutz-extern.example', 'emergency_contact' => null, 'manager_id' => null, 'is_key_personnel' => 1, 'crisis_role' => 'dpo', 'is_crisis_deputy' => 0, 'notes' => 'Externer DSB. Bei Datenpanne sofort Kontakt — Bewohnerdaten besonders sensibel (Gesundheitsdaten Art. 9 DSGVO, Diagnosen/Medikation).', 'location_id' => null, 'created_at' => $ts, 'updated_at' => $ts],
            ],

            'service_providers' => [
                ['id' => $prov['software'], 'name' => 'Connext Vivendi / MEDIFOX DAN (Heim-Software)', 'type' => 'other', 'contact_name' => 'Support-Hotline', 'hotline' => '05251 7711 0', 'email' => 'support@vivendi.example', 'contract_number' => 'KD-SZ-2026-771', 'sla' => '24/7 für Notfälle (P1), sonst Mo-Fr 7-19', 'notes' => 'Hersteller Pflegedoku + Heimverwaltung + Medikamentenmodul. KRITISCH: bei Ausfall stehen Pflegedoku und Stellsoftware. 24/7-Hotline vertraglich zugesichert.', 'direct_order_limit' => 4000, 'created_at' => $ts, 'updated_at' => $ts],
                ['id' => $prov['schwesternruf'], 'name' => 'RUF Notrufsysteme GmbH (Schwesternruf/Lichtruf)', 'type' => 'other', 'contact_name' => 'Service-Notdienst', 'hotline' => '0800 7838000', 'email' => 'service@ruf-notruf.example', 'contract_number' => 'WV-SZ-2025-441', 'sla' => '24/7 Notdienst, Reaktion < 4 Std', 'notes' => 'Wartung und Notdienst Schwesternruf-/Lichtrufanlage. LEBENSKRITISCH — Vollwartungsvertrag mit 24/7-Reaktion. DGUV-/DIN-VDE-0834-Prüfpflicht.', 'direct_order_limit' => 6000, 'created_at' => $ts, 'updated_at' => $ts],
                ['id' => $prov['notstrom'], 'name' => 'EnergieTechnik Süd GmbH (Notstrom/USV)', 'type' => 'utility', 'contact_name' => 'Hr. Kaiser', 'hotline' => '0711 4040 900', 'email' => 'service@energietechnik-sued.example', 'contract_number' => 'NSA-SZ-2025', 'sla' => '24/7 Notdienst', 'notes' => 'Wartung Notstromaggregat (Diesel) + USV-Anlagen. Pflichtprüfung und Lastlauf. Versorgt Schwesternruf, Heizung, kritische IT.', 'direct_order_limit' => 5000, 'created_at' => $ts, 'updated_at' => $ts],
                ['id' => $prov['brandmelde'], 'name' => 'BrandSchutz Müller GmbH (BMA/Sprinkler)', 'type' => 'other', 'contact_name' => 'Hr. Müller', 'hotline' => '07131 998822', 'email' => 'service@brandschutz-mueller.example', 'contract_number' => 'BMA-SZ-2024', 'sla' => 'Mo-Fr 7-18, Notdienst 24/7', 'notes' => 'Wartung Brandmeldeanlage mit Aufschaltung zur Feuerwehr. Brandschutzordnung, Räumungskonzept, jährliche Prüfung nach DIN 14675.', 'direct_order_limit' => 4000, 'created_at' => $ts, 'updated_at' => $ts],
                ['id' => $prov['aufzug'], 'name' => 'OTIS Aufzüge (Wartung)', 'type' => 'other', 'contact_name' => 'Service-Center', 'hotline' => '0800 1234567', 'email' => 'service@otis.example', 'contract_number' => 'AUF-SZ-2024', 'sla' => '24/7 Befreiungsdienst', 'notes' => 'Wartung 2 Bettenaufzüge. Personenbefreiung 24/7 — kritisch für Bewohnertransport und Evakuierung. TÜV-Prüfung jährlich.', 'direct_order_limit' => null, 'created_at' => $ts, 'updated_at' => $ts],
                ['id' => $prov['it'], 'name' => 'GesundheitsIT Süd GmbH (MSP)', 'type' => 'it_msp', 'contact_name' => 'Hr. Wolf', 'hotline' => '0711 4455 800', 'email' => 'noc@gesundheits-it.example', 'contract_number' => 'MSP-SZ-2026', 'sla' => 'Mo-Fr 7-19, Notfall 24/7 mit Aufpreis', 'notes' => 'IT-MSP spezialisiert auf Pflege/Heilberufe (DSGVO Art. 9). Betreut Server, Netzwerk, M365, Backup der Pflegedoku.', 'direct_order_limit' => 4000, 'created_at' => $ts, 'updated_at' => $ts],
                ['id' => $prov['gesundheitsamt'], 'name' => 'Gesundheitsamt Landkreis Heilbronn', 'type' => 'other', 'contact_name' => 'Infektionsschutz', 'hotline' => '07131 994 400', 'email' => 'gesundheitsamt@landkreis-heilbronn.example', 'contract_number' => null, 'sla' => 'Mo-Fr 8-16, Bereitschaft bei Ausbruch', 'notes' => 'Meldebehörde nach IfSG § 6/§ 36. Ausbruchsmeldung (Noro, Influenza, COVID) unverzüglich. Begehungen Hygiene.', 'direct_order_limit' => null, 'created_at' => $ts, 'updated_at' => $ts],
                ['id' => $prov['lfdi'], 'name' => 'LfDI Baden-Württemberg', 'type' => 'data_protection_authority', 'contact_name' => 'Beschwerdestelle', 'hotline' => '0711 615541-0', 'email' => 'poststelle@lfdi.bwl.de', 'contract_number' => null, 'sla' => 'Mo-Fr 8-16', 'notes' => 'Aufsichtsbehörde für DSGVO Art. 33-Meldungen. Bewohnerdaten (Diagnosen/Medikation) = besondere Kategorie Art. 9.', 'direct_order_limit' => null, 'created_at' => $ts, 'updated_at' => $ts],
            ],

            'systems' => [
                ['id' => $sys['schwesternruf'], 'name' => 'Schwesternruf-/Lichtrufanlage (24/7)', 'description' => 'Stationäre Lichtruf-/Schwesternrufanlage in allen Bewohnerzimmern, Bädern und Fluren. Bewohner lösen Hilferuf aus, Signalisierung an Dienstzimmer und Pflegekräfte-Pager. LEBENSKRITISCH nach DIN VDE 0834.', 'category' => 'basisbetrieb', 'rto_minutes' => 10, 'rpo_minutes' => null, 'downtime_cost_per_hour' => 1000, 'fallback_process' => 'SOFORT: Verstärkte Sicht-Rundgänge in allen Wohnbereichen (alle 15–30 Min, risikoorientiert), zusätzliche Pflegekraft pro WB einteilen. Mobile Notruf-Klingeln/Handglocken aus Notfallschrank an gefährdete Bewohner verteilen. Service-Notdienst RUF (0800 7838000) sofort anrufen. Heimleitung + PDL informieren.', 'runbook_reference' => 'Runbook „Schwesternruf-Ausfall — höchste Priorität" v1.3', 'system_priority_id' => null, 'emergency_level_id' => null, 'created_at' => $ts, 'updated_at' => $ts],
                ['id' => $sys['pflegedoku'], 'name' => 'Elektronische Pflegedokumentation (Vivendi)', 'description' => 'Gesetzlich vorgeschriebene Pflegedoku (SGB XI), Pflegeplanung, Vitalwerte, Wunddoku, Sturzprotokoll. Haftungs- und abrechnungsrelevant, Grundlage MD-Qualitätsprüfung. Server vor Ort + Cloud-Backup.', 'category' => 'geschaeftsbetrieb', 'rto_minutes' => 120, 'rpo_minutes' => 60, 'downtime_cost_per_hour' => 800, 'fallback_process' => 'Sofort-Umstellung auf Papier-Pflegedoku (Vordrucke je Wohnbereich). Vitalwerte/Medikamentengabe/Lagerung lückenlos handschriftlich. Nach Wiederanlauf vollständige Übertragung in Software — Dokumentationspflicht wahren!', 'runbook_reference' => 'Runbook „Pflegedoku-Ausfall (gesetzlich)" v1.2', 'system_priority_id' => null, 'emergency_level_id' => null, 'created_at' => $ts, 'updated_at' => $ts],
                ['id' => $sys['medikamente'], 'name' => 'Medikamenten-/Stellsoftware', 'description' => 'Software für Medikationsplan, Stellkontrolle, Betäubungsmittel-Doku (BtM), Blisterversorgung Apotheke. Verknüpft mit Pflegedoku.', 'category' => 'geschaeftsbetrieb', 'rto_minutes' => 120, 'rpo_minutes' => 60, 'downtime_cost_per_hour' => 600, 'fallback_process' => 'Aktuellen Medikationsplan jeder Bewohner liegt als Tagesausdruck im Wohnbereich. Stellen nach Papierplan + Vier-Augen-Prinzip. BtM-Buch handschriftlich führen. Apotheke telefonisch erreichbar halten.', 'runbook_reference' => 'Runbook „Medikamenten-Software-Ausfall" v1.1', 'system_priority_id' => null, 'emergency_level_id' => null, 'created_at' => $ts, 'updated_at' => $ts],
                ['id' => $sys['kuehlkette'], 'name' => 'Medikamenten-Kühlschrank / Kühlkette', 'description' => 'Kühlschränke für kühlpflichtige Medikamente (Insulin, Impfstoffe) mit Temperaturlogger 2–8 °C. Hygiene-/Arzneimittelrecht.', 'category' => 'basisbetrieb', 'rto_minutes' => 60, 'rpo_minutes' => null, 'downtime_cost_per_hour' => 300, 'fallback_process' => 'Bei Stromausfall/Defekt: Medikamente in Kühlbox mit Kühlakkus umlagern (Notfallschrank). Temperatur stündlich messen + protokollieren. Apotheke + Hausarzt informieren. Notstrom versorgt Kühlschränke priorisiert.', 'runbook_reference' => 'Runbook „Kühlkette-Ausfall" v1.0', 'system_priority_id' => null, 'emergency_level_id' => null, 'created_at' => $ts, 'updated_at' => $ts],
                ['id' => $sys['dienstplan'], 'name' => 'Dienstplan-Software', 'description' => 'Schichtplanung, Arbeitszeiterfassung, Ausfallmanagement. Sicherstellung Fachkraftquote und Nachtdienstbesetzung (Heimpersonalverordnung).', 'category' => 'geschaeftsbetrieb', 'rto_minutes' => 480, 'rpo_minutes' => 1440, 'downtime_cost_per_hour' => 80, 'fallback_process' => 'Dienstplan der laufenden + nächsten Woche wird wöchentlich gedruckt (Pflegebüro). Änderungen handschriftlich, Nacherfassung nach Wiederanlauf.', 'runbook_reference' => null, 'system_priority_id' => null, 'emergency_level_id' => null, 'created_at' => $ts, 'updated_at' => $ts],
                ['id' => $sys['heimverwaltung'], 'name' => 'Heimverwaltung / Bewohnerabrechnung', 'description' => 'Bewohnerstammdaten, Heimkostenabrechnung, Pflegekassen-/Sozialamts-Abrechnung, Belegungsmanagement.', 'category' => 'geschaeftsbetrieb', 'rto_minutes' => 1440, 'rpo_minutes' => 1440, 'downtime_cost_per_hour' => 100, 'fallback_process' => 'Abrechnungslauf um 1–3 Tage verschieben (kein direkter Bewohnerschaden). Stammdaten als Notfall-Bewohnerliste auf Papier vorhanden. Liquiditätsplan bei längerem Ausfall.', 'runbook_reference' => null, 'system_priority_id' => null, 'emergency_level_id' => null, 'created_at' => $ts, 'updated_at' => $ts],
                ['id' => $sys['telefon'], 'name' => 'Telefon / Hausnotruf-Zentrale (24/7)', 'description' => 'TK-Anlage mit zentraler Rufnummer, Dienstzimmer-Telefone, externer Hausnotruf-/Bereitschaftskontakt. 24/7-Erreichbarkeit für Angehörige, Ärzte, Rettungsdienst.', 'category' => 'basisbetrieb', 'rto_minutes' => 30, 'rpo_minutes' => null, 'downtime_cost_per_hour' => 250, 'fallback_process' => 'Eingehende Anrufe auf Bereitschafts-Mobil PDL (0172 6660002) umleiten. Notfall-Mobiltelefone (anderer Provider) an Dienstzimmer verteilen. Rettungsdienst/112 funktioniert über Mobilnetz unabhängig.', 'runbook_reference' => 'Runbook „Telefon-Ausfall" v1.1', 'system_priority_id' => null, 'emergency_level_id' => null, 'created_at' => $ts, 'updated_at' => $ts],
                ['id' => $sys['notstrom'], 'name' => 'Notstromaggregat + USV', 'description' => 'Diesel-Notstromaggregat (Netzersatzanlage) + USV-Anlagen. Versorgt priorisiert Schwesternruf, Brandmeldeanlage, kritische Medizingeräte, Kühlkette, IT-Server und Teile der Beleuchtung.', 'category' => 'basisbetrieb', 'rto_minutes' => 15, 'rpo_minutes' => null, 'downtime_cost_per_hour' => 800, 'fallback_process' => 'NEA startet bei Netzausfall automatisch (< 1 Min). USV überbrückt die Umschaltzeit. Bei NEA-Defekt: EnergieTechnik Süd 24/7-Notdienst + ggf. mobiles Mietaggregat. Tankvorrat für 24h vorhalten.', 'runbook_reference' => 'Runbook „Stromausfall / Notstrom" v1.2', 'system_priority_id' => null, 'emergency_level_id' => null, 'created_at' => $ts, 'updated_at' => $ts],
                ['id' => $sys['heizung'], 'name' => 'Heizung / Warmwasser', 'description' => 'Zentrale Heizungs- und Warmwasserversorgung (Gas-Brennwert). Warmwasser mit Legionellen-Schutz (TrinkwV). Wärme für pflegebedürftige Bewohner essenziell.', 'category' => 'basisbetrieb', 'rto_minutes' => 240, 'rpo_minutes' => null, 'downtime_cost_per_hour' => 200, 'fallback_process' => 'Haustechnik prüft Anlage; Heizungsnotdienst rufen. Bei längerem Ausfall im Winter: mobile Heizgeräte (Notstrom-abgesichert) in Bewohnerzimmer, zusätzliche Decken, ggf. Verlegung gefährdeter Bewohner. Warmwasser über Boiler.', 'runbook_reference' => null, 'system_priority_id' => null, 'emergency_level_id' => null, 'created_at' => $ts, 'updated_at' => $ts],
                ['id' => $sys['brandmelde'], 'name' => 'Brandmeldeanlage (BMA)', 'description' => 'Flächendeckende Brandmeldeanlage mit Aufschaltung zur Feuerwehr, Rauchmelder, Handfeuermelder. Teil des Brandschutz- und Evakuierungskonzepts (Räumungsplan).', 'category' => 'basisbetrieb', 'rto_minutes' => 30, 'rpo_minutes' => null, 'downtime_cost_per_hour' => 500, 'fallback_process' => 'Bei BMA-Störung: Brandsicherheitswache organisieren (verstärkte Rundgänge), Feuerwehr informieren, BrandSchutz Müller 24/7-Notdienst. Räumungsplan und Handfeuermelder-Standorte bekannt halten.', 'runbook_reference' => 'Runbook „BMA-Störung / Brandsicherheitswache" v1.1', 'system_priority_id' => null, 'emergency_level_id' => null, 'created_at' => $ts, 'updated_at' => $ts],
                ['id' => $sys['aufzug'], 'name' => 'Bettenaufzüge (2 Stück)', 'description' => '2 Bettenaufzüge für Bewohner-, Essens- und Wäschetransport über 3 Etagen. Kritisch für Pflegeabläufe und Evakuierung (Feuerwehraufzug).', 'category' => 'geschaeftsbetrieb', 'rto_minutes' => 240, 'rpo_minutes' => null, 'downtime_cost_per_hour' => 150, 'fallback_process' => 'Bei Steckenbleiben: OTIS Befreiungsdienst 24/7 (0800 1234567) + 112 falls Person betroffen. Bei Ausfall beider Aufzüge: Tragehilfen/Treppensteiger organisieren, Essensausgabe etagenweise umorganisieren.', 'runbook_reference' => null, 'system_priority_id' => null, 'emergency_level_id' => null, 'created_at' => $ts, 'updated_at' => $ts],
                ['id' => $sys['medizingeraete'], 'name' => 'Pflegebetten / Medizingeräte', 'description' => 'Elektrische Pflegebetten, Lifter, Absauggeräte, Sauerstoffkonzentratoren, Blutzucker-/Vitalmessgeräte. MPG/MPDG-konform, Medizinprodukte-Bestandsverzeichnis.', 'category' => 'geschaeftsbetrieb', 'rto_minutes' => 240, 'rpo_minutes' => null, 'downtime_cost_per_hour' => 200, 'fallback_process' => 'Defekte Geräte aus Reservepool ersetzen. Pflegebetten manuell verstellbar nutzen. Sauerstoffkonzentratoren über Notstrom; Notfall-Sauerstoffflaschen als Backup. STK/MTK-Wartung nach MPBetreibV.', 'runbook_reference' => null, 'system_priority_id' => null, 'emergency_level_id' => null, 'created_at' => $ts, 'updated_at' => $ts],
                ['id' => $sys['internet'], 'name' => 'Internet-Anbindung / WLAN', 'description' => 'Glasfaser/VDSL Geschäftskunde + LTE-Backup. WLAN für mobile Pflege-Doku, Bewohner-WLAN getrennt.', 'category' => 'basisbetrieb', 'rto_minutes' => 120, 'rpo_minutes' => null, 'downtime_cost_per_hour' => 200, 'fallback_process' => 'LTE-Failover automatisch. Pflegedoku-Server arbeitet lokal weiter (Cloud-Sync später). Cloud-Dienste (M365) über LTE oder mobil.', 'runbook_reference' => null, 'system_priority_id' => null, 'emergency_level_id' => null, 'created_at' => $ts, 'updated_at' => $ts],
                ['id' => $sys['mail'], 'name' => 'E-Mail (Microsoft 365)', 'description' => 'M365 Business Standard für Verwaltung, Heimaufsicht-/Behördenkommunikation, Hausärzte, Angehörige.', 'category' => 'geschaeftsbetrieb', 'rto_minutes' => 240, 'rpo_minutes' => 60, 'downtime_cost_per_hour' => 100, 'fallback_process' => 'M365-Webmail mobil; bei Total-Ausfall Telefon + Fax als Übergang für Behörden.', 'runbook_reference' => null, 'system_priority_id' => null, 'emergency_level_id' => null, 'created_at' => $ts, 'updated_at' => $ts],
                ['id' => $sys['kueche'], 'name' => 'Großküche / HACCP-Dokumentation', 'description' => 'Großküche mit Kühl-/Tiefkühlhaus, HACCP-Eigenkontrolle, Temperaturdoku, Diät-/Kostformenverwaltung für ca. 100 Bewohner.', 'category' => 'geschaeftsbetrieb', 'rto_minutes' => 240, 'rpo_minutes' => null, 'downtime_cost_per_hour' => 200, 'fallback_process' => 'Bei Küchenausfall: Notverpflegung über externen Caterer/benachbarte Einrichtung. Kühlware in Notstrom-gesicherte Kühlräume. HACCP-Doku übergangsweise auf Papier. Diätkost priorisiert sicherstellen.', 'runbook_reference' => null, 'system_priority_id' => null, 'emergency_level_id' => null, 'created_at' => $ts, 'updated_at' => $ts],
                ['id' => $sys['waescherei'], 'name' => 'Wäscherei', 'description' => 'Hauseigene Wäscherei für Bewohner- und Berufskleidung, Bettwäsche. Hygienisch sensibel (RKI-Anforderungen, Infektionswäsche getrennt).', 'category' => 'unterstuetzend', 'rto_minutes' => 1440, 'rpo_minutes' => null, 'downtime_cost_per_hour' => 60, 'fallback_process' => 'Bei Ausfall: externer Wäscherei-Dienstleister beauftragen. Frischwäsche-Notvorrat (mind. 3 Tage) im Lager. Infektionswäsche gesondert sammeln.', 'runbook_reference' => null, 'system_priority_id' => null, 'emergency_level_id' => null, 'created_at' => $ts, 'updated_at' => $ts],
                ['id' => $sys['strom'], 'name' => 'Stromversorgung (Hausanschluss)', 'description' => 'Mittelspannungs-/Niederspannungs-Hausanschluss. Basis für alle elektrischen Systeme; bei Ausfall greift das Notstromaggregat.', 'category' => 'basisbetrieb', 'rto_minutes' => 30, 'rpo_minutes' => null, 'downtime_cost_per_hour' => 600, 'fallback_process' => 'Bei Netzausfall startet das Notstromaggregat automatisch und versorgt priorisierte Verbraucher (Schwesternruf, BMA, Kühlkette, IT, Notbeleuchtung). Netzbetreiber-Störungsnummer informieren.', 'runbook_reference' => 'Runbook „Stromausfall / Notstrom" v1.2', 'system_priority_id' => null, 'emergency_level_id' => null, 'created_at' => $ts, 'updated_at' => $ts],
            ],

            'system_dependencies' => [
                ['system_id' => $sys['schwesternruf'], 'depends_on_system_id' => $sys['strom'], 'sort' => 0, 'note' => 'Notstrom-priorisiert. Bei Ausfall sofort Sicht-Rundgänge!', 'created_at' => $ts, 'updated_at' => $ts],
                ['system_id' => $sys['brandmelde'], 'depends_on_system_id' => $sys['strom'], 'sort' => 0, 'note' => 'Notstrom-priorisiert.', 'created_at' => $ts, 'updated_at' => $ts],
                ['system_id' => $sys['kuehlkette'], 'depends_on_system_id' => $sys['strom'], 'sort' => 0, 'note' => 'Notstrom-priorisiert für kühlpflichtige Medikamente.', 'created_at' => $ts, 'updated_at' => $ts],
                ['system_id' => $sys['heizung'], 'depends_on_system_id' => $sys['strom'], 'sort' => 0, 'note' => 'Steuerung/Pumpen stromabhängig.', 'created_at' => $ts, 'updated_at' => $ts],
                ['system_id' => $sys['aufzug'], 'depends_on_system_id' => $sys['strom'], 'sort' => 0, 'note' => null, 'created_at' => $ts, 'updated_at' => $ts],
                ['system_id' => $sys['telefon'], 'depends_on_system_id' => $sys['strom'], 'sort' => 0, 'note' => null, 'created_at' => $ts, 'updated_at' => $ts],
                ['system_id' => $sys['internet'], 'depends_on_system_id' => $sys['strom'], 'sort' => 0, 'note' => null, 'created_at' => $ts, 'updated_at' => $ts],
                ['system_id' => $sys['notstrom'], 'depends_on_system_id' => $sys['strom'], 'sort' => 1, 'note' => 'Springt bei Netzausfall ein (Netzersatzanlage).', 'created_at' => $ts, 'updated_at' => $ts],
                ['system_id' => $sys['telefon'], 'depends_on_system_id' => $sys['internet'], 'sort' => 1, 'note' => 'VoIP-Anteil der TK-Anlage.', 'created_at' => $ts, 'updated_at' => $ts],
                ['system_id' => $sys['pflegedoku'], 'depends_on_system_id' => $sys['internet'], 'sort' => 0, 'note' => 'Cloud-Backup-Sync; lokaler Server läuft offline weiter.', 'created_at' => $ts, 'updated_at' => $ts],
                ['system_id' => $sys['medikamente'], 'depends_on_system_id' => $sys['pflegedoku'], 'sort' => 0, 'note' => 'Modul/Datenbasis der Heim-Software.', 'created_at' => $ts, 'updated_at' => $ts],
                ['system_id' => $sys['heimverwaltung'], 'depends_on_system_id' => $sys['pflegedoku'], 'sort' => 0, 'note' => 'Gemeinsame Software-Plattform.', 'created_at' => $ts, 'updated_at' => $ts],
                ['system_id' => $sys['dienstplan'], 'depends_on_system_id' => $sys['pflegedoku'], 'sort' => 0, 'note' => null, 'created_at' => $ts, 'updated_at' => $ts],
                ['system_id' => $sys['mail'], 'depends_on_system_id' => $sys['internet'], 'sort' => 0, 'note' => null, 'created_at' => $ts, 'updated_at' => $ts],
                ['system_id' => $sys['kueche'], 'depends_on_system_id' => $sys['strom'], 'sort' => 0, 'note' => 'Kühl-/Tiefkühlhaus notstrom-abgesichert.', 'created_at' => $ts, 'updated_at' => $ts],
                ['system_id' => $sys['waescherei'], 'depends_on_system_id' => $sys['strom'], 'sort' => 0, 'note' => null, 'created_at' => $ts, 'updated_at' => $ts],
            ],

            'insurance_policies' => [
                ['id' => Helpers::uuid(), 'type' => 'cyber', 'insurer' => 'HDI Cyber+ Heilberufe', 'policy_number' => 'CY-SZ-2026-088', 'hotline' => '0800 4434464', 'email' => 'cyber-heilberufe@hdi.example', 'reporting_window' => 'unverzüglich, spätestens 24 Stunden', 'contact_name' => 'Hr. Lorenz', 'notes' => 'Deckung 1.000.000 €, Spezialtarif Pflegeeinrichtungen (Bewohnerdaten Art. 9 DSGVO).', 'deductible' => '5.000 €', 'created_at' => $ts, 'updated_at' => $ts],
                ['id' => Helpers::uuid(), 'type' => 'liability', 'insurer' => 'Versicherungskammer Bayern (Betriebshaftpflicht Pflegeheim)', 'policy_number' => 'BHV-SZ-2025-33', 'hotline' => '089 2160-0', 'email' => 'heilberufe-schaden@vkb.example', 'reporting_window' => 'binnen 7 Tagen', 'contact_name' => 'Fr. Mayer', 'notes' => 'Betriebshaftpflicht stationäre Pflege inkl. Obhuts-/Personenschäden, Deckung 5 Mio €.', 'deductible' => '1.000 €', 'created_at' => $ts, 'updated_at' => $ts],
                ['id' => Helpers::uuid(), 'type' => 'property', 'insurer' => 'Allianz Sach AG (Gebäude-/Inhaltsversicherung)', 'policy_number' => 'PROP-SZ-2024-12', 'hotline' => '0800 1112020', 'email' => 'gewerbe-schaden@allianz.example', 'reporting_window' => 'unverzüglich', 'contact_name' => 'Hr. Schubert', 'notes' => 'Gebäude, Inventar, Technik (Schwesternruf, Notstrom, Aufzüge) inkl. Elementarschäden und Feuer.', 'deductible' => '2.500 €', 'created_at' => $ts, 'updated_at' => $ts],
                ['id' => Helpers::uuid(), 'type' => 'business_interruption', 'insurer' => 'Allianz Sach AG', 'policy_number' => 'BI-SZ-2025-21', 'hotline' => '0800 1112020', 'email' => 'gewerbe-schaden@allianz.example', 'reporting_window' => 'binnen 7 Tagen', 'contact_name' => 'Hr. Schubert', 'notes' => 'Betriebsunterbrechung bis 60 Tage. Deckt Ertragsausfall bei Teil-/Vollräumung der Einrichtung.', 'deductible' => '2.500 €', 'created_at' => $ts, 'updated_at' => $ts],
            ],

            'communication_templates' => [
                ['id' => Helpers::uuid(), 'name' => 'Angehörigen-Info bei Störung/Vorfall (Telefon)', 'audience' => 'customers', 'channel' => 'phone', 'subject' => null, 'body' => "Anrufskript Angehörige:\n\nGuten Tag, hier {{ ansprechpartner }} vom Seniorenzentrum Sonnenhof. Ich rufe wegen Frau/Herrn {{ bewohner }} an.\n\nWir möchten Sie informieren, dass es bei uns aktuell zu {{ vorfall }} gekommen ist.\nDie Versorgung Ihrer Angehörigen ist sichergestellt: {{ massnahme }}.\nEs besteht {{ ggf_keine }} unmittelbare Gefahr für die Bewohner.\n\nBei Fragen erreichen Sie uns unter 07131 666 0 (im Notfall: 0172 6660002).\n\nVielen Dank für Ihr Verständnis.", 'fallback' => 'Bei Nicht-Erreichen: 2. Versuch nach 30 Min, danach Hinterlegung Sammel-Info am Empfang/Aushang.', 'sort' => 0, 'created_at' => $ts, 'updated_at' => $ts],
                ['id' => Helpers::uuid(), 'name' => 'Meldung an Heimaufsicht (E-Mail)', 'audience' => 'authorities', 'channel' => 'email', 'subject' => 'Meldung besonderes Vorkommnis – Seniorenzentrum Sonnenhof gGmbH', 'body' => "Sehr geehrte Damen und Herren der Heimaufsicht,\n\nhiermit melden wir gemäß den Anzeigepflichten nach Landesheimgesetz/WTG ein besonderes Vorkommnis in unserer Einrichtung.\n\nEinrichtung: Seniorenzentrum Sonnenhof gGmbH\nZeitpunkt: {{ zeitpunkt }}\nVorkommnis: {{ vorkommnis }}\nBetroffene Bewohner: {{ betroffene }}\nSofortmaßnahmen: {{ massnahmen }}\nAuswirkung auf die Versorgung: {{ auswirkung }}\nVoraussichtliche Behebung: {{ prognose }}\n\nDie pflegerische Versorgung der Bewohner ist durch Ersatzmaßnahmen sichergestellt.\n\nMit freundlichen Grüßen\n{{ heimleitung_name }}\nEinrichtungsleitung", 'fallback' => 'Telefonische Vorab-Information bei der Heimaufsicht parallel zur Mail.', 'sort' => 1, 'created_at' => $ts, 'updated_at' => $ts],
                ['id' => Helpers::uuid(), 'name' => 'Mitarbeiter-Schichtanweisung (SMS-Verteiler)', 'audience' => 'employees', 'channel' => 'sms', 'subject' => null, 'body' => 'WICHTIG Sonnenhof: {{ system }} aktuell gestört. Bitte {{ anweisung }} (z.B. Sicht-Rundgänge alle 15 Min / Papier-Doku verwenden). Keine Bewohnerdaten per privater App weitergeben! Rückfragen: 0172 6660002 (PDL Reinhardt). Stand: {{ zeitpunkt }}.', 'fallback' => 'Telefonkette: PDL → Wohnbereichsleitungen → Pflegekräfte.', 'sort' => 2, 'created_at' => $ts, 'updated_at' => $ts],
                ['id' => Helpers::uuid(), 'name' => 'DSGVO-Meldung Aufsichtsbehörde (Bewohnerdaten Art. 9)', 'audience' => 'authorities', 'channel' => 'email', 'subject' => 'Meldung gemäß Art. 33 DSGVO – Seniorenzentrum Sonnenhof (besondere Kategorien)', 'body' => "Sehr geehrte Damen und Herren,\n\nhiermit melden wir gemäß Art. 33 DSGVO einen Sicherheitsvorfall mit Bezug zu personenbezogenen Daten besonderer Kategorien (Gesundheitsdaten Art. 9 DSGVO – Bewohner-Diagnosen, Medikation, Pflegedoku).\n\nVerantwortlicher: Seniorenzentrum Sonnenhof gGmbH\nBranche: Stationäre Pflege (SGB XI)\nZeitpunkt der Kenntnis: {{ zeitpunkt }}\nVorfall: {{ vorfall }}\nBetroffene Personen (geschätzt): {{ anzahl }}\nMaßnahmen: {{ massnahmen }}\nDSB: Klaus Engel (extern)\n\nMit freundlichen Grüßen\n{{ heimleitung_name }}\nEinrichtungsleitung", 'fallback' => null, 'sort' => 3, 'created_at' => $ts, 'updated_at' => $ts],
                ['id' => Helpers::uuid(), 'name' => 'Aushang Schwesternruf-Ausfall (Sofortmaßnahme)', 'audience' => 'employees', 'channel' => 'notice', 'subject' => 'Schwesternruf-Ausfall – Sofortmaßnahme', 'body' => "AUSHANG DIENSTZIMMER — SCHWESTERNRUF-NOTFALL\n\n1. SOFORT verstärkte Sicht-Rundgänge: jeder Bewohner alle 15–30 Min (risikoorientiert), bettlägerige/sturzgefährdete zuerst\n2. Zusätzliche Pflegekraft je Wohnbereich einteilen (Heimleitung/PDL informieren)\n3. Mobile Notruf-Klingeln/Handglocken aus Notfallschrank an gefährdete Bewohner verteilen\n4. RUF Notdienst anrufen: 0800 7838000 (24/7)\n5. Vorfall + Maßnahmen lückenlos dokumentieren (Haftung!)\n\nDie sichere Versorgung der Bewohner hat absolute Priorität — RTO 10 Minuten!", 'fallback' => 'Aushang in allen Dienstzimmern + Eintrag Übergabebuch.', 'sort' => 4, 'created_at' => $ts, 'updated_at' => $ts],
                ['id' => Helpers::uuid(), 'name' => 'Gesundheitsamt-Meldung Infektionsausbruch (IfSG)', 'audience' => 'authorities', 'channel' => 'email', 'subject' => 'Meldung Infektionsausbruch gemäß § 6 / § 36 IfSG – Seniorenzentrum Sonnenhof', 'body' => "Sehr geehrte Damen und Herren des Gesundheitsamtes,\n\nhiermit melden wir gemäß Infektionsschutzgesetz (§ 6 i.V.m. § 36 IfSG) das gehäufte Auftreten von Infektionen in unserer Einrichtung.\n\nEinrichtung: Seniorenzentrum Sonnenhof gGmbH\nErreger/Verdacht: {{ erreger }}\nErste Erkrankung: {{ erstes_datum }}\nBetroffene Bewohner: {{ bewohner_anzahl }}\nBetroffene Mitarbeiter: {{ ma_anzahl }}\nBetroffene Wohnbereiche: {{ wohnbereiche }}\nEingeleitete Hygienemaßnahmen: {{ massnahmen }} (Isolierung, Kohortierung, Aufnahmestopp geprüft)\nHygienebeauftragter: Markus Brenner\n\nWir bitten um Rückmeldung zu weiteren Anordnungen.\n\nMit freundlichen Grüßen\n{{ heimleitung_name }}\nEinrichtungsleitung", 'fallback' => 'Unverzügliche telefonische Meldung an Gesundheitsamt (07131 994 400) vor/parallel zur Mail.', 'sort' => 5, 'created_at' => $ts, 'updated_at' => $ts],
            ],

            'emergency_resources' => [
                ['id' => Helpers::uuid(), 'type' => 'offline_docs', 'name' => 'Papier-Bewohnerliste mit Medikation/Diagnosen', 'description' => 'Vollständige Notfall-Bewohnerliste je Wohnbereich: Name, Zimmer, Diagnosen, aktuelle Medikation, Allergien, Notfallkontakt, Patientenverfügung/Vorsorge, Pflegegrad. Tagesaktuell gedruckt.', 'location' => 'Dienstzimmer jedes Wohnbereichs (verschlossener Schrank) + Tresor Heimleitung (Gesamtliste)', 'access_holders' => 'PDL, stv. PDL, Wohnbereichsleitungen, Schichtleitung Nachtdienst', 'last_check_at' => Helpers::date(-1), 'next_check_at' => Helpers::date(0), 'notes' => 'BESONDERS SENSIBEL (Art. 9 DSGVO) — verschlossen aufbewahren, Zugang protokollieren. TÄGLICH neu drucken bei Medikationsänderung. Lebenswichtig bei Pflegedoku-/Stromausfall und Evakuierung.', 'sort' => 0, 'created_at' => $ts, 'updated_at' => $ts, 'last_reminder_sent_at' => null],
                ['id' => Helpers::uuid(), 'type' => 'replacement_hardware', 'name' => 'Notfall-Mobiltelefone (3 Stück, anderer Provider)', 'description' => '3× Smartphone mit Prepaid-SIM eines anderen Netzbetreibers. Für Telefon-Failover (Dienstzimmer) und Erreichbarkeit von Rettungsdienst/Ärzten bei TK-Ausfall. Aktivierung halbjährlich.', 'location' => 'Tresor Heimleitung + 1 je Etage im Dienstzimmer-Schrank', 'access_holders' => 'Heimleitung, PDL, Wohnbereichsleitungen, Nachtdienst', 'last_check_at' => Helpers::date(-90), 'next_check_at' => Helpers::date(90), 'notes' => 'Halbjährlicher Aktivierungs-Anruf zwingend (sonst SIM-Sperre). Akkus geladen halten.', 'sort' => 1, 'created_at' => $ts, 'updated_at' => $ts, 'last_reminder_sent_at' => null],
                ['id' => Helpers::uuid(), 'type' => 'emergency_cash', 'name' => 'Bargeld-Notfallkasse', 'description' => '500 € in Scheinen + 50 € Münzgeld (für Notbeschaffung Lebensmittel, Apotheke, Material, Mietgeräte bei Systemausfall).', 'location' => 'Tresor Verwaltung', 'access_holders' => 'Heimleitung, Verwaltungsleitung, PDL', 'last_check_at' => Helpers::date(-30), 'next_check_at' => Helpers::date(60), 'notes' => null, 'sort' => 2, 'created_at' => $ts, 'updated_at' => $ts, 'last_reminder_sent_at' => null],
                ['id' => Helpers::uuid(), 'type' => 'generator_ups', 'name' => 'Notstromaggregat + USV-Anlagen', 'description' => 'Diesel-Netzersatzanlage mit Tankvorrat (24h) + USV für Schwesternruf, BMA, Server und Kühlkette. Versorgt priorisierte Verbraucher bei Netzausfall.', 'location' => 'Technikraum UG (NEA) + Serverraum/Verteiler (USV)', 'access_holders' => 'Leiter Haustechnik (Jürgen Stahl), eingewiesene Pflegefachkräfte Nachtdienst', 'last_check_at' => Helpers::date(-20), 'next_check_at' => Helpers::date(10), 'notes' => 'Monatlicher Lastlauf + Tankstand prüfen. Wartung über EnergieTechnik Süd. USV-Akkus jährlich testen.', 'sort' => 3, 'created_at' => $ts, 'updated_at' => $ts, 'last_reminder_sent_at' => null],
                ['id' => Helpers::uuid(), 'type' => 'offline_docs', 'name' => 'Papier-Pflegedoku-Vordrucke', 'description' => 'Vordruck-Sätze für Pflegedoku, Medikamentengabe/BtM, Vitalwerte, Lagerungs-/Sturzprotokoll, Trinkprotokoll. Lückenlose Übertragung in Software nach Wiederanlauf zwingend!', 'location' => 'Stations-Lager je Wohnbereich (Notvorrat) + Pflegebüro', 'access_holders' => 'Alle Pflegekräfte', 'last_check_at' => Helpers::date(-60), 'next_check_at' => Helpers::date(120), 'notes' => 'Bestand quartalsweise prüfen, Nachdruck rechtzeitig bestellen.', 'sort' => 4, 'created_at' => $ts, 'updated_at' => $ts, 'last_reminder_sent_at' => null],
                ['id' => Helpers::uuid(), 'type' => 'offline_docs', 'name' => 'Notfallhandbuch (Papier)', 'description' => 'Druckversion inkl. Telefonliste Krisenrollen, Playbooks (Schwesternruf/Strom/Brand/Ausbruch), Räumungs-/Evakuierungsplan, Dienstleister-Hotlines (RUF, EnergieTechnik, BMA, OTIS), Gesundheitsamt, Heimaufsicht.', 'location' => '1× Heimleitung, 1× PDL, 1× je Dienstzimmer (4 Wohnbereiche), 1× Pforte/Empfang', 'access_holders' => 'Heimleitung, PDL, Wohnbereichsleitungen, Nachtdienst, Empfang', 'last_check_at' => Helpers::date(-14), 'next_check_at' => Helpers::date(180), 'notes' => 'Räumungsplan/Brandschutzordnung mit Feuerwehr abgestimmt halten.', 'sort' => 5, 'created_at' => $ts, 'updated_at' => $ts, 'last_reminder_sent_at' => null],
            ],

            'handbook_tests' => [
                ['id' => Helpers::uuid(), 'type' => 'contact_check', 'name' => 'Quartals-Check Telefonliste + Rufbereitschaft', 'description' => 'Erreichbarkeit aller Krisenrollen + Rufbereitschaftskette PDL/stv. + Dienstleister-Notdienste (RUF, EnergieTechnik, BMA, OTIS) + Gesundheitsamt/Heimaufsicht prüfen.', 'interval' => 'quarterly', 'last_executed_at' => Helpers::date(-60), 'next_due_at' => Helpers::date(30), 'responsible_employee_id' => $emp['verwaltung'], 'result_notes' => null, 'sort' => 0, 'created_at' => $ts, 'updated_at' => $ts, 'last_reminder_sent_at' => null],
                ['id' => Helpers::uuid(), 'type' => 'recovery', 'name' => 'Schwesternruf-Ausfall-Test (DIN VDE 0834)', 'description' => 'Funktionsprüfung Schwesternruf in Stichprobe je Wohnbereich + Simulation Ausfall: Umstellung auf Sicht-Rundgänge, mobile Notrufklingeln, Notdienst-Eskalation. RTO 10 Min prüfen.', 'interval' => 'quarterly', 'last_executed_at' => Helpers::date(-45), 'next_due_at' => Helpers::date(45), 'responsible_employee_id' => $emp['haustechnik'], 'result_notes' => null, 'sort' => 1, 'created_at' => $ts, 'updated_at' => $ts, 'last_reminder_sent_at' => null],
                ['id' => Helpers::uuid(), 'type' => 'tabletop', 'name' => 'Tabletop Stromausfall mit pflegebedürftigen Bewohnern', 'description' => 'Schreibtisch-Übung: mehrstündiger Stromausfall. Notstrom-Priorisierung (Schwesternruf/Kühlkette/Heizung/IT), Kühlkette-Umlagerung, Aufzug-Ausfall, Heizung im Winter, Kommunikation Angehörige/Heimaufsicht.', 'interval' => 'yearly', 'last_executed_at' => Helpers::date(-150), 'next_due_at' => Helpers::date(215), 'responsible_employee_id' => $emp['pdl'], 'result_notes' => null, 'sort' => 2, 'created_at' => $ts, 'updated_at' => $ts, 'last_reminder_sent_at' => null],
                ['id' => Helpers::uuid(), 'type' => 'backup_restore', 'name' => 'Restore-Test Pflegedokumentation', 'description' => 'Restore-Übung Pflegedoku-/Medikamenten-Datenbank aus Backup (mit MSP/Hersteller). Datenstand, Vollständigkeit Medikationspläne und Doku-Konsistenz validieren.', 'interval' => 'yearly', 'last_executed_at' => Helpers::date(-200), 'next_due_at' => Helpers::date(165), 'responsible_employee_id' => $emp['haustechnik'], 'result_notes' => null, 'sort' => 3, 'created_at' => $ts, 'updated_at' => $ts, 'last_reminder_sent_at' => null],
                ['id' => Helpers::uuid(), 'type' => 'recovery', 'name' => 'Evakuierungs-/Räumungsübung', 'description' => 'Praktische Räumungsübung (Brandschutzordnung/Evakuierungskonzept) mit Feuerwehr: horizontale Evakuierung in nächsten Brandabschnitt, Bewohner-Zählung anhand Papier-Bewohnerliste, Tragehilfen, Sammelplatz.', 'interval' => 'yearly', 'last_executed_at' => Helpers::date(-120), 'next_due_at' => Helpers::date(245), 'responsible_employee_id' => $emp['qmb'], 'result_notes' => null, 'sort' => 4, 'created_at' => $ts, 'updated_at' => $ts, 'last_reminder_sent_at' => null],
            ],

            'system_tasks' => [
                ['id' => Helpers::uuid(), 'system_id' => $sys['schwesternruf'], 'title' => 'Schwesternruf-Funktionsprüfung (Stichprobe)', 'description' => 'Monatliche Sichtprüfung Ruftaster/Signalisierung je Wohnbereich, Doku nach DIN VDE 0834. Defekte sofort an RUF-Notdienst.', 'due_date' => Helpers::date(15), 'completed_at' => null, 'sort' => 0, 'created_at' => $ts, 'updated_at' => $ts],
                ['id' => Helpers::uuid(), 'system_id' => $sys['schwesternruf'], 'title' => 'Mobile Notruf-Klingeln im Notfallschrank prüfen', 'description' => 'Bestand und Funktion der mobilen Handglocken/Notrufklingeln für Schwesternruf-Ausfall kontrollieren.', 'due_date' => Helpers::date(45), 'completed_at' => null, 'sort' => 1, 'created_at' => $ts, 'updated_at' => $ts],
                ['id' => Helpers::uuid(), 'system_id' => $sys['notstrom'], 'title' => 'Notstrom-Lastlauf + Tankstand', 'description' => 'Monatlicher Lastlauf Notstromaggregat unter Last, Tankvorrat (24h) prüfen, Startautomatik testen, Doku.', 'due_date' => Helpers::date(10), 'completed_at' => null, 'sort' => 0, 'created_at' => $ts, 'updated_at' => $ts],
                ['id' => Helpers::uuid(), 'system_id' => $sys['notstrom'], 'title' => 'USV-Akkutest', 'description' => 'Jährlicher USV-Akkutest (Überbrückungszeit messen) für Schwesternruf/Server. Akkus bei Bedarf tauschen.', 'due_date' => Helpers::date(90), 'completed_at' => null, 'sort' => 1, 'created_at' => $ts, 'updated_at' => $ts],
                ['id' => Helpers::uuid(), 'system_id' => $sys['kuehlkette'], 'title' => 'Kühlketten-Temperaturlog prüfen', 'description' => 'Wöchentliche Kontrolle der Temperaturlogger (2–8 °C) Medikamenten-Kühlschränke, Min/Max dokumentieren, Abweichungen melden.', 'due_date' => Helpers::date(7), 'completed_at' => null, 'sort' => 0, 'created_at' => $ts, 'updated_at' => $ts],
                ['id' => Helpers::uuid(), 'system_id' => $sys['brandmelde'], 'title' => 'Brandmeldeanlage-Wartung (DIN 14675)', 'description' => 'Jährliche Wartung BMA + Aufschaltung Feuerwehr über BrandSchutz Müller koordinieren, Prüfbuch führen.', 'due_date' => Helpers::date(60), 'completed_at' => null, 'sort' => 0, 'created_at' => $ts, 'updated_at' => $ts],
                ['id' => Helpers::uuid(), 'system_id' => $sys['pflegedoku'], 'title' => 'Backup Pflegedoku verifizieren', 'description' => 'Backup-Status Pflegedoku-/Medikamenten-DB mit MSP prüfen, Restore-Stichprobe vorbereiten.', 'due_date' => Helpers::date(30), 'completed_at' => null, 'sort' => 0, 'created_at' => $ts, 'updated_at' => $ts],
                ['id' => Helpers::uuid(), 'system_id' => $sys['medikamente'], 'title' => 'Tagesausdruck Medikationspläne sicherstellen', 'description' => 'Automatischen Tagesdruck der Medikationspläne je Wohnbereich prüfen (Fallback bei Software-Ausfall).', 'due_date' => Helpers::date(20), 'completed_at' => null, 'sort' => 0, 'created_at' => $ts, 'updated_at' => $ts],
                ['id' => Helpers::uuid(), 'system_id' => $sys['aufzug'], 'title' => 'Aufzug-TÜV-/Wartungstermin koordinieren', 'description' => 'Jährliche TÜV-Prüfung und Wartung Bettenaufzüge über OTIS terminieren, Notruf/Befreiungsfunktion testen.', 'due_date' => Helpers::date(75), 'completed_at' => null, 'sort' => 0, 'created_at' => $ts, 'updated_at' => $ts],
                ['id' => Helpers::uuid(), 'system_id' => $sys['heizung'], 'title' => 'Legionellenprüfung Warmwasser (TrinkwV)', 'description' => 'Turnusmäßige Legionellen-Beprobung Warmwassersystem nach TrinkwV, Ergebnisse dokumentieren.', 'due_date' => Helpers::date(100), 'completed_at' => null, 'sort' => 0, 'created_at' => $ts, 'updated_at' => $ts],
                ['id' => Helpers::uuid(), 'system_id' => $sys['kueche'], 'title' => 'HACCP-Temperaturdoku-Check', 'description' => 'Monatliche Prüfung HACCP-Eigenkontrolle Großküche, Kühl-/Tiefkühltemperaturen, Reinigungspläne.', 'due_date' => Helpers::date(25), 'completed_at' => null, 'sort' => 0, 'created_at' => $ts, 'updated_at' => $ts],
                ['id' => Helpers::uuid(), 'system_id' => $sys['mail'], 'title' => 'Phishing-Awareness Pflege/Verwaltung', 'description' => 'Schulung speziell zu Phishing mit Fokus auf Bewohner-/Gesundheitsdaten (Art. 9 DSGVO).', 'due_date' => Helpers::date(120), 'completed_at' => null, 'sort' => 0, 'created_at' => $ts, 'updated_at' => $ts],
            ],
        ]);
    }
}
