<?php

namespace Database\Seeders\IndustryTemplates;

use App\Enums\Industry;

class SeniorenzentrumKritisTemplate implements Contract
{
    public function name(): string
    {
        return 'Seniorenzentren-Verbund (KRITIS/NIS2, mehrere Häuser)';
    }

    public function industry(): Industry
    {
        return Industry::Dienstleistung;
    }

    public function description(): string
    {
        return 'Verbund mehrerer stationärer Seniorenzentren mit zentraler IT/eigenem Rechenzentrum in der Verwaltung (~600 Mitarbeiter, mehrere Häuser). Als Einrichtung des Sektors Gesundheit gilt der Verbund als „wichtige Einrichtung" nach NIS2 (NIS2UmsuCG / BSIG) bzw. KRITIS-relevant. Schwerpunkte: zentrale mandantenfähige Pflegedoku über alle Häuser, Schwesternruf/Lichtruf je Haus, Medikations- und Kühlketten-Sicherheit, ISMS nach ISO 27001, Lieferketten-/Dienstleistersicherheit. Enthält registrierungs- und Meldepflichten ans BSI (24h-Frühwarnung, §8a/§8b BSIG), Heimrecht/WTG, IfSG sowie Art. 9/Art. 33 DSGVO. Umfasst 3 Standorte (Zentrale+RZ, 2 Pflegehäuser), 14 Mitarbeiter inkl. CISO/ISB/Krisenstab, 15 Systeme mit RTO/RPO, 7 Dienstleister inkl. BSI-Meldestelle, Versicherungen, NIS2-Kommunikationsvorlagen, KRITIS-Testplan und system_tasks.';
    }

    public function sort(): int
    {
        return 92;
    }

    public function payload(): array
    {
        // Stable IDs, damit FK-Verweise innerhalb des Payloads konsistent
        // bleiben. Beim Apply werden sie via regenerateIds neu gemappt.
        $loc = [
            'zentrale' => Helpers::uuid(),
            'haus_a' => Helpers::uuid(),
            'haus_b' => Helpers::uuid(),
        ];

        $emp = [
            'gf' => Helpers::uuid(),
            'it_lead' => Helpers::uuid(),
            'it_stv' => Helpers::uuid(),
            'isb' => Helpers::uuid(),
            'pflegedirektion' => Helpers::uuid(),
            'qmb_hygiene' => Helpers::uuid(),
            'presse' => Helpers::uuid(),
            'dsb' => Helpers::uuid(),
            'haustechnik' => Helpers::uuid(),
            'heimleitung_a' => Helpers::uuid(),
            'heimleitung_b' => Helpers::uuid(),
            'pdl_a' => Helpers::uuid(),
            'pdl_b' => Helpers::uuid(),
            'apotheke' => Helpers::uuid(),
        ];

        $prov = [
            'msp' => Helpers::uuid(),
            'bsi' => Helpers::uuid(),
            'software' => Helpers::uuid(),
            'lfdi' => Helpers::uuid(),
            'energie' => Helpers::uuid(),
            'internet' => Helpers::uuid(),
            'heimaufsicht' => Helpers::uuid(),
        ];

        $sys = [
            'rz' => Helpers::uuid(),
            'pflegedoku' => Helpers::uuid(),
            'schwesternruf' => Helpers::uuid(),
            'medikation' => Helpers::uuid(),
            'erp' => Helpers::uuid(),
            'dienstplan' => Helpers::uuid(),
            'vpn' => Helpers::uuid(),
            'backup' => Helpers::uuid(),
            'siem' => Helpers::uuid(),
            'voip' => Helpers::uuid(),
            'notstrom' => Helpers::uuid(),
            'bma' => Helpers::uuid(),
            'internet' => Helpers::uuid(),
            'm365' => Helpers::uuid(),
            'kuehlkette' => Helpers::uuid(),
        ];

        $ts = Helpers::now();

        return Helpers::payload([
            'company' => [[
                'name' => 'Seniorenzentren Lebensbogen Stiftung',
                'industry' => 'dienstleistung',
                'employee_count' => 600,
                'review_cycle_months' => 6,
                'legal_form' => 'stiftung',
                'kritis_relevant' => 'yes',
                'nis2_classification' => 'important',
                'cyber_insurance_deductible' => '25.000 €',
                'budget_it_lead' => 5000,
                'budget_emergency_officer' => 20000,
                'budget_management' => 150000,
                'data_protection_authority_name' => 'LfDI Baden-Württemberg',
                'data_protection_authority_phone' => '0711 615541-0',
                'data_protection_authority_website' => 'https://www.baden-wuerttemberg.datenschutz.de',
            ]],

            'locations' => [
                [
                    'id' => $loc['zentrale'], 'name' => 'Verwaltung & Rechenzentrum (Zentrale)', 'street' => 'Stiftungsallee 1',
                    'postal_code' => '70173', 'city' => 'Stuttgart', 'country' => 'DE',
                    'is_headquarters' => 1, 'phone' => '0711 8800 100',
                    'notes' => 'Zentrale IT mit eigenem Rechenzentrum (Server, Storage, SIEM, Backup), Geschäftsführung, zentrale Pflegedirektion, Personalabteilung, Abrechnung, Pressestelle. Versorgt alle Häuser des Verbunds über VPN/MPLS. NIS2-/KRITIS-Schaltzentrale, Krisenstab tagt hier.',
                    'sort' => 0, 'created_at' => $ts, 'updated_at' => $ts,
                ],
                [
                    'id' => $loc['haus_a'], 'name' => 'Pflegehaus Sonnenhalde', 'street' => 'Sonnenhalde 22',
                    'postal_code' => '70597', 'city' => 'Stuttgart', 'country' => 'DE',
                    'is_headquarters' => 0, 'phone' => '0711 8800 200',
                    'notes' => 'Stationäres Pflegehaus, 120 Bewohnerplätze, 3 Wohnbereiche. Eigener Schwesternruf, Hausapotheke mit Kühlkette, Notstrom. 24/7-Betrieb.',
                    'sort' => 1, 'created_at' => $ts, 'updated_at' => $ts,
                ],
                [
                    'id' => $loc['haus_b'], 'name' => 'Pflegehaus Lindenpark', 'street' => 'Lindenstraße 8',
                    'postal_code' => '71638', 'city' => 'Ludwigsburg', 'country' => 'DE',
                    'is_headquarters' => 0, 'phone' => '07141 9900 300',
                    'notes' => 'Stationäres Pflegehaus, 90 Bewohnerplätze, beschützender Wohnbereich (Demenz). Eigener Schwesternruf, Notstrom, Brandmeldeanlage. 24/7-Betrieb.',
                    'sort' => 2, 'created_at' => $ts, 'updated_at' => $ts,
                ],
            ],

            'employees' => [
                ['id' => $emp['gf'], 'first_name' => 'Dr. Andreas', 'last_name' => 'Vogt', 'position' => 'Geschäftsführung / Vorstand Stiftung', 'department' => 'Geschäftsführung', 'work_phone' => '0711 8800 101', 'mobile_phone' => '0171 5550001', 'private_phone' => '0711 660011', 'email' => 'a.vogt@lebensbogen-stiftung.de', 'emergency_contact' => null, 'manager_id' => null, 'is_key_personnel' => 1, 'crisis_role' => 'management', 'is_crisis_deputy' => 0, 'notes' => 'Leitet den Krisenstab. Verantwortlich für NIS2-Geschäftsleitungspflichten (§38 BSIG: Billigung & Überwachung der Risikomanagementmaßnahmen, persönliche Haftung).', 'location_id' => $loc['zentrale'], 'created_at' => $ts, 'updated_at' => $ts],
                ['id' => $emp['it_lead'], 'first_name' => 'Sven', 'last_name' => 'Kramer', 'position' => 'IT-Leitung / CISO', 'department' => 'IT', 'work_phone' => '0711 8800 110', 'mobile_phone' => '0171 5550010', 'private_phone' => null, 'email' => 's.kramer@lebensbogen-stiftung.de', 'emergency_contact' => null, 'manager_id' => $emp['gf'], 'is_key_personnel' => 1, 'crisis_role' => 'it_lead', 'is_crisis_deputy' => 0, 'notes' => 'Leitet zentrale IT + Rechenzentrum, CISO. Technische Verantwortung für ISMS (ISO 27001), Meldeketten ans BSI, SIEM/EDR-Auswertung.', 'location_id' => $loc['zentrale'], 'created_at' => $ts, 'updated_at' => $ts],
                ['id' => $emp['it_stv'], 'first_name' => 'Marc', 'last_name' => 'Heller', 'position' => 'Stellv. IT-Leitung / RZ-Administration', 'department' => 'IT', 'work_phone' => '0711 8800 111', 'mobile_phone' => '0171 5550011', 'private_phone' => null, 'email' => 'm.heller@lebensbogen-stiftung.de', 'emergency_contact' => null, 'manager_id' => $emp['it_lead'], 'is_key_personnel' => 1, 'crisis_role' => 'it_lead', 'is_crisis_deputy' => 1, 'notes' => 'Vertretung CISO, Rechenzentrum/Virtualisierung/Backup, Rufbereitschaft IT 24/7.', 'location_id' => $loc['zentrale'], 'created_at' => $ts, 'updated_at' => $ts],
                ['id' => $emp['isb'], 'first_name' => 'Petra', 'last_name' => 'Sauer', 'position' => 'Informationssicherheitsbeauftragte (ISB)', 'department' => 'Informationssicherheit', 'work_phone' => '0711 8800 115', 'mobile_phone' => '0171 5550015', 'private_phone' => null, 'email' => 'p.sauer@lebensbogen-stiftung.de', 'emergency_contact' => null, 'manager_id' => $emp['gf'], 'is_key_personnel' => 1, 'crisis_role' => 'emergency_officer', 'is_crisis_deputy' => 0, 'notes' => 'ISB/Notfallbeauftragte. Pflegt ISMS, Risikoanalyse, Meldeprozess §8b BSIG, Übungen. Unabhängig von IT-Linie an GF berichtend.', 'location_id' => $loc['zentrale'], 'created_at' => $ts, 'updated_at' => $ts],
                ['id' => $emp['pflegedirektion'], 'first_name' => 'Claudia', 'last_name' => 'Berg', 'position' => 'Zentrale Pflegedirektion', 'department' => 'Pflege', 'work_phone' => '0711 8800 120', 'mobile_phone' => '0171 5550020', 'private_phone' => null, 'email' => 'c.berg@lebensbogen-stiftung.de', 'emergency_contact' => null, 'manager_id' => $emp['gf'], 'is_key_personnel' => 1, 'crisis_role' => 'emergency_officer', 'is_crisis_deputy' => 1, 'notes' => 'Verantwortlich für Versorgungssicherheit über alle Häuser. Notfallbeauftragte Pflege im Krisenstab, koordiniert Papier-Notbetrieb der Häuser.', 'location_id' => $loc['zentrale'], 'created_at' => $ts, 'updated_at' => $ts],
                ['id' => $emp['qmb_hygiene'], 'first_name' => 'Daniela', 'last_name' => 'Roth', 'position' => 'Qualitäts- & Hygienemanagement (QMB)', 'department' => 'Qualität', 'work_phone' => '0711 8800 125', 'mobile_phone' => '0171 5550025', 'private_phone' => null, 'email' => 'd.roth@lebensbogen-stiftung.de', 'emergency_contact' => null, 'manager_id' => $emp['pflegedirektion'], 'is_key_personnel' => 1, 'crisis_role' => null, 'is_crisis_deputy' => 0, 'notes' => 'QMB + Hygienebeauftragte (IfSG §23), MD-Prüfungen, Kühlketten-Überwachung, Heimaufsicht-Kontakt.', 'location_id' => $loc['zentrale'], 'created_at' => $ts, 'updated_at' => $ts],
                ['id' => $emp['presse'], 'first_name' => 'Julia', 'last_name' => 'Wagner', 'position' => 'Leitung Kommunikation / Pressestelle', 'department' => 'Kommunikation', 'work_phone' => '0711 8800 130', 'mobile_phone' => '0171 5550030', 'private_phone' => null, 'email' => 'j.wagner@lebensbogen-stiftung.de', 'emergency_contact' => null, 'manager_id' => $emp['gf'], 'is_key_personnel' => 1, 'crisis_role' => 'communications_lead', 'is_crisis_deputy' => 0, 'notes' => 'Zentrale Krisen- und Pressekommunikation, Angehörigen-Information verbundweit, Sprachregelung bei Cyberangriff.', 'location_id' => $loc['zentrale'], 'created_at' => $ts, 'updated_at' => $ts],
                ['id' => $emp['dsb'], 'first_name' => 'Klaus', 'last_name' => 'Engel', 'position' => 'Datenschutzbeauftragter (extern)', 'department' => 'Compliance', 'work_phone' => null, 'mobile_phone' => '0172 5550040', 'private_phone' => null, 'email' => 'engel@datenschutz-extern.example', 'emergency_contact' => null, 'manager_id' => null, 'is_key_personnel' => 1, 'crisis_role' => 'dpo', 'is_crisis_deputy' => 0, 'notes' => 'Externer DSB. Bei Datenpanne sofort Kontakt — Bewohnerdaten = Gesundheitsdaten Art. 9 DSGVO, Art. 33-Meldung an LfDI binnen 72h.', 'location_id' => null, 'created_at' => $ts, 'updated_at' => $ts],
                ['id' => $emp['haustechnik'], 'first_name' => 'Roland', 'last_name' => 'Fischer', 'position' => 'Leitung Haus- & Gebäudetechnik (Verbund)', 'department' => 'Haustechnik', 'work_phone' => '0711 8800 140', 'mobile_phone' => '0171 5550050', 'private_phone' => null, 'email' => 'r.fischer@lebensbogen-stiftung.de', 'emergency_contact' => null, 'manager_id' => $emp['gf'], 'is_key_personnel' => 1, 'crisis_role' => null, 'is_crisis_deputy' => 0, 'notes' => 'Verantwortlich Notstrom/NEA, USV, Heizung, Brandmeldeanlagen, Kühlräume über alle Häuser. Wartungsverträge.', 'location_id' => $loc['zentrale'], 'created_at' => $ts, 'updated_at' => $ts],
                ['id' => $emp['heimleitung_a'], 'first_name' => 'Susanne', 'last_name' => 'Maier', 'position' => 'Heimleitung Sonnenhalde', 'department' => 'Heimleitung', 'work_phone' => '0711 8800 210', 'mobile_phone' => '0171 5550060', 'private_phone' => null, 'email' => 's.maier@lebensbogen-stiftung.de', 'emergency_contact' => null, 'manager_id' => $emp['gf'], 'is_key_personnel' => 1, 'crisis_role' => 'management', 'is_crisis_deputy' => 1, 'notes' => 'Verantwortliche Leitung Pflegehaus Sonnenhalde nach WTG/Heimrecht. Vor-Ort-Krisenleitung Haus A.', 'location_id' => $loc['haus_a'], 'created_at' => $ts, 'updated_at' => $ts],
                ['id' => $emp['heimleitung_b'], 'first_name' => 'Thomas', 'last_name' => 'Brunner', 'position' => 'Heimleitung Lindenpark', 'department' => 'Heimleitung', 'work_phone' => '07141 9900 310', 'mobile_phone' => '0171 5550061', 'private_phone' => null, 'email' => 't.brunner@lebensbogen-stiftung.de', 'emergency_contact' => null, 'manager_id' => $emp['gf'], 'is_key_personnel' => 1, 'crisis_role' => 'management', 'is_crisis_deputy' => 1, 'notes' => 'Verantwortliche Leitung Pflegehaus Lindenpark nach WTG/Heimrecht. Vor-Ort-Krisenleitung Haus B.', 'location_id' => $loc['haus_b'], 'created_at' => $ts, 'updated_at' => $ts],
                ['id' => $emp['pdl_a'], 'first_name' => 'Birgit', 'last_name' => 'Lang', 'position' => 'Pflegedienstleitung Sonnenhalde (PDL)', 'department' => 'Pflege', 'work_phone' => '0711 8800 220', 'mobile_phone' => '0171 5550070', 'private_phone' => null, 'email' => 'b.lang@lebensbogen-stiftung.de', 'emergency_contact' => null, 'manager_id' => $emp['heimleitung_a'], 'is_key_personnel' => 1, 'crisis_role' => null, 'is_crisis_deputy' => 0, 'notes' => 'PDL Haus A, steuert Papier-Notbetrieb bei Doku-Ausfall, Bewohnerliste Haus A.', 'location_id' => $loc['haus_a'], 'created_at' => $ts, 'updated_at' => $ts],
                ['id' => $emp['pdl_b'], 'first_name' => 'Markus', 'last_name' => 'Hofmann', 'position' => 'Pflegedienstleitung Lindenpark (PDL)', 'department' => 'Pflege', 'work_phone' => '07141 9900 320', 'mobile_phone' => '0171 5550071', 'private_phone' => null, 'email' => 'm.hofmann@lebensbogen-stiftung.de', 'emergency_contact' => null, 'manager_id' => $emp['heimleitung_b'], 'is_key_personnel' => 1, 'crisis_role' => null, 'is_crisis_deputy' => 0, 'notes' => 'PDL Haus B, steuert Papier-Notbetrieb bei Doku-Ausfall, Bewohnerliste Haus B.', 'location_id' => $loc['haus_b'], 'created_at' => $ts, 'updated_at' => $ts],
                ['id' => $emp['apotheke'], 'first_name' => 'Anja', 'last_name' => 'Krüger', 'position' => 'Fachkraft Medikation / Apothekenkoordination', 'department' => 'Pflege', 'work_phone' => '0711 8800 230', 'mobile_phone' => '0171 5550080', 'private_phone' => null, 'email' => 'a.krueger@lebensbogen-stiftung.de', 'emergency_contact' => null, 'manager_id' => $emp['pflegedirektion'], 'is_key_personnel' => 1, 'crisis_role' => null, 'is_crisis_deputy' => 0, 'notes' => 'Koordiniert Medikationssoftware + Stellprozess + Kühlkette mit externer Apotheke (Blistering). Kühlketten-Notfallplan.', 'location_id' => $loc['zentrale'], 'created_at' => $ts, 'updated_at' => $ts],
            ],

            'service_providers' => [
                ['id' => $prov['msp'], 'name' => 'SecureHealth IT & SOC GmbH (MSP/SOC)', 'type' => 'it_msp', 'contact_name' => 'NOC/SOC 24/7', 'hotline' => '0711 4455 900', 'email' => 'soc@securehealth-it.example', 'contract_number' => 'MSP-SZ-2026-001', 'sla' => '24/7 SOC-Monitoring, P1 Reaktion < 30 Min', 'notes' => 'Managed Security Service Provider mit SOC/SIEM-Betrieb und Incident Response. Unterstützt NIS2-Meldekette und forensische Analyse. Lieferketten-Sicherheitsanforderungen vertraglich (Art. 21 NIS2).', 'direct_order_limit' => 10000, 'created_at' => $ts, 'updated_at' => $ts],
                ['id' => $prov['bsi'], 'name' => 'BSI – Meldestelle (Bundesamt für Sicherheit in der Informationstechnik)', 'type' => 'bsi_reporting_office', 'contact_name' => 'Nationales IT-Lagezentrum / Meldestelle', 'hotline' => '0228 99 9582-222', 'email' => 'meldestelle@bsi.bund.de', 'contract_number' => null, 'sla' => '24/7 Meldeportal', 'notes' => 'Zuständige Meldestelle nach §8b BSIG / NIS2. Pflichtmeldungen: Erstmeldung (Frühwarnung) binnen 24h, Folgemeldung binnen 72h, Abschlussbericht binnen 1 Monat. Registrierung als wichtige Einrichtung erforderlich.', 'direct_order_limit' => null, 'created_at' => $ts, 'updated_at' => $ts],
                ['id' => $prov['software'], 'name' => 'Vivendi / CGM (Pflegesoftware-Hersteller)', 'type' => 'other', 'contact_name' => 'Premium-Support', 'hotline' => '05121 28 29 1700', 'email' => 'support@pflegesoftware.example', 'contract_number' => 'KD-SZ-2026-441', 'sla' => '24/7 für P1, mandantenfähiges Hosting/On-Prem-Support', 'notes' => 'Hersteller der zentralen mandantenfähigen Pflegedoku + Medikations-/Abrechnungsmodule. Wartungsfenster abgestimmt, Restore-Test jährlich vertraglich.', 'direct_order_limit' => 8000, 'created_at' => $ts, 'updated_at' => $ts],
                ['id' => $prov['lfdi'], 'name' => 'LfDI Baden-Württemberg', 'type' => 'data_protection_authority', 'contact_name' => 'Beschwerde-/Meldestelle', 'hotline' => '0711 615541-0', 'email' => 'poststelle@lfdi.bwl.de', 'contract_number' => null, 'sla' => 'Mo-Fr 8-16', 'notes' => 'Aufsichtsbehörde für DSGVO Art. 33-Meldungen. Bewohnerdaten = besondere Kategorien Art. 9. Meldung binnen 72h.', 'direct_order_limit' => null, 'created_at' => $ts, 'updated_at' => $ts],
                ['id' => $prov['energie'], 'name' => 'EnBW / Stadtwerke (Energieversorger)', 'type' => 'utility', 'contact_name' => 'Großkunden-Entstörung', 'hotline' => '0800 3629000', 'email' => 'entstoerung@energie.example', 'contract_number' => 'EVU-SZ-2025', 'sla' => '24/7 Entstörung', 'notes' => 'Stromversorgung aller Standorte. Bei längerem Ausfall NEA/Notstrom je Haus. Priorisierte Wiederversorgung als Gesundheitseinrichtung anmelden.', 'direct_order_limit' => null, 'created_at' => $ts, 'updated_at' => $ts],
                ['id' => $prov['internet'], 'name' => 'Deutsche Telekom Geschäftskunden (Internet/MPLS)', 'type' => 'internet_provider', 'contact_name' => 'Business Service Desk', 'hotline' => '0800 3301300', 'email' => 'business@telekom.example', 'contract_number' => 'TK-SZ-MPLS-2026', 'sla' => '24/7, 99,9 %, Entstörung < 4h', 'notes' => 'MPLS-Standortvernetzung Zentrale↔Häuser + redundanter Internetzugang Zentrale. LTE/5G-Backup je Standort.', 'direct_order_limit' => 5000, 'created_at' => $ts, 'updated_at' => $ts],
                ['id' => $prov['heimaufsicht'], 'name' => 'Heimaufsicht / Aufsichtsbehörde WTG (Landratsamt)', 'type' => 'other', 'contact_name' => 'Heimaufsicht', 'hotline' => '0711 2153 0', 'email' => 'heimaufsicht@landratsamt.example', 'contract_number' => null, 'sla' => 'Mo-Fr 8-16', 'notes' => 'Heimrechtliche Aufsicht (WTG/Heimrecht). Meldung bei besonderen Vorkommnissen, die die Versorgung der Bewohner gefährden.', 'direct_order_limit' => null, 'created_at' => $ts, 'updated_at' => $ts],
            ],

            'systems' => [
                ['id' => $sys['rz'], 'name' => 'Zentrales Rechenzentrum (Server/Virtualisierung/Storage)', 'description' => 'Eigenes RZ in der Zentrale: Virtualisierungs-Cluster, zentrales Storage/SAN, AD/Identity, hostet zentrale Fachanwendungen für alle Häuser. Redundante USV + Klimatisierung.', 'category' => 'basisbetrieb', 'rto_minutes' => 120, 'rpo_minutes' => 60, 'downtime_cost_per_hour' => 4000, 'fallback_process' => 'KRITIS-Wiederanlaufplan: HA-Failover auf zweiten Hypervisor-Knoten; bei Total-Ausfall Restore aus 3-2-1-Backup nach dokumentierter Wiederanlaufreihenfolge (Identity → Pflegedoku → Medikation → Rest). Häuser laufen währenddessen im Papier-Notbetrieb. MSP/SOC einbinden, NIS2-Meldeprüfung anstoßen.', 'runbook_reference' => 'Runbook „RZ-Wiederanlauf (KRITIS)" v2.1', 'system_priority_id' => null, 'emergency_level_id' => null, 'created_at' => $ts, 'updated_at' => $ts],
                ['id' => $sys['pflegedoku'], 'name' => 'Zentrale Pflegedoku (mandantenfähig, alle Häuser)', 'description' => 'Mandantenfähige elektronische Pflegedokumentation über alle Häuser des Verbunds. Gesetzlich vorgeschrieben (SGB XI), haftungs- und abrechnungsrelevant, Grundlage MD-Prüfung. On-Prem im zentralen RZ.', 'category' => 'geschaeftsbetrieb', 'rto_minutes' => 120, 'rpo_minutes' => 30, 'downtime_cost_per_hour' => 2500, 'fallback_process' => 'Sofort-Umstellung jedes Hauses auf Papier-Pflegedoku (Vordruck-Sätze je Wohnbereich). PDLs koordinieren, lückenlose Nacherfassung nach Wiederanlauf zwingend. Bei Verdacht auf Datenabfluss DSB + Art. 33-Prüfung.', 'runbook_reference' => 'Runbook „Pflegedoku-Ausfall (Verbund)" v1.4', 'system_priority_id' => null, 'emergency_level_id' => null, 'created_at' => $ts, 'updated_at' => $ts],
                ['id' => $sys['schwesternruf'], 'name' => 'Schwesternruf-/Lichtrufanlage (je Haus)', 'description' => 'Bewohner-Notrufanlage (Lichtruf) in jedem Pflegehaus — lebenswichtige Alarmierung des Pflegepersonals. Eigenständige Anlage je Standort, teils mit DECT-Anbindung.', 'category' => 'basisbetrieb', 'rto_minutes' => 30, 'rpo_minutes' => null, 'downtime_cost_per_hour' => 3000, 'fallback_process' => 'SOFORT erhöhte Personalpräsenz/Sichtkontrollen im Wohnbereich (engmaschige Rundgänge), mobile DECT/Notruf-Handgeber, Tür-/Bettalarm-Ersatz. Haustechnik + Anlagen-Wartungsdienst sofort alarmieren. Patientensicherheit hat absolute Priorität.', 'runbook_reference' => 'Runbook „Schwesternruf-Ausfall" v1.2', 'system_priority_id' => null, 'emergency_level_id' => null, 'created_at' => $ts, 'updated_at' => $ts],
                ['id' => $sys['medikation'], 'name' => 'Medikations-/Apothekensoftware', 'description' => 'Medikationsmanagement, Verordnungen, Stell-/Blisterprozess mit externer Apotheke, Betäubungsmittel-Doku. Integriert in Pflegedoku, im zentralen RZ.', 'category' => 'geschaeftsbetrieb', 'rto_minutes' => 240, 'rpo_minutes' => 60, 'downtime_cost_per_hour' => 1200, 'fallback_process' => 'Aktueller Medikationsplan je Bewohner liegt ausgedruckt im Bewohner-Ordner (täglich aktualisiert). Stellung nach Papierplan, Vier-Augen-Prinzip. Externe Apotheke telefonisch/Fax. BtM weiter handschriftlich dokumentieren.', 'runbook_reference' => 'Runbook „Medikation-Ausfall" v1.1', 'system_priority_id' => null, 'emergency_level_id' => null, 'created_at' => $ts, 'updated_at' => $ts],
                ['id' => $sys['kuehlkette'], 'name' => 'Kühlketten-Überwachung (Medikamente/Impfstoffe)', 'description' => 'Temperaturüberwachung der Medikamenten-/Impfstoff-Kühlschränke je Haus mit Alarmierung. Relevant für Arzneimittelsicherheit (AMG/ApBetrO).', 'category' => 'unterstuetzend', 'rto_minutes' => 240, 'rpo_minutes' => 120, 'downtime_cost_per_hour' => 400, 'fallback_process' => 'Manuelle Temperaturmessung + handschriftliches Protokoll alle 2h. Bei Kühlausfall Medikamente in Ersatzkühlschrank/Kühlbox umlagern, Apotheke konsultieren, betroffene Chargen prüfen.', 'runbook_reference' => 'Runbook „Kühlkette" v1.0', 'system_priority_id' => null, 'emergency_level_id' => null, 'created_at' => $ts, 'updated_at' => $ts],
                ['id' => $sys['erp'], 'name' => 'ERP / Heimverwaltung & Abrechnung', 'description' => 'Zentrale Heimverwaltung: Bewohnerverwaltung, Belegung, Leistungsabrechnung Pflege-/Krankenkassen, Buchhaltung. On-Prem im RZ.', 'category' => 'geschaeftsbetrieb', 'rto_minutes' => 480, 'rpo_minutes' => 240, 'downtime_cost_per_hour' => 600, 'fallback_process' => 'Abrechnungslauf verschieben (kein direkter Bewohnerschaden). Belegungsänderungen handschriftlich, Nacherfassung. Liquiditätsplan bei längerem Ausfall.', 'runbook_reference' => 'Runbook „ERP-Ausfall" v1.0', 'system_priority_id' => null, 'emergency_level_id' => null, 'created_at' => $ts, 'updated_at' => $ts],
                ['id' => $sys['dienstplan'], 'name' => 'Dienstplan-/HR-System (zentral)', 'description' => 'Zentrale Personaleinsatzplanung, Arbeitszeiterfassung, Lohnvorbereitung für ~600 Mitarbeiter über alle Häuser.', 'category' => 'geschaeftsbetrieb', 'rto_minutes' => 480, 'rpo_minutes' => 1440, 'downtime_cost_per_hour' => 300, 'fallback_process' => 'Dienstpläne der nächsten 2 Wochen je Wohnbereich gedruckt verfügbar. Änderungen handschriftlich, Nacherfassung nach Wiederanlauf.', 'runbook_reference' => null, 'system_priority_id' => null, 'emergency_level_id' => null, 'created_at' => $ts, 'updated_at' => $ts],
                ['id' => $sys['vpn'], 'name' => 'VPN / Standortvernetzung (MPLS/SD-WAN)', 'description' => 'Sichere Vernetzung der Häuser mit dem zentralen RZ über MPLS mit SD-WAN-Overlay. Grundlage für Zugriff der Häuser auf alle zentralen Fachanwendungen.', 'category' => 'basisbetrieb', 'rto_minutes' => 120, 'rpo_minutes' => null, 'downtime_cost_per_hour' => 1500, 'fallback_process' => 'SD-WAN-Failover auf LTE/5G-Backup je Standort automatisch. Bei Total-Ausfall eines Hauses: lokaler Papier-Notbetrieb, Telefon-Koordination mit Zentrale. MSP einbinden.', 'runbook_reference' => 'Runbook „Standortvernetzung-Ausfall" v1.1', 'system_priority_id' => null, 'emergency_level_id' => null, 'created_at' => $ts, 'updated_at' => $ts],
                ['id' => $sys['backup'], 'name' => 'Backup-System (3-2-1, Offline/Immutable)', 'description' => 'Zentrales Backup nach 3-2-1-Regel: tägliche Backups, zweite Kopie auf anderem Medium, Offline-/Immutable-Kopie extern (Ransomware-sicher). Basis für KRITIS-Wiederanlauf.', 'category' => 'basisbetrieb', 'rto_minutes' => 240, 'rpo_minutes' => 60, 'downtime_cost_per_hour' => 800, 'fallback_process' => 'Bei Ausfall der Backup-Infrastruktur: keine neuen Sicherungen — sofort eskalieren, manuelle Sicherung kritischer Daten. Restore-Pfad ist Kernfähigkeit; Integrität der Offline-Kopie regelmäßig prüfen.', 'runbook_reference' => 'Runbook „Backup & Restore (3-2-1)" v2.0', 'system_priority_id' => null, 'emergency_level_id' => null, 'created_at' => $ts, 'updated_at' => $ts],
                ['id' => $sys['siem'], 'name' => 'SIEM / EDR (Security Monitoring, NIS2)', 'description' => 'Zentrales Security-Monitoring (SIEM) + Endpoint Detection & Response über alle Standorte, betrieben mit dem SOC des MSP. NIS2-Pflichtbaustein (Detektion & Vorfallbehandlung Art. 21).', 'category' => 'unterstuetzend', 'rto_minutes' => 240, 'rpo_minutes' => 60, 'downtime_cost_per_hour' => 500, 'fallback_process' => 'Bei SIEM-Ausfall manuelles Log-Review kritischer Systeme, SOC informieren, erhöhte Wachsamkeit. EDR-Agenten blockieren weiterhin lokal. Meldepflicht prüfen, falls Ausfall durch Angriff verursacht.', 'runbook_reference' => 'Runbook „SIEM/EDR-Störung" v1.0', 'system_priority_id' => null, 'emergency_level_id' => null, 'created_at' => $ts, 'updated_at' => $ts],
                ['id' => $sys['voip'], 'name' => 'Telefonanlage / VoIP (zentral)', 'description' => 'Zentrale VoIP-Telefonanlage für alle Standorte inkl. Durchwahlen, Heimleitungen, Pflegestützpunkte, externe Erreichbarkeit Angehörige.', 'category' => 'basisbetrieb', 'rto_minutes' => 60, 'rpo_minutes' => null, 'downtime_cost_per_hour' => 700, 'fallback_process' => 'Umleitung zentraler Rufnummern auf Mobiltelefone der Heimleitungen/Pflegestützpunkte. Notfall-SIM-Mobiltelefone je Haus aktivieren. Pflege-interne Kommunikation über DECT bleibt lokal verfügbar.', 'runbook_reference' => 'Runbook „VoIP-Ausfall" v1.1', 'system_priority_id' => null, 'emergency_level_id' => null, 'created_at' => $ts, 'updated_at' => $ts],
                ['id' => $sys['notstrom'], 'name' => 'Notstrom / NEA & USV (je Haus)', 'description' => 'Netzersatzanlage (Diesel-NEA) + USV je Pflegehaus für sicherheitsrelevante Verbraucher (Schwesternruf, BMA, Pflegetechnik, Kühlung, Notbeleuchtung).', 'category' => 'basisbetrieb', 'rto_minutes' => 15, 'rpo_minutes' => null, 'downtime_cost_per_hour' => 3000, 'fallback_process' => 'USV überbrückt bis NEA-Start (automatisch). Haustechnik prüft Anlauf, Dieselvorrat. Energieversorger informieren, priorisierte Wiederversorgung als Gesundheitseinrichtung. Bei NEA-Ausfall: Evakuierungsbereitschaft, Feuerwehr/THW-Kontakt.', 'runbook_reference' => 'Runbook „Stromausfall/Notstrom" v1.3', 'system_priority_id' => null, 'emergency_level_id' => null, 'created_at' => $ts, 'updated_at' => $ts],
                ['id' => $sys['bma'], 'name' => 'Brandmeldeanlage (je Haus)', 'description' => 'Brandmelde- und Alarmierungsanlage mit Aufschaltung zur Feuerwehr je Pflegehaus. Sicherheits- und genehmigungsrelevant (Heimbetrieb).', 'category' => 'basisbetrieb', 'rto_minutes' => 30, 'rpo_minutes' => null, 'downtime_cost_per_hour' => 2000, 'fallback_process' => 'Bei Ausfall sofort Brandsicherheitswache organisieren (Begehungen), Feuerwehr informieren, Wartungsdienst alarmieren. Heimaufsicht ggf. melden. Betrieb nur mit kompensierenden Maßnahmen.', 'runbook_reference' => 'Runbook „BMA-Störung" v1.0', 'system_priority_id' => null, 'emergency_level_id' => null, 'created_at' => $ts, 'updated_at' => $ts],
                ['id' => $sys['internet'], 'name' => 'Internet-Anbindung Zentrale (redundant + Backup)', 'description' => 'Redundanter Internetzugang der Zentrale (zwei Carrier) plus LTE/5G-Backup. Zentraler Übergang für MPLS, Telematik, Cloud-Dienste aller Häuser.', 'category' => 'basisbetrieb', 'rto_minutes' => 60, 'rpo_minutes' => null, 'downtime_cost_per_hour' => 1200, 'fallback_process' => 'Automatischer Failover auf zweiten Carrier, dann LTE/5G. Bei Total-Ausfall: Häuser nutzen lokales LTE-Backup, kritische Fachanwendungen priorisieren, MSP/Provider eskalieren.', 'runbook_reference' => null, 'system_priority_id' => null, 'emergency_level_id' => null, 'created_at' => $ts, 'updated_at' => $ts],
                ['id' => $sys['m365'], 'name' => 'E-Mail & Kollaboration (Microsoft 365)', 'description' => 'M365 für Verwaltung, Heimleitungen, Kommunikation. E-Mail, Teams, zentrale Dokumente. Conditional Access/MFA.', 'category' => 'geschaeftsbetrieb', 'rto_minutes' => 240, 'rpo_minutes' => 60, 'downtime_cost_per_hour' => 300, 'fallback_process' => 'M365-Webclient mobil; bei Total-Ausfall Telefon/SMS-Verteiler als Übergang. Externe Kommunikation über Pressestelle bündeln.', 'runbook_reference' => null, 'system_priority_id' => null, 'emergency_level_id' => null, 'created_at' => $ts, 'updated_at' => $ts],
            ],

            'system_dependencies' => [
                ['system_id' => $sys['internet'], 'depends_on_system_id' => $sys['notstrom'], 'sort' => 0, 'note' => 'Zentrale-Strom/USV.', 'created_at' => $ts, 'updated_at' => $ts],
                ['system_id' => $sys['rz'], 'depends_on_system_id' => $sys['notstrom'], 'sort' => 0, 'note' => 'RZ an USV + NEA der Zentrale.', 'created_at' => $ts, 'updated_at' => $ts],
                ['system_id' => $sys['vpn'], 'depends_on_system_id' => $sys['internet'], 'sort' => 0, 'note' => 'MPLS/SD-WAN über zentralen Internetübergang.', 'created_at' => $ts, 'updated_at' => $ts],
                ['system_id' => $sys['pflegedoku'], 'depends_on_system_id' => $sys['rz'], 'sort' => 0, 'note' => 'Läuft im zentralen RZ.', 'created_at' => $ts, 'updated_at' => $ts],
                ['system_id' => $sys['pflegedoku'], 'depends_on_system_id' => $sys['vpn'], 'sort' => 1, 'note' => 'Häuser greifen über VPN zu.', 'created_at' => $ts, 'updated_at' => $ts],
                ['system_id' => $sys['medikation'], 'depends_on_system_id' => $sys['pflegedoku'], 'sort' => 0, 'note' => 'In Pflegedoku integriert.', 'created_at' => $ts, 'updated_at' => $ts],
                ['system_id' => $sys['erp'], 'depends_on_system_id' => $sys['rz'], 'sort' => 0, 'note' => null, 'created_at' => $ts, 'updated_at' => $ts],
                ['system_id' => $sys['dienstplan'], 'depends_on_system_id' => $sys['rz'], 'sort' => 0, 'note' => null, 'created_at' => $ts, 'updated_at' => $ts],
                ['system_id' => $sys['backup'], 'depends_on_system_id' => $sys['rz'], 'sort' => 0, 'note' => 'Sichert RZ-Workloads.', 'created_at' => $ts, 'updated_at' => $ts],
                ['system_id' => $sys['siem'], 'depends_on_system_id' => $sys['internet'], 'sort' => 0, 'note' => 'SOC-Anbindung des MSP.', 'created_at' => $ts, 'updated_at' => $ts],
                ['system_id' => $sys['voip'], 'depends_on_system_id' => $sys['vpn'], 'sort' => 0, 'note' => 'VoIP über Standortvernetzung.', 'created_at' => $ts, 'updated_at' => $ts],
                ['system_id' => $sys['voip'], 'depends_on_system_id' => $sys['internet'], 'sort' => 1, 'note' => null, 'created_at' => $ts, 'updated_at' => $ts],
                ['system_id' => $sys['m365'], 'depends_on_system_id' => $sys['internet'], 'sort' => 0, 'note' => null, 'created_at' => $ts, 'updated_at' => $ts],
                ['system_id' => $sys['schwesternruf'], 'depends_on_system_id' => $sys['notstrom'], 'sort' => 0, 'note' => 'Lichtruf an Notstrom je Haus.', 'created_at' => $ts, 'updated_at' => $ts],
                ['system_id' => $sys['bma'], 'depends_on_system_id' => $sys['notstrom'], 'sort' => 0, 'note' => 'BMA an Notstrom je Haus.', 'created_at' => $ts, 'updated_at' => $ts],
                ['system_id' => $sys['kuehlkette'], 'depends_on_system_id' => $sys['notstrom'], 'sort' => 0, 'note' => 'Kühlschränke an Notstrom.', 'created_at' => $ts, 'updated_at' => $ts],
            ],

            'insurance_policies' => [
                ['id' => Helpers::uuid(), 'type' => 'cyber', 'insurer' => 'Allianz Cyber (Health/KRITIS)', 'policy_number' => 'CY-SZ-2026-001', 'hotline' => '0800 1112020', 'email' => 'cyber-kritis@allianz.example', 'reporting_window' => 'unverzüglich, spätestens 24 Stunden', 'contact_name' => 'Hr. Schubert', 'notes' => 'Deckung 5 Mio €, Spezialtarif Gesundheits-/KRITIS-Einrichtungen. Inkl. Incident-Response-Retainer, Betriebsunterbrechung, Forensik, Bewohnerdaten Art. 9 DSGVO.', 'deductible' => '25.000 €', 'created_at' => $ts, 'updated_at' => $ts],
                ['id' => Helpers::uuid(), 'type' => 'liability', 'insurer' => 'Versicherungskammer Bayern (Betriebs-/Berufshaftpflicht)', 'policy_number' => 'BHV-SZ-2025-44', 'hotline' => '089 2160-0', 'email' => 'heilberufe-schaden@vkb.example', 'reporting_window' => 'binnen 7 Tagen', 'contact_name' => 'Fr. Mayer', 'notes' => 'Betriebs- und Berufshaftpflicht für stationäre Pflegeeinrichtungen, Vermögensschaden, Personenschäden Bewohner.', 'deductible' => '5.000 €', 'created_at' => $ts, 'updated_at' => $ts],
                ['id' => Helpers::uuid(), 'type' => 'property', 'insurer' => 'Gothaer Sach (Gebäude/Inhalt)', 'policy_number' => 'SACH-SZ-2025-77', 'hotline' => '0221 308-00', 'email' => 'sach-schaden@gothaer.example', 'reporting_window' => 'unverzüglich', 'contact_name' => 'Hr. Klein', 'notes' => 'Gebäude- und Inhaltsversicherung beider Häuser + Zentrale/RZ. Elektronik-/RZ-Technik, Feuer/Leitungswasser.', 'deductible' => '2.500 €', 'created_at' => $ts, 'updated_at' => $ts],
                ['id' => Helpers::uuid(), 'type' => 'business_interruption', 'insurer' => 'HDI Betriebsunterbrechung', 'policy_number' => 'BI-SZ-2025-22', 'hotline' => '0800 4434464', 'email' => 'bu-schaden@hdi.example', 'reporting_window' => 'binnen 7 Tagen', 'contact_name' => 'Hr. Lorenz', 'notes' => 'Ertragsausfall/Mehrkosten bei Betriebsunterbrechung, auch infolge Cyber-Vorfall (Rückwirkungsschäden zentrale IT).', 'deductible' => '10.000 €', 'created_at' => $ts, 'updated_at' => $ts],
            ],

            'communication_templates' => [
                ['id' => Helpers::uuid(), 'name' => 'BSI-Erstmeldung NIS2 / §8b BSIG (Frühwarnung 24h)', 'audience' => 'authorities', 'channel' => 'email', 'subject' => 'Erstmeldung erheblicher Sicherheitsvorfall – {{ firma }} (wichtige Einrichtung, Sektor Gesundheit)', 'body' => "An: BSI-Meldestelle (meldestelle@bsi.bund.de / Meldeportal)\n\nErstmeldung (Frühwarnung) gemäß §8b BSIG / NIS2 – erheblicher Sicherheitsvorfall.\n\nEinrichtung: {{ firma }} (wichtige Einrichtung, Sektor Gesundheit / stationäre Pflege)\nMeldende Person: {{ melder }} ({{ rolle }})\nZeitpunkt der Kenntnis: {{ zeitpunkt }}\nArt des Vorfalls: {{ vorfall }}\nBetroffene Systeme/Standorte: {{ systeme }}\nAuswirkung auf Versorgung der Bewohner: {{ auswirkung }}\nVerdacht rechtswidrige/böswillige Handlung: {{ ja_nein }}\nGrenzüberschreitende Auswirkung: {{ ja_nein }}\nBisherige Maßnahmen: {{ massnahmen }}\n\nFolgemeldung (binnen 72h) und Abschlussbericht (binnen 1 Monat) folgen.", 'fallback' => 'Parallel BSI-Lagezentrum telefonisch 0228 99 9582-222. Meldeportal-Zugang im Passwort-Safe.', 'sort' => 0, 'scenario_id' => null, 'created_at' => $ts, 'updated_at' => $ts],
                ['id' => Helpers::uuid(), 'name' => 'DSGVO-Meldung Aufsichtsbehörde (Bewohner-/Gesundheitsdaten)', 'audience' => 'authorities', 'channel' => 'email', 'subject' => 'Meldung gemäß Art. 33 DSGVO – {{ firma }} (besondere Kategorien Art. 9)', 'body' => "An: LfDI Baden-Württemberg (poststelle@lfdi.bwl.de)\n\nMeldung einer Verletzung des Schutzes personenbezogener Daten gemäß Art. 33 DSGVO.\n\nVerantwortlicher: {{ firma }}\nBranche: Stationäre Senioren-/Pflegeeinrichtungen (Verbund)\nZeitpunkt der Kenntnis: {{ zeitpunkt }}\nArt der Verletzung: {{ vorfall }}\nKategorien betroffener Daten: Gesundheits-/Pflegedaten besonderer Kategorien (Art. 9)\nBetroffene Personen (geschätzt): {{ anzahl }} Bewohner/Beschäftigte\nWahrscheinliche Folgen: {{ folgen }}\nErgriffene/geplante Maßnahmen: {{ massnahmen }}\nDSB: Klaus Engel (extern), Tel. 0172 5550040\n\nMeldung binnen 72h; ggf. Benachrichtigung Betroffener nach Art. 34.", 'fallback' => 'DSB vorab telefonisch einbinden. Mit BSI-Meldung abstimmen, Doppelmeldepflichten beachten.', 'sort' => 1, 'scenario_id' => null, 'created_at' => $ts, 'updated_at' => $ts],
                ['id' => Helpers::uuid(), 'name' => 'Heimaufsicht-Meldung (besonderes Vorkommnis)', 'audience' => 'authorities', 'channel' => 'email', 'subject' => 'Meldung besonderes Vorkommnis – {{ firma }}, {{ haus }} (WTG/Heimrecht)', 'body' => "An: Heimaufsicht / Aufsichtsbehörde WTG\n\nMeldung eines besonderen Vorkommnisses mit möglicher Auswirkung auf die Versorgung der Bewohner.\n\nEinrichtung: {{ firma }} – {{ haus }}\nZeitpunkt: {{ zeitpunkt }}\nVorkommnis: {{ vorfall }} (z. B. Ausfall Schwesternruf / Pflegedoku / Notstrom)\nAuswirkung auf Bewohnerversorgung: {{ auswirkung }}\nKompensierende Sofortmaßnahmen: {{ massnahmen }}\nAnsprechpartner vor Ort: {{ heimleitung }}\n\nWir halten Sie über den weiteren Verlauf informiert.", 'fallback' => 'Telefonische Vorabinformation an Heimaufsicht parallel zur schriftlichen Meldung.', 'sort' => 2, 'scenario_id' => null, 'created_at' => $ts, 'updated_at' => $ts],
                ['id' => Helpers::uuid(), 'name' => 'Angehörigen-Information Verbund (Anrufskript)', 'audience' => 'customers', 'channel' => 'phone', 'subject' => null, 'body' => "Anrufskript Angehörige (zentral durch Pressestelle/Verwaltung koordiniert):\n\nGuten Tag, hier {{ ansprechpartner }} von der {{ firma }}, {{ haus }}. Ich rufe Sie wegen Frau/Herrn {{ bewohner }} an.\n\nAufgrund einer technischen Störung in unseren IT-Systemen arbeiten wir aktuell im Notbetrieb. Die pflegerische Versorgung und Sicherheit Ihrer Angehörigen ist jederzeit gewährleistet — unser Personal dokumentiert vorübergehend auf Papier und ist verstärkt präsent.\n\nEs besteht kein Anlass zur Sorge. Bei Fragen erreichen Sie uns unter {{ rueckrufnummer }}.\n\nWir informieren Sie, sobald der Normalbetrieb wiederhergestellt ist. Vielen Dank für Ihr Verständnis.", 'fallback' => 'Sammel-Information per Aushang an Haustüren/Wohnbereichen + Info auf Mailbox-Ansage der Zentrale.', 'sort' => 3, 'scenario_id' => null, 'created_at' => $ts, 'updated_at' => $ts],
                ['id' => Helpers::uuid(), 'name' => 'Mitarbeiter-Sammelanweisung Notbetrieb (Intranet/SMS)', 'audience' => 'employees', 'channel' => 'intranet', 'subject' => 'Aktivierung IT-Notbetrieb – Anweisung an alle Häuser', 'body' => "WICHTIG {{ firma }} – IT-NOTBETRIEB AKTIV (Stand {{ zeitpunkt }})\n\nBetroffen: {{ systeme }}. Krisenstab tagt.\n\nAnweisungen an alle Wohnbereiche/Häuser:\n1. Sofort auf Papier-Pflegedoku umstellen (Vordrucke je Wohnbereich).\n2. Medikamentenstellung nach ausgedrucktem Medikationsplan, Vier-Augen-Prinzip.\n3. Bei Schwesternruf-Ausfall: engmaschige Sichtkontrollen, DECT-Notruf.\n4. KEINE Bewohner-/Gesundheitsdaten über private Geräte/Apps versenden.\n5. Verdächtige E-Mails/Vorfälle sofort an IT/SOC melden.\n6. Angehörigen-Auskünfte nur nach zentraler Sprachregelung (Pressestelle).\n\nRückfragen: IT-Leitung 0711 8800 110 / Pflegedirektion 0711 8800 120.", 'fallback' => 'Bei Intranet-Ausfall: SMS-Verteiler an Heimleitungen/PDLs + Aushang Wohnbereiche, Telefonkette.', 'sort' => 4, 'scenario_id' => null, 'created_at' => $ts, 'updated_at' => $ts],
                ['id' => Helpers::uuid(), 'name' => 'Presse-Statement bei Cyberangriff', 'audience' => 'press', 'channel' => 'email', 'subject' => 'Pressestatement {{ firma }} – IT-Sicherheitsvorfall', 'body' => "Pressestatement (Freigabe ausschließlich durch Geschäftsführung + Pressestelle):\n\nDie {{ firma }} wurde am {{ datum }} Ziel eines IT-Sicherheitsvorfalls. Wir haben unsere Notfallpläne aktiviert, externe IT-Sicherheitsexperten (SOC) hinzugezogen und den Vorfall den zuständigen Behörden (BSI, Datenschutzaufsicht) gemeldet.\n\nDie pflegerische Versorgung und Sicherheit unserer Bewohnerinnen und Bewohner ist zu jedem Zeitpunkt gewährleistet; betroffene Bereiche arbeiten im Notbetrieb.\n\nDie Aufklärung des Vorfalls hat höchste Priorität. Sobald gesicherte Erkenntnisse vorliegen, informieren wir transparent.\n\nKontakt Pressestelle: {{ pressekontakt }}", 'fallback' => 'Nur freigegebene Sprachregelung verwenden. Einheitliche Aussagen über alle Häuser, keine Einzelauskünfte an Presse vor Ort.', 'sort' => 5, 'scenario_id' => null, 'created_at' => $ts, 'updated_at' => $ts],
            ],

            'emergency_resources' => [
                ['id' => Helpers::uuid(), 'type' => 'offline_backup', 'name' => 'Offline-/Immutable-Backup (extern, 3-2-1)', 'description' => 'Externe, vom Netz getrennte (immutable) Backup-Kopie aller kritischen Systeme (Pflegedoku, Medikation, ERP, Identity). Ransomware-sicher, Grundlage des KRITIS-Wiederanlaufs.', 'location' => 'Externes Rechenzentrum / gesichertes Auslagerungsobjekt', 'access_holders' => 'Sven Kramer (CISO), Marc Heller (RZ), Notfall-Zugang im Passwort-Safe', 'last_check_at' => Helpers::date(-14), 'next_check_at' => Helpers::date(16), 'notes' => 'Restore-Fähigkeit + Integrität monatlich verifizieren. Offline-Kopie darf nie dauerhaft online erreichbar sein.', 'sort' => 0, 'created_at' => $ts, 'updated_at' => $ts, 'last_reminder_sent_at' => null],
                ['id' => Helpers::uuid(), 'type' => 'password_safe', 'name' => 'Notfall-Passwortsafe / Break-Glass-Zugänge', 'description' => 'Verschlüsselter Notfalltresor mit administrativen Zugängen (RZ, Backup, SIEM, BSI-Meldeportal, Provider-Hotlines, Domain). Break-Glass-Verfahren dokumentiert.', 'location' => 'KeePass/Hardware-Token im Tresor Zentrale + versiegelte Kopie Tresor GF', 'access_holders' => 'Geschäftsführung, CISO, Stv. IT-Leitung (versiegelt, Zugriff protokolliert)', 'last_check_at' => Helpers::date(-30), 'next_check_at' => Helpers::date(60), 'notes' => 'Zugriff protokollieren, nach Nutzung Zugangsdaten rotieren. Teil des ISMS.', 'sort' => 1, 'created_at' => $ts, 'updated_at' => $ts, 'last_reminder_sent_at' => null],
                ['id' => Helpers::uuid(), 'type' => 'generator_ups', 'name' => 'Notstromaggregat (NEA) + USV je Haus', 'description' => 'Diesel-Netzersatzanlage je Pflegehaus für sicherheitsrelevante Verbraucher (Schwesternruf, BMA, Kühlung, Notbeleuchtung) + USV im RZ.', 'location' => 'Technikraum Sonnenhalde, Technikraum Lindenpark, USV-Raum RZ Zentrale', 'access_holders' => 'Roland Fischer (Haustechnik), Heimleitungen, Wartungsdienst', 'last_check_at' => Helpers::date(-30), 'next_check_at' => Helpers::date(60), 'notes' => 'Monatlicher Lastlauf, Dieselvorrat ≥ 24h prüfen, Wartungsvertrag aktiv.', 'sort' => 2, 'created_at' => $ts, 'updated_at' => $ts, 'last_reminder_sent_at' => null],
                ['id' => Helpers::uuid(), 'type' => 'offline_docs', 'name' => 'Papier-Bewohnerlisten & Medikationspläne (je Haus)', 'description' => 'Tagesaktuell gedruckte Bewohnerliste (Wohnbereich, Pflegegrad, Notfallkontakt, Hausarzt) + aktueller Medikationsplan je Bewohner. Grundlage des Papier-Notbetriebs.', 'location' => 'Pflegestützpunkt jedes Wohnbereichs (verschlossen), je Haus', 'access_holders' => 'PDLs, Pflegefachkräfte der Häuser, Heimleitungen', 'last_check_at' => Helpers::date(-1), 'next_check_at' => Helpers::date(0), 'notes' => 'TÄGLICH neu drucken (Cron). Besonders sensibel (Art. 9) — verschlossen aufbewahren, Zugriff geregelt.', 'sort' => 3, 'created_at' => $ts, 'updated_at' => $ts, 'last_reminder_sent_at' => null],
                ['id' => Helpers::uuid(), 'type' => 'emergency_sim', 'name' => 'Notfall-SIM / Krisen-Mobiltelefone', 'description' => 'Mobiltelefone mit SIM eines alternativen Netzbetreibers je Haus + Zentrale für Krisenstab und Telefon-Failover, unabhängig von VoIP/Internet.', 'location' => 'Tresor Zentrale + Pflegestützpunkt je Haus', 'access_holders' => 'Krisenstab, Heimleitungen, PDLs', 'last_check_at' => Helpers::date(-60), 'next_check_at' => Helpers::date(30), 'notes' => 'Halbjährlicher Aktivierungs-/Akkucheck. Nummernliste im Notfallhandbuch.', 'sort' => 4, 'created_at' => $ts, 'updated_at' => $ts, 'last_reminder_sent_at' => null],
                ['id' => Helpers::uuid(), 'type' => 'offline_docs', 'name' => 'Notfallhandbuch / BCM-Ordner (Papier)', 'description' => 'Gedrucktes Notfall-/BCM-Handbuch inkl. Meldeketten (BSI 24h/72h, LfDI, Heimaufsicht), Telefonlisten, Runbooks, Wiederanlaufreihenfolge RZ, Krisenstab-Aufstellung.', 'location' => 'Krisenraum Zentrale, je Heimleitung (Haus A/B), CISO privat', 'access_holders' => 'Krisenstab, IT-Leitung, ISB, Heimleitungen, Pflegedirektion', 'last_check_at' => Helpers::date(-30), 'next_check_at' => Helpers::date(150), 'notes' => 'Bei jedem Review-Zyklus (6 Monate) aktualisieren, Versionsstand dokumentieren.', 'sort' => 5, 'created_at' => $ts, 'updated_at' => $ts, 'last_reminder_sent_at' => null],
            ],

            'handbook_tests' => [
                ['id' => Helpers::uuid(), 'type' => 'communication', 'name' => 'BSI-/NIS2-Meldeketten-Test (24h/72h)', 'description' => 'Trockentest der gesamten Meldekette: Vorfall erkannt → CISO/ISB → GF → BSI-Erstmeldung (Portal) binnen 24h, parallel LfDI/Heimaufsicht. Zuständigkeiten, Zugänge (Passwort-Safe) und Fristen prüfen.', 'interval' => 'biannually', 'last_executed_at' => Helpers::date(-120), 'next_due_at' => Helpers::date(60), 'responsible_employee_id' => $emp['isb'], 'result_notes' => null, 'sort' => 0, 'created_at' => $ts, 'updated_at' => $ts, 'last_reminder_sent_at' => null],
                ['id' => Helpers::uuid(), 'type' => 'recovery', 'name' => 'KRITIS-Wiederanlauf Rechenzentrum', 'description' => 'Übung Wiederanlauf zentrales RZ nach Total-Ausfall: dokumentierte Reihenfolge (Identity → Pflegedoku → Medikation → ERP), RTO/RPO messen, Häuser-Notbetrieb koordinieren. Mit MSP/SOC.', 'interval' => 'yearly', 'last_executed_at' => Helpers::date(-200), 'next_due_at' => Helpers::date(165), 'responsible_employee_id' => $emp['it_lead'], 'result_notes' => null, 'sort' => 1, 'created_at' => $ts, 'updated_at' => $ts, 'last_reminder_sent_at' => null],
                ['id' => Helpers::uuid(), 'type' => 'tabletop', 'name' => 'Tabletop Ransomware – Ausfall zentrale Pflegedoku', 'description' => 'Planspiel: Ransomware verschlüsselt RZ, zentrale Pflegedoku in allen Häusern aus. Durchspielen: Papier-Notbetrieb, Meldepflichten (BSI/DSGVO), Krisenkommunikation, Restore aus Offline-Backup, GF-Entscheidungen (§38 BSIG).', 'interval' => 'yearly', 'last_executed_at' => Helpers::date(-150), 'next_due_at' => Helpers::date(215), 'responsible_employee_id' => $emp['gf'], 'result_notes' => null, 'sort' => 2, 'created_at' => $ts, 'updated_at' => $ts, 'last_reminder_sent_at' => null],
                ['id' => Helpers::uuid(), 'type' => 'backup_restore', 'name' => 'Restore-Test 3-2-1-Backup (Offline-Kopie)', 'description' => 'Tatsächlicher Wiederherstellungstest kritischer Systeme aus der externen Offline-/Immutable-Kopie. Datenintegrität + RPO validieren, Restore-Dauer dokumentieren.', 'interval' => 'quarterly', 'last_executed_at' => Helpers::date(-60), 'next_due_at' => Helpers::date(30), 'responsible_employee_id' => $emp['it_stv'], 'result_notes' => null, 'sort' => 3, 'created_at' => $ts, 'updated_at' => $ts, 'last_reminder_sent_at' => null],
                ['id' => Helpers::uuid(), 'type' => 'contact_check', 'name' => 'Quartals-Erreichbarkeit Krisenstab', 'description' => 'Erreichbarkeit aller Krisenstab-Mitglieder + Stellvertreter, Heimleitungen, externer DSB, MSP/SOC-24/7, BSI-Lagezentrum, Provider-Hotlines testen. Notfall-SIM-Geräte prüfen.', 'interval' => 'quarterly', 'last_executed_at' => Helpers::date(-60), 'next_due_at' => Helpers::date(30), 'responsible_employee_id' => $emp['isb'], 'result_notes' => null, 'sort' => 4, 'created_at' => $ts, 'updated_at' => $ts, 'last_reminder_sent_at' => null],
            ],

            'system_tasks' => [
                ['id' => Helpers::uuid(), 'system_id' => $sys['rz'], 'title' => 'Patch-Management RZ/Server', 'description' => 'Monatlicher Patch-Zyklus für Hypervisor, Server-OS, zentrale Fachanwendungen. Sandbox-Test, Wartungsfenster mit Häusern abstimmen, ISMS-Doku.', 'due_date' => Helpers::date(20), 'completed_at' => null, 'sort' => 0, 'created_at' => $ts, 'updated_at' => $ts],
                ['id' => Helpers::uuid(), 'system_id' => $sys['siem'], 'title' => 'SIEM-Alarmierung / Use-Cases testen', 'description' => 'Mit SOC des MSP Test-Alarme auslösen (z. B. Brute-Force, Daten-Exfiltration), Reaktionszeit und Eskalationskette prüfen. NIS2-Detektionsnachweis.', 'due_date' => Helpers::date(30), 'completed_at' => null, 'sort' => 0, 'created_at' => $ts, 'updated_at' => $ts],
                ['id' => Helpers::uuid(), 'system_id' => $sys['rz'], 'title' => 'Penetrationstest (extern)', 'description' => 'Jährlicher externer Pentest auf zentrale Systeme + Standortvernetzung, Findings im ISMS nachverfolgen (ISO 27001 / Art. 21 NIS2).', 'due_date' => Helpers::date(120), 'completed_at' => null, 'sort' => 1, 'created_at' => $ts, 'updated_at' => $ts],
                ['id' => Helpers::uuid(), 'system_id' => $sys['notstrom'], 'title' => 'USV-/Notstrom-Test (NEA-Lastlauf)', 'description' => 'Lastlauf der NEA je Haus, USV-Akkutest im RZ, Dieselvorrat und automatischer Anlauf prüfen, Protokoll für Haustechnik.', 'due_date' => Helpers::date(25), 'completed_at' => null, 'sort' => 0, 'created_at' => $ts, 'updated_at' => $ts],
                ['id' => Helpers::uuid(), 'system_id' => $sys['backup'], 'title' => 'Backup-Restore-Stichprobe', 'description' => 'Stichprobenhafte Wiederherstellung einzelner Dateien/VMs, Integrität prüfen, Restore-Zeiten dokumentieren.', 'due_date' => Helpers::date(40), 'completed_at' => null, 'sort' => 0, 'created_at' => $ts, 'updated_at' => $ts],
                ['id' => Helpers::uuid(), 'system_id' => $sys['pflegedoku'], 'title' => 'Berechtigungs-Review (Rollen/Mandanten)', 'description' => 'Halbjährliches Review der Zugriffsrechte über alle Häuser/Mandanten (Least Privilege), verwaiste Konten deaktivieren, Protokoll ISMS.', 'due_date' => Helpers::date(60), 'completed_at' => null, 'sort' => 0, 'created_at' => $ts, 'updated_at' => $ts],
                ['id' => Helpers::uuid(), 'system_id' => $sys['kuehlkette'], 'title' => 'Kühlketten-Sensoren kalibrieren/prüfen', 'description' => 'Temperatursensoren je Haus prüfen/kalibrieren, Alarmierung testen, Notfallplan Kühlausfall mit Apotheke abstimmen.', 'due_date' => Helpers::date(50), 'completed_at' => null, 'sort' => 0, 'created_at' => $ts, 'updated_at' => $ts],
                ['id' => Helpers::uuid(), 'system_id' => $sys['schwesternruf'], 'title' => 'Funktionstest Schwesternruf je Haus', 'description' => 'Lichtrufanlage je Wohnbereich testen (Ruf, Quittierung, DECT-Anbindung), Wartungsdienst-Termin koordinieren.', 'due_date' => Helpers::date(35), 'completed_at' => null, 'sort' => 0, 'created_at' => $ts, 'updated_at' => $ts],
                ['id' => Helpers::uuid(), 'system_id' => $sys['m365'], 'title' => 'Phishing-Awareness & MFA-Review', 'description' => 'Simulierte Phishing-Kampagne (~600 MA), Conditional Access/MFA-Abdeckung prüfen, Schulungsnachweis ISMS.', 'due_date' => Helpers::date(90), 'completed_at' => null, 'sort' => 0, 'created_at' => $ts, 'updated_at' => $ts],
                ['id' => Helpers::uuid(), 'system_id' => $sys['vpn'], 'title' => 'SD-WAN-Failover je Standort testen', 'description' => 'MPLS-Strecke je Haus simuliert trennen, LTE/5G-Failover messen, Zugriff auf zentrale Pflegedoku validieren.', 'due_date' => Helpers::date(45), 'completed_at' => null, 'sort' => 0, 'created_at' => $ts, 'updated_at' => $ts],
            ],
        ]);
    }
}
